rust-lang/rustc-dev-guide

- src/type-inference.md
Also
- remove stale reference
- I don't see how ty chapter explains anything here
> fix lifetime name

- src/the-parser.md
> remove incorrect info

- src/diagnostics/diagnostic-structs.md
- src/diagnostics/translation.md
Due to changes by https://github.com/rust-lang/rust/pull/100377
> Update slug style to use _ instead of -

- src/diagnostics/diagnostic-structs.md
Same kind of fixes as in #1437
> More syntax fix

- src/diagnostics/diagnostic-structs.md
The compiler forced me to add this while I was working on https://github.com/rust-lang/rust/pull/100730
> Add missing lifetime

- src/diagnostics/diagnostic-structs.md
These were all replaced by uses of typed identifiers but some documentation wasn't updated.
> diagnostics: fix outdated use of string slugs

- src/diagnostics/diagnostic-structs.md
> Document changes introduced by kind-less SessionDiagnostics

- ci/date-check/src/main.rs
One could not run it like the following, for the would be a panic:
cargo run --manifest-path ci/date-check/Cargo.toml .
> make date-check more easy to use

- src/building/prerequisites.md
With the recent upgrade to C++17 in LLVM, this increases the minimum requirements for building LLVM from source. Matches those at https://llvm.org/docs/GettingStarted.html#host-c-toolchain-both-compiler-and-standard-library
> Updates prereqs to build LLVM from source for C++17.

- src/diagnostics/lintstore.md
> Refine the lintstore section

- src/stabilization_guide.md
Due to https://github.com/rust-lang/rust/pull/100591 the stabilization process is changed to now use `CURRENT_RUSTC_VERSION` instead of spelling out whatever version is currently the latest. This placeholder will be replaced during the release process with the correct version.
> Update the stabilization guide to refer to the new placeholder system

- src/building/bootstrapping.md
- src/building/new-target.md
- src/contributing.md
- src/diagnostics.md
- src/git.md
- src/name-resolution.md
- src/overview.md
- src/rustc-driver.md
- src/tests/intro.md
RLS has been removed as of https://github.com/rust-lang/rust/pull/100863. This updates the guide to remove information related to it.
> Update for removal of RLS

- src/building/prerequisites.md
Yes, the reference is a page on Java's documentation but that's the most complete and most official looking reference I could find.
> Add reference for updating Windows PATH and fix typo

- src/diagnostics/diagnostic-structs.md
> Document multipart_suggestion derive on SessionSubdiagnostic

- src/feature-gates.md
- src/implementing_new_features.md
I don't know if I'm holding it wrong, but without these steps, I get the following error, for example:
```
error[E0425]: cannot find value `manually_drop_attr` in module `sym`                                                                                                                                                [47/1826]
--> compiler/rustc_feature/src/active.rs:436:14
|
436 |     (active, manually_drop_attr, "1.64.0", Some(100344), None),
|              ^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `manually_drop`
|
::: /usr/local/google/home/devinj/local_programming/rust-compiler/compiler/rustc_span/src/symbol.rs:23:1
|
23  | symbols! {
| -------- similarly named constant `manually_drop` defined here
```
> Add symbol-addition to the how-to for new features

- src/const-eval.md
Dependent on getting https://github.com/rust-lang/rust/pull/83234 merged first.
cc @rust-lang/wg-const-eval
> Explain the new valtree system for type level constants.

- src/building/how-to-build-and-run.md
Adds a note that for custom toolchains you may want to build `rust-analyzer-proc-macro-srv`, see https://github.com/rust-lang/rust/pull/101873
> Add a note about building `rust-analyzer-proc-macro-srv`

- src/diagnostics.md
- src/diagnostics/diagnostic-structs.md
- src/diagnostics/translation.md
Renamed Diagnostics/Subdiagnostics traits and macros in https://github.com/rust-lang/rust/pull/101558
Cc @rust-lang/wg-diagnostics
> [Diagnostics] - Update docs to match renamed Diagnostics traits and macros

- src/building/suggested.md
The proc-macro server path is required for proc-macros to properly work in r-a when working on rustc.
Pointing the sysroot to the stage0 one is more correct than using the system installed one.
Related PRs in rust-analyzer:
https://github.com/rust-lang/rust-analyzer/pull/13327
https://github.com/rust-lang/rust-analyzer/pull/13326
Note, these configs only work with the next r-a release, that is tomorrows nightly, or next monday's stable release!
> Update r-a config suggestions

- src/about-this-guide.md
Previously, "Building and debugging `rustc`" linked to the getting started page, which isn't correct. If people want that page, it already appears in the sidebar, and is the next sequential page.
> Link to the correct page in "about this guide"

- src/diagnostics/diagnostic-structs.md
Following https://github.com/rust-lang/rust/pull/102306 and https://github.com/rust-lang/rust/pull/102395
> Rename typeck to hir_analysis

- src/tests/running.md
https://github.com/rust-lang/rust/pull/102193 changed the flags you need to pass to run `remote-test-server`, and this PR updates the documentation to reflect that.
> Update running tests with the new flags

- src/diagnostics/diagnostic-structs.md
rust-lang/rust#102189 added support for enums to the diagnostic derive, so this documentation needs updating.
> diagnostic structs: derive on enum

- .gitattributes
When doing a git grep (of rustc-dev-guide or of rust-lang/rust with
--recurse-submodules), if the grep happens to match within the minified
javascript, the resulting long single lines can cause a text pager or
editor to slow down and distract from more useful matches.
Minified javascript isn't formatted for human consumption, by
definition, so mark it as binary, which causes git grep to instead just
state that it matches without printing the matching "line".
> .gitattributes: Mark minified javascript as binary to filter greps

- src/backend/debugging.md
Using `llvm.godbolt.org` subdomain should automatically select the correct LLVM-IR language.
> Use llvm subdomain for compiler-explorer link

- src/building/prerequisites.md
Fedora and Ubuntu users have reported missing `libstdc++-static` when attempting to build the compiler.
> Add missing prerequisite for some Linux distros

- src/contributing.md
- src/git.md
As of https://github.com/rust-lang/rust/pull/102028 miri is now subtree.
> miri is no longer a submodule but a subtree.

- src/building/suggested.md
This setting will cause r-a to invoke the build script command only once in the root of the project instead of once per workspace which causes problems when the `linkedProjects` settings is used to target other workspaces in the repo.
In theory the same setting could be applied to `checkOnSave`, but for that to work `x.py` needs to fix up the paths of diagnostics to be relative to the project root instead of the workspace roots the diagnostics are emitted from.
This depends on https://github.com/rust-lang/rust-analyzer/pull/13128 which will have the next stable r-a release on coming monday / nightly in ~2 hours
> Update rust-analyzer suggestions

- src/diagnostics/diagnostic-structs.md
- src/diagnostics/translation.md
As implemented in rust-lang/rust#103345
> Update diagnostics to flat fluent message paths

- src/compiler-team.md
- src/contributing.md
- src/getting-started.md
As of https://github.com/rust-lang/rust/pull/103492, `rust-lang/rust` no longer uses highfive to handle reviewer rotation. Triagebot has token over this responsibility. This PR updates the documentation for this change.
> Update for highfive transition.

- src/building/suggested.md
According to https://github.com/rust-lang/rust/commit/8873e33806487a0fb12143772b1a3c1544edbe0b
> Running with --bless causes the push to succeed if there are fixable
formatting changes, but the changes don't make it into the push.
>
> We should have the user rerun with --bless (or x.py fmt) and commit the
changes themselves (they might want to amend a particular commit, for instance).
So update the hook documentation with that in mind.
> Remove `--bless` from pre-push hook suggestion

- src/backend/monomorph.md
- src/macro-expansion.md
- src/mir/dataflow.md
- src/mir/drop-elaboration.md
- src/mir/passes.md
- src/parallel-rustc.md
- src/ty-fold.md
I found a few typos while reading through the guide.
> Fixes some typos

- src/query.md
- queries always need a description
- `QueryDescription` isn't just for descriptions (it's actually not for descriptions at all now) and always implemented by the macro
- queries are not grouped into categories
cc @cjgillot
> Update outdated queries section

- src/diagnostics/diagnostic-structs.md
Added by rust-lang/rust#103209.
> Document multiple alternative suggestions on diagnostic structs

- src/bug-fix-procedure.md
- src/macro-expansion.md
- src/part-5-intro.md
- src/stability.md
I noticed the weird formatting of the ordered lists at https://rustc-dev-guide.rust-lang.org/macro-expansion.html. I believe this is caused by the 0-based numbering of these lists. Because it seemed like all the other ordered lists in this book were 1-based, I assumed this was an anomaly and changed all the 0-based lists to start from 1.
I apologize If it was intentional to have these start from 0, and I will close this PR if that is the case.
> Consistent ordered list indexing

- src/type-inference.md
cc @spastorino @compiler-errors
> rewrite the section about regions in the trait solver

- src/backend/updating-llvm.md
> date-check: updating-llvm

- src/backend/updating-llvm.md
Also, keep it trimmed... if a formal policy is adopted, this text can be updated to indicate so.
> updating-llvm: keep a calm tone

- src/constants.md
https://github.com/rust-lang/project-const-generics/pull/21 removed the link. This replaces it with an issue link mentioned on the design docs.
Fixes #1498
> Fix a broken design docs link about unused substs bug

- src/queries/incremental-compilation-in-detail.md
Updates the location of the `try_mark_green` algorithm from `compiler/rustc_middle/src/dep_graph/graph.rs` to [`compiler/rustc_middle/src/dep_graph/graph.rs`](https://github.com/rust-lang/rust/blob/stable/compiler/rustc_query_system/src/dep_graph/graph.rs#L574) .
> Update path for `try_mark_green` implementation

- src/contributing.md
Cc https://github.com/rust-lang/rust/issues/104962
> clarify subtree tool policy

- src/backend/monomorph.md
Just fixing a small inaccuracy. Pretty sure we meant to say heap here :)
> Fix small inaccuracy in monomorph page

- src/memory.md
- src/ty.md
This is being removed from rustc in https://github.com/rust-lang/rust/pull/104898
> Remove TyS

- src/appendix/background.md
- src/appendix/bibliography.md
- src/contributing.md
- src/overview.md
- src/query.md
- src/tests/adding.md
- src/type-checking.md
This replaces a bunch of broken links. A few things I'd like to mention:
- citeseerx.ist.psu.edu's PDF links are broken, I searched alternatives on DuckDuckGo but I haven't made sure all the websites are reliable. Any suggestions are welcome!
- https://github.com/rust-lang/rust/pull/102302 changed the logic and `first_token` no longer exists. I chose `advance_token` but `next_token` might be suitable.
> fix: Fix broken links

- src/contributing.md
also moved link to the end, for there are 3 uses in the file
> share same link

- src/mir/passes.md
- src/mir/visitor.md
> Replace references to NoLandingPads in MIR pass documents

- src/sanitizers.md
This commit adds initial documentation for LLVM Kernel Control Flow Integrity (KCFI) support to the Rust compiler (see rust-lang/rust#105109 and rust-lang/rust#89653).
> Add documentation for LLVM KCFI support

- src/compiler-debugging.md
- src/diagnostics.md
Followup to https://github.com/rust-lang/rust/pull/103217
> Add -Ztrack-diagnostics information

- src/borrow_check.md
Fixes minor typo - `rustc_borrow_ck` -> `rustc_borrowck`.
> Fix rustc_borrowck crate name typo

- src/building/suggested.md
- src/contributing.md
- src/rustdoc.md
- src/tests/running.md
This avoids having to manually modify the configuration in the docs.
Companion to https://github.com/rust-lang/rust/pull/104854 and shouldn't be merged before.
> Replace `$TARGET` with `host`

- src/building/how-to-build-and-run.md
- src/building/prerequisites.md
See a detailed explanation in the commit messages. This is a companion PR to https://github.com/rust-lang/rust/pull/105465 and should not be merged before.
- Update sentence about LLVM to match the new defaults
- Move information about dependencies to the rust-lang/rust readme
- Move "create a config.toml" after the section explaning x.py
- Remove unnecessary detail in building chapter
- Remove initial section on submodules
> Simplify "how to build and run" section

- src/appendix/humorust.md
- src/asm.md
- src/building/bootstrapping.md
- src/building/how-to-build-and-run.md
- src/building/suggested.md
- src/compiler-src.md
- src/incrcomp-debugging.md
- src/llvm-coverage-instrumentation.md
- src/mir/optimizations.md
- src/profile-guided-optimization.md
- src/rustdoc-internals.md
- src/rustdoc.md
- src/sanitizers.md
- src/tests/adding.md
- src/tests/compiletest.md
- src/tests/docker.md
- src/tests/headers.md
- src/tests/intro.md
- src/tests/running.md
- src/tests/ui.md
rust-lang/rust#106458 moves the test directory.
This updates the documentation to point to the new directory.
Is blocked on rust-lang/rust#106458 to be merged.
> Change `src/test` to `tests`

- examples/rustc-driver-example.rs
- examples/rustc-driver-getting-diagnostics.rs
- examples/rustc-driver-interacting-with-the-ast.rs
- src/rustc-driver-getting-diagnostics.md
- src/rustc-driver-interacting-with-the-ast.md
because `diagnostic_output: DiagnosticOutput`  is removed from `rustc_interface::Config` type by commit https://github.com/rust-lang/rust/commit/641f8249f99b407af7e5376b098323926eab1696, the examples are no longer compiled.
This PR is to fix it for the latest nightly rustc as today 1.68.0-nightly (935dc0721 2022-12-19)
Closes https://github.com/rust-lang/rustc-dev-guide/issues/1556
> fix examples for rustc 1.68.0-nightly (935dc0721 2022-12-19) (#1556)

- src/compiler-src.md
Since the tests move, this was not correct anymore.
> Correct tests misplacement

- src/type-checking.md
> rustc_typeck exists no more

- src/diagnostics/translation.md
> there are still no locale bundles

- .github/workflows/ci.yml
- book.toml
This tries to fix the notorious 429 failure using [GHA's ephemeral PAT](https://docs.github.com/en/actions/security-guides/automatic-token-authentication).
> Use ephemeral PAT for linkcheck

- src/type-inference.md
> New infcx usage

- src/building/suggested.md
As per https://github.com/rust-lang/rust/pull/107297#discussion_r1092764740, the change broke the rust-analyzer config. Hence, changing the docs to match the new path
> Update rustfmt path

- src/ty.md
For rust-lang/rust#107393
There are a few questions remaining that I would like some help one :)
> Add section on comparing types

- book.toml
It seems that this header causes "406 Not Acceptable" failures: https://github.com/rust-lang/rustc-dev-guide/actions/runs/4092776683/jobs/7057742900
> Do not add accept header on linkcheck

- src/building/suggested.md
https://github.com/rust-lang/rust/pull/107757 moves the recommended `settings.json` setup into `x.py setup`, so update the dev guide accordingly.
cc @jyn514
> Replace settings.json with x.py setup note

- examples/rustc-driver-example.rs
- examples/rustc-driver-getting-diagnostics.rs
- examples/rustc-driver-interacting-with-the-ast.rs
- src/rustc-driver-getting-diagnostics.md
- src/rustc-driver-interacting-with-the-ast.md
Closes https://github.com/rust-lang/rustc-dev-guide/issues/1581
Updated examples with the 1.69.0-nightly (e1eaa2d5d 2023-02-06).
> update examples for rustc 1.69.0-nightly (e1eaa2d5d 2023-02-06)

- CITATION.cff
- book.toml
Fixes #1534
This places a CFF file following https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files to add citation metadata.
Some data is taken from https://github.com/rust-lang/rustc-dev-guide/blob/master/book.toml.
The release date is taken from https://github.com/rust-lang/rustc-dev-guide/commit/27ec0dc6d6e5afb7a4848ed00b457d24ec12b8f3.
cc @rust-lang/wg-rustc-dev-guide I'm not familiar with citations at all, any feedback is greatly welcome!
> Add a citation file

- README.md
- src/building/suggested.md
The JSON provided for VSCode works with coc and nlsp-settings. This is verified by
https://github.com/fannheyward/coc-rust-analyzer#configurations for coc, and feeding the JSON in to this schema
https://github.com/tamago324/nlsp-settings.nvim/blob/main/schemas/_generated/rust_analyzer.json for validating nlsp-settings.
The Lua translation is straight-forward and is how all rust-analyzer settings must be used with native nvim lsp.
Note that I just moved and my main computer that has nvim setup on it is not unpacked so I did not test these. But I believe they should work, and I think I've actually done something like this in the past.
> Add Neovim configuration information

- src/compiler-debugging.md
There is a section with [instructions for setting up source analyzer in VSCode](https://rustc-dev-guide.rust-lang.org/building/suggested.html#configuring-rust-analyzer-for-rustc), but nothing for setting up debugging with CodeLLDB.  This adds a sample configuration that may not be ideal, but appears to work for me.
To source highlight the snippet, uses JavaScript instead of JSON so that comments do not show up as errors highlighted in red (VSCode allows comments).
*(I'm not using Windows... I saw the given pattern from another launch.json and just included it.  Someone on Windows should edit that to be correct if it's not.)*
> Add sample CodeLLDB launch.json

- src/building/suggested.md
cc @RalfJung, @jyn514 
I'm not sure if 'the above file' is ambiguous here or if I should just duplicate the link.
Also, if https://github.com/rust-lang/rust/pull/107848 is accepted, it might be nice to specifically ask users to run `x.py setup hook`/`x.py setup vscode` in these two sections of this page.
> Add link to vscode settings in Rust repo

- ci/date-check/src/main.rs
They currently also point to filenames, which is redundant.
current
proposed
- thir.md
- traits/chalk.md
> have checkboxes only point to date-check lines in files

- src/closure.md
- src/compiler-debugging.md
saw https://github.com/rust-lang/rustc-dev-guide/pull/1482#discussion_r1110265830 and looked elsewhere
> make use of the `host` symlink in the build directory, to ease things

- src/backend/backend-agnostic.md
This way, there's a bit of context for the reader.
> Explain what the rest of the backend agnostic page is about

- src/backend/updating-llvm.md
See this recent text from team member...
https://rust-lang.zulipchat.com/#narrow/stream/187780-t-compiler.2Fwg-llvm/topic/Rust-specific.20LLVM.20patches/near/327170957
cc https://github.com/rust-lang/rustc-dev-guide/issues/1575
> fix and clarify llvm bugfix policy

- src/backend/updating-llvm.md
> mention Dev desktops, to help with LLVM builds

- src/building/how-to-build-and-run.md
https://github.com/rust-lang/rust/issues/101691
> bootstrap now creates a usable toolchain when building stage0 std

- src/solve/canonicalization.md
still have to explain canonicalization in-depth. Before that I want to check whether the current way this is written is even helpful.
cc @rust-lang/initiative-trait-system-refactor
> new solver: write canonicalization chapter

- src/diagnostics.md
This replaces link to a removed lint with a link to discussion of lints of its type.
> keep "grey area" lint summary green

- src/diagnostics/diagnostic-items.md
> this remains true

- src/contributing.md
We are trying to improve on the pull request review flow. This patch add additional info on how to use the review flags during the lifecycle of a pull request.
Discussed during T-compiler meeting ([comment](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bsteering.5D.202023-02-17.20review.20latency.20compiler-team.23589/near/328505647)).
thanks!
r? @JohnTitor
> Add detail to contributing guide

- src/identifiers.md
The field was made `pub` by https://github.com/rust-lang/rust/pull/98930 and #99027 removed the method.
Fixes https://github.com/rust-lang/rustc-dev-guide/issues/1626
> Update explnation about `Body.basic_blocks`

- src/type-inference.md
This hasn't been changed since 2021, see https://doc.rust-lang.org/nightly/nightly-rustc/rustc_infer/infer/struct.InferCtxtInner.html.
cc #1627
> Update date reference about infer context variables

- src/the-parser.md
This removes the mention of lexer/parser refactoring.
AFAIK, there is no MCP, project, initiative, or anything else, and the work is done on a best-efforts basis.
That is, such refactoring happens on other parts of the compiler, and we can say it's just normal work, so I don't think it makes much sense to do the date check (actually, no one has asked "why hasn't it been updated" before).
cc #1627
> Remove mention to lexer/parser refactoring

- src/mir/index.md
Fixes #1589, fixes #1387
r? @spastorino @oli-obk
> Reflect the changes in rust-lang/rust#67000

- src/building/suggested.md
This file was moved in https://github.com/rust-lang/rust/pull/108618.
Also as of https://github.com/rust-lang/rust/pull/107848, `x setup vscode` runs this step specifically.
> Fix Rust Analyzer settings location

- src/building/how-to-build-and-run.md
- src/building/suggested.md
- src/compiler-debugging.md
- src/contributing.md
Corresponds to https://github.com/rust-lang/rust/pull/109031. Should not land if that one doesn't.
> Rename `config.toml.example` to `config.example.toml`

- src/backend/libs-and-metadata.md
"Crate disambiguator" is now called "Stable Crate Id" (see [this commit](https://github.com/rust-lang/rustc-dev-guide/commit/93422c21baca585dc88357ec886a48f6ddc7d665)).
A broken link using the obselete name is updated. No more occurrence of "crate disambiguator" remains.
> Fix "Crate disambiguator" in libs-and-metadata.md

- src/SUMMARY.md
- src/fuzzing.md
Fixes #1645.
cc @workingjubilee and @matthiaskrgr
> Add chapter on fuzzing

- src/contributing.md
This updates the overview of the different kinds of labels to add some missing entries, fix some incorrect ones, and to rearrange it into a table which should hopefully make it a little easier to read.
Since GitHub's markdown preview does not allow style tags, this is a screenshot of what it looks like rendered with mdbook:
> Update labels overview

- README.md
- book.toml
- ci/linkcheck.sh
Mdbook currently gives a hard error if it's not set in the environment:
```
[2023-03-25T22:52:13Z ERROR mdbook_linkcheck::config] Unable to interpolate "authorization: Bearer $GITHUB_TOKEN" because Failed to retrieve `GITHUB_TOKEN` env var: environment variable not found
```
Dynamically add it in `linkcheck.sh` to avoid requiring it when we don't need it.
> Don't require $GITHUB_TOKEN to build locally

- examples/rustc-driver-interacting-with-the-ast.rs
After adding this field it works in: `rustc 1.70.0-nightly (a266f1199 2023-03-22)`
> Add locale_resources

- src/compiler-debugging.md
- src/fuzzing.md
- src/notification-groups/cleanup-crew.md
This updates some links for cargo-bisect-rustc which has a new documentation guide.
> Update some links and information for cargo-bisect-rustc

- src/conventions.md
As part of https://github.com/rust-lang/rust/issues/99414 I'm implementing support for REUSE in the rust-lang/rust repository (of which this repository is a submodule) to automatically gather licensing information.
Unfortunately REUSE is occasionally too eager to find copyright statements, and in this case it's marking `src/conventions.md` as being copyrighted by `notice`. This PR adds ignore comments to prevent that from happening.
> Make REUSE ignore section heading as a copyright statement

- src/building/how-to-build-and-run.md
> mention `git clone --depth 1`

- .github/workflows/ci.yml
- README.md
- ci/check_line_lengths.sh
- ci/lengthcheck.sh
- src/contributing.md
- Add compatibility for bash 3, which is the default on MacOS
- Make error messages less verbose and clickable in VSCode
- Rename check_line_lengths.sh to lengthcheck.sh
The rename allows using tab completion to run the script. Before, `ci/check`
would stop because of the ambiguity between `check-in.sh` and
`check_line_lengths.sh`.
- Fix the powershell example in the readme to work without changes.
> Various improvements to `check_line_lengths.sh`

- src/building/compiler-documenting.md
- src/contributing.md
Libstd links directly to this section (https://doc.rust-lang.org/std/index.html#contributing-changes-to-the-documentation). Make it more useful.
> Improve the landing page for contributing to the libstd docs

- src/external-repos.md
Fixes https://github.com/rust-lang/rustc-dev-guide/pull/1653#discussion_r1159212965 and https://github.com/rust-lang/rustc-dev-guide/pull/1653#discussion_r1159213120.
r? @RalfJung
> Link to forge instead of duplicating toolstate info

- src/SUMMARY.md
- src/about-this-guide.md
- src/contributing.md
- src/getting-started.md
"What should I work on?" is the first question I get from nearly all contributors. So far
I've been giving links to individual issues, but they quickly go out of
date or get fixed, and then I have more work to do to help people find
an issue. Add some suggestions for work people can find themselves,
without having to first consult an expert.
- Move "Getting Started" to be the first page of the guide
- Fix up some links
- Make the "Asking Questions" section more useful
- Move the "Cloning and Building" stub to the bottom of the
page
> Reorganize "Getting Started" and add a "What should I work on?" section

- src/SUMMARY.md
- src/building/suggested.md
- src/tests/suggest-tests.md
Part of rust-lang/rust#109933.
Blocked on rust-lang/rust#106249? (the links are broken until it's merged)
I think it's a pretty good overview, both high and low level.
r? @albertlarsan68
> docs: document new `suggest-tests` tool

- src/building/how-to-build-and-run.md
Four links were broken, either pointing to the wrong url or the wrong extension (or both). This fixes the links.
> Fix links in how-to-build-and-run.md

- src/tests/headers.md
- src/tests/ui.md
https://github.com/rust-lang/rust/pull/110444
> Add docs for compare-output-lines-by-subset flag

- src/solve/trait-solving.md
cc https://github.com/rust-lang/rust/pull/110180
this is a bit worrying as I can imagine us getting ICE when checking user type annotations. https://rust-lang.zulipchat.com/#narrow/stream/364551-t-types.2Ftrait-system-refactor/topic/mir.20typeck.20and.20relying.20on.20region.20equality
> extend the sixth trait system requirement

- src/hir-debugging.md
https://github.com/rust-lang/rust/pull/83491
`--pretty` has been removed.
> Use unpretty for debugging Hir

- src/mir/optimizations.md
For this PR, which changes the name in the code: https://github.com/rust-lang/rust/pull/111309
> Rename InstCombine to InstSimplify

- src/building/suggested.md
Add a note about the new shell completion scripts that will land in https://github.com/rust-lang/rust/pull/111388. cc @jyn514
> Add note about shell completion scripts

- src/name-resolution.md
Some very minor typos I noticed as I was perusing the chapter on name resolution
> name-resolution: Fix some typos in "Scopes and ribs"

- src/compiler-team.md
- src/notification-groups/about.md
- src/rustbot.md
The triagebot documentation has moved to the forge as part of https://github.com/rust-lang/rust-forge/pull/687. This updates the links to the new locations.
> Update triagebot links.

- src/thir.md
Fixes typo in the word `surrounding` in a THIR example codeblock.
> Fix "surronding" typo in thir.md

- src/building/how-to-build-and-run.md
Currently, [the how to build and run guide](https://rustc-dev-guide.rust-lang.org/building/how-to-build-and-run.html) of the rustc dev guide doesn't mention anything about the default options you are given when running `./x.py setup`:
```
Welcome to the Rust project! What do you want to do with x.py?
a) library: Contribute to the standard library
b) compiler: Contribute to the compiler itself
c) codegen: Contribute to the compiler, and also modify LLVM or codegen
d) tools: Contribute to tools which depend on the compiler, but do not modify it directly (e.g. rustdoc, clippy, miri)
e) dist: Install Rust from source
f) none: Do not modify `config.toml`
Please choose one (a/b/c/d/e/f):
```
This could lead to frustration for new users (like myself) who do not fully understand how the defaults …
> Include information about setup defaults in how-to-build guide

- src/backend/implicit-caller-location.md
This PR updates the (probably) outdated https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-track_caller-attribute to https://doc.rust-lang.org/reference/attributes/codegen.html#the-track_caller-attribute
> Update track_caller reference link

- src/diagnostics.md
This adds some explicit definitions of various terms used in the lint chapters *before* they are used. It can be confusing when the text uses terminology that is not defined (or is not defined until much later).
This uses some text taken from a comment by @Nilstrieb.
> Define more lint terms.

- src/building/how-to-build-and-run.md
This pr is the follower of https://github.com/rust-lang/rustc-dev-guide/pull/1710, which didn't finish it's job perfectly.
> Try to avoid confusion

- src/parallel-rustc.md
https://github.com/rust-lang/rust/pull/109971
> OwningRef exists no more

- src/tests/running.md
I recently had to run the test suites with a `-Z flag` and without using `RUSTFLAGS`. I looked for such a thing in the dev guide testing section but couldn't find anything.
Since `./x test` supports that with `--rustc-args`, let's document it a bit here.
> document `./x test --rustc-args` option

- src/contributing.md
More easy to review per-commit.
Also, ticks some boxes in #1714.
> various fixes/improvements to Contributing chapter

- src/llvm-coverage-instrumentation.md
**PR Summary**:
The PR contains a fix to broken link pointing to Function Coverage page.
> fix: update link to function coverage

- src/SUMMARY.md
- src/solve/normalization.md
now that https://github.com/rust-lang/rust/pull/113086 was merged.
cc @rust-lang/initiative-trait-system-refactor
> add section for normalization with the new solver

- src/git.md
> linked issue is closed

- src/building/how-to-build-and-run.md
This paragraph says that given README section have instructions on how to install Python and other prerequisites but it doesn't.
Other than that "Dependencies" section in the README is already given in this section of the rustc-dev-guide: https://rustc-dev-guide.rust-lang.org/building/prerequisites.html#dependencies So this paragraph seems not necessary.
> fix(how-to-build-and-run): remove a wrong paragraph

- src/building/how-to-build-and-run.md
I think it is a typo, isn't it? 🤔
> fix(how-to-build-and-run): fix a typo ("fromer" -> "former")

- src/building/suggested.md
This statement is not about Visual Studio Code; it is about Neovim and it is already in that section. And it is also confusing for a VS Code user. So I think it is better to remove it.
> fix(suggested): remove an unnecessary and confusing statement

- src/generic_arguments.md
See https://github.com/rust-lang/rust/pull/113591
> generic_arguments.md: substs -> GenericArgs

- src/git.md
It might cause a confusion since it is not end of a sentence.
> fix(git.md): remove a confusing end of sentence character

- src/walkthrough.md
There was an ambiguity on whether the `it` after `don't` is a subject or object.
> fix(walkthrough.md) add a comma operator to eliminate ambiguity

- src/git.md
Some of them wasn't clickable.
> refactor(git.md): make git-scm links clickable

- src/notification-groups/about.md
Pronunciation of the next word requires it.
> fix(about.md): use `a` instead of `an`

- src/serialization.md
This is better not to have an interruption while reading it fast.
> fix(serialization.md): add a necessary plural suffix

- src/serialization.md
I think it should be like this since after this word, it is specified that this _generates an implementation_ which seems like a macro's job.
> fix(serialization.md): fix the name of a derive macro

- src/mir/visitor.md
From the context, it is understood that this type is `MyVisitor`, not `NoLandingPads`.
> fix(visitor.md): fix a type name in a code sample

- src/diagnostics/diagnostic-structs.md
Context: https://github.com/rust-lang/rustc-dev-guide/issues/1704
> Update from `#[warn_]` to `#[warning]` diagnostic attributes

- src/debugging-support-in-rustc.md
**PR Summary**:
The PR fixes the docs regarding `debugger_visualizer` which was stabilized. Please refer to this [PR#108668](https://github.com/rust-lang/rust/pull/108668) of the `rust` repo, for more information. Also, the relevant section in the docs can be found [here](https://rustc-dev-guide.rust-lang.org/debugging-support-in-rustc.html?highlight=debugging%20support#natvis).
> fix: stabilize debugger_visualizer

- src/SUMMARY.md
- src/borrow_check/drop_check.md
This adds a slight modification of the @rust-lang/types deep dive document prepared by @lcnr in https://hackmd.io/h9YBnIbaRSCD7Ej6hUpF_w as a chapter.
Link to the meeting: https://rust-lang.zulipchat.com/#narrow/stream/326132-t-types.2Fmeetings/topic/2023-07-17.20dropck
Changed things:
- Minor wording changes usages of I think, I believe and things like that are gone.
- I've removed the content starting on the section `Fixing the [T; 0] inconsistency #110288` and everything after that was in the deep dive document because those are about discussions and not about how things work, but maybe people want to add some stuff from there?.
- Replaced the beginning of dropck_outlives section of @lcnr's document with @nikomatsakis drop-live explanation …
> Add dropck documentation

- src/ty.md
we don't have APIs like `mk_array` for types now.
> Update outdated doc for types

- src/building/suggested.md
I imagine that the book meant that a full build isn't needed since it gave as an example the addition of a debug! statement
> Update suggested.md : missing word

- src/building/suggested.md
Bootstraps nix detection isn't always perfect. For example in these two cases:
- https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Bootstrapping.20on.20NixOS
- https://github.com/rust-lang/rust/issues/115073
> Suggest enabling patch-binaries-for-nix in `shell.nix`

- src/tests/compiletest.md
Note stolen from https://github.com/rust-lang/rust/blob/fe03b46ee4688a99d7155b4f9dcd875b6903952d/src/tools/compiletest/src/lib.rs#L727.
Also moved info downwards, as it feels secondary.
Ticks a box in #1714 .
> date-check: test suites/classes using "revisions"

- src/backend/updating-llvm.md
- src/llvm-coverage-instrumentation.md
> llvm updates

- src/llvm-coverage-instrumentation.md
first to `run-make/coverage*`, then finally to `run-coverage*`
> coverage tests have moved, twice

- src/building/how-to-build-and-run.md
The current sentence was confusing when I first read it. I've reworded it to hopefully make it clearer
> Reword sentence about using `./x` over `./x.py`

- src/git.md
> add sections in 'using git' (#1675)

- src/building/how-to-build-and-run.md
As of  Aug 2023, found:
Spelling mistake "guilde" should be "guide"
This PR makes this minor correction only.
Thank you for your consideration.
> Update minor how-to-build-and-run.md spelling mistake

- src/llvm-coverage-instrumentation.md
- src/tests/compiletest.md
[(As suggested on Zulip.)](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/PSA.3A.20Blessing.20the.20coverage-map.20tests/near/390169405)
This adds compiletest documentation for the `coverage-map`, `run-coverage`, and `run-coverage-rustdoc` test suites.
My main goal here is to document these test suites for developers who are *not* working on coverage instrumentation, but might need to bless or otherwise interact with the tests as part of unrelated MIR or LLVM work.
I also lightly revised the testing section of the `llvm-coverage-instrumentation.md` page to make it less blatantly out-of-date, but I'm holding off on making larger high-effort changes to that page until my ongoing coverage work has calmed down a bit.
> Document the `coverage-map` and `run-coverage` test suites

- src/serialization.md
stolen from https://github.com/rust-lang/rustc-dev-guide/pull/1758
> fix type name

- src/building/optimized-build.md
The optimized builds pipeline was simplified in https://github.com/rust-lang/rust/pull/115795. Now it should be much easier to use locally, which is reflected in the changes of this PR.
> Modify build instructions for optimized build

- src/appendix/glossary.md
> Clarify all the `{AP,RP}IT{,IT}` impl trait types

- src/tests/headers.md
This is more consistent with the other examples in this file such as https://github.com/rust-lang/rustc-dev-guide/blob/a13b7c28ed705891c681ce5417b3d1cdb12cecd1/src/tests/headers.md?plain=1#L196
> test headers: fix `compile-flags` example

- examples/rustc-driver-example.rs
- examples/rustc-driver-getting-diagnostics.rs
- examples/rustc-driver-interacting-with-the-ast.rs
- src/rustc-driver-getting-diagnostics.md
- src/rustc-driver-interacting-with-the-ast.md
It's been a while since the rustc driver examples were updated and they no longer compile because new fields were added to `rustc_interface::config::Config`, so I thought I'd submit a PR to fix them up. Their values don't seem very important for the purposes of the specific examples so I just left them at their default value.
> update rustc_driver examples

- src/building/suggested.md
`changelog-seen` was deprecated in https://github.com/rust-lang/rust/pull/115898
```
WARNING: The use of `changelog-seen` is deprecated. Please refer to `change-id` option in `config.example.toml` instead.
WARNING: The `change-id` is missing in the `config.toml`. This means that you will not be able to track the major changes made to the bootstrap configurations.
note: to silence this warning, add `change-id = 115898` at the top of `config.toml`
```
> [suggested.md]  `changelog-seen` -> `change-id` in `shell.nix`

- src/return-position-impl-trait-in-trait.md
cc https://github.com/rust-lang/rust/pull/116072#issuecomment-1751644397 @lcnr @aliemjay
> Document subtle implied bounds issue in RPITIT inference

- src/hir-debugging.md
Previously at no point in the guide did we recommend `unpretty=hir`, only `unpretty=hir-tree`. I'm not sure if `unpretty=hir` existed when this chapter was written.
related: https://github.com/rust-lang/rustc-dev-guide/issues/1159
I noticed that there's some duplicate information between here and the parent chapter https://rustc-dev-guide.rust-lang.org/hir.html I may try to merge https://rustc-dev-guide.rust-lang.org/hir-debugging.html into its parent in another PR.
> recommend `unpretty=hir` alongside `unpretty=hir-tree`

- src/appendix/glossary.md
> Add WF to glossary

- src/feature-gates.md
- src/implementing_new_features.md
- src/stabilization_guide.md
The name for active features was changed to unstable in https://github.com/rust-lang/rust/pull/116550
> Update name of "active" features to "unstable"

- src/building/suggested.md
Since the change-id is frequently updated alongside breaking changes in the build configuration, keeping the change-id in sample configurations synced with the latest change-id becomes challenging. To address this, we are removing the change-id from the sample configurations so that users can directly view the logs and decide whether to use it or not.
ref https://github.com/rust-lang/rust/pull/115898#issuecomment-1775909050
> remove change-id from sample build configuration

- src/traits/unsize.md
Possibly satisfies https://github.com/rust-lang/rust/issues/65991#issuecomment-1757680181, though I really kinda want to know what needs to be specified here.
r? @lcnr
> Add some documentation for unsizing

- src/llvm-coverage-instrumentation.md
Coverage internals have changed quite a bit over recent months/weeks, so I decided to at least make a pass over the existing docs and update anything that is clearly outdated.
> Update some outdated descriptions of coverage instrumentation

- src/solve/invariants.md
encountered it while refactoring normalization in the new solver, currently holds, doesn't always hold in the new solver
r? @compiler-errors
> add a new type system invariant

- src/llvm-coverage-instrumentation.md
- src/tests/compiletest.md
The two big coverage test suites (`coverage-map` and `run-coverage`) have been merged into a single `coverage` suite with multiple modes (https://github.com/rust-lang/rust/pull/117484).
The `run-coverage` mode has also been renamed to `coverage-run`, with corresponding changes to the `run-coverage-rustdoc` suite (https://github.com/rust-lang/rust/pull/117700).
> Update documentation for coverage tests

- src/getting-started.md
From [Zulip Conversation](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Looking.20for.20Mentorship.20.28Diagnostics.29)
Adds greater emphasis on the fact that the expert's map is outdated.  
Also cleans up accidental double spaces and formats document.
> Emphasize that the experts map is not up to date

- src/SUMMARY.md
- src/traits/canonicalization.md
> Add back the `canonicalization` chapter.

- src/tests/running.md
As mentioned in https://github.com/rust-lang/rust/pull/117313, adding documentation about how to run cg_gcc tests would be very helpful.
cc @RalfJung
> Add explanations on how to run rustc_codegen_gcc tests

- src/compiler-team.md
- src/getting-started.md
Now that we have removed experts map https://github.com/rust-lang/compiler-team/pull/698, fix the guide accordingly.
cc @davidtwco
> Replace experts map with reviewers from triagebot

- src/SUMMARY.md
- src/diagnostics.md
- src/guides/editions.md
This adds a chapter to explain how editions work in rustc and the things to consider for different kinds of changes.
I don't know how best to place this in the chapter listing. It doesn't fit any of the "phases" of the compiler, since it covers multiple phases. I decided to start a new "General Guides" section, but I don't know if that really makes sense.
> Add a chapter on editions.

- src/feature-gates.md
- src/implementing_new_features.md
The edition field in the feature definition was removed in https://github.com/rust-lang/rust/pull/118802, so it should no longer be specified.
> Remove feature edition fields.

- src/building/bootstrapping.md
The wording
> When compiling `rustc`, the stage0 compiler uses the freshly compiled
> `std`.
can be misread as
> code from `std` compiled by stage0 `rustc` is executed to produce the
> stage1 `rustc`.
Clarify that that is not the case. (I personally misread it that way which has had me confused for a long time.)
> bootstrapping: Clarify that stage0 std code is not executed to produce stage1 compiler

- src/building/suggested.md
`./x.py test mir_opts` requires a cross-architecture toolchain. `gcc_multi` seems to have everything needed for it to run on NixOS. I hope there was no particular reason to pin `gcc9` in particular; `gcc_multi` uses the latest available `gcc`.
> Suggest `gcc_multi` to make `mir_opts` run on nixos

- src/traits/unsize.md
> Fix typo in unsize docs

- src/hir.md
I believe rust playground use `unpretty=hir` option by default, so I think it would also be nice to add a mention of this option.
> Add a description of `unpretty=hir` to the HIR docs

- src/llvm-coverage-instrumentation.md
Enabling the profiler runtime is an essential part of being able to properly work on the coverage instrumentation code.
There's already a mention of it on this page, but it's made in passing and is easy to miss. This patch adds a much more prominent section containing recommended `config.toml` settings, including `profiler = true`.
> Prominently mention `profiler = true` on the coverage page

- src/pat-exhaustive-checking.md
Exhaustiveness checking is pretty intricate and interesting, so I thought (and it was suggested to me) I'd provide a bit more detail here. These subsections are uplifted almost wholesale from the doc-comments of the relevant modules (including [this PR](https://github.com/rust-lang/rust/pull/118308)).
> Explain the important concepts of exhaustiveness checking

- src/about-this-guide.md
The current link provides a link to two versions of the book, both redirecting to the "current version", which is the link this PR uses.
> Correct the link to rust reference

- src/contributing.md
At some point we added the label <kbd>has-merge-commits</kbd> which gets automatically added if a PR has merge commits. In rust-lang/rust#119938, @Nilstrieb has made it possible for unauthorized users to remove it via `@rustbot` which makes perfect sense since it doesn't get removed automatically.
I've added a paragraph for this since we didn't mention this label at all.
This one codifies another case of “tribal knowledge”: Basically, one shouldn't use `Fixes #NNN` in <kbd>{stable,beta}-accepted</kbd> PRs that fix stable-to-{stable,beta} regressions. I don't think I need to further justify this but just in case I do, cc this age-old comment https://github.com/rust-lang/rust/issues/52873#issuecomment-437011639 and this recent PR rust-lang/rust#119477.
> Expand upon PR guidelines

- src/building/new-target.md
- src/sanitizers.md
- src/tests/running.md
- src/tests/suggest-tests.md
> update old bootstrap docs

- src/compiler-debugging.md
- src/mir/debugging.md
- src/tests/compiletest.md
This flag was removed by <https://github.com/rust-lang/rust/pull/119566>.
> Remove outdated references to `-Z dump-mir-spanview`

- src/SUMMARY.md
- src/thir.md
- src/unsafety-checking.md
Documentation for rust-lang/rust#117673
> Document unsafety checking

- src/tests/perf.md
Suggested [here](https://github.com/rust-lang/rust/pull/120093#issuecomment-1899238160).
> Add a perf. bot command and a link to its help page

- examples/rustc-driver-getting-diagnostics.rs
Closes #1834
The example code writes dignostics to `stderr` implicitly with `TyCtxt::analysis()` and the last line in `fn main()` does nothing.
This PR uses custom `Emitter` to gather diagnostic directly.
> Get diagnostics directly in `rustc-driver-getting-diagnostics` example

- src/incrcomp-debugging.md
I found the explanation very confusing. I tried to take the same test and give more details, so that the next reader could understand this part of the test even if they are not that used to macros.
I also added a link to the example file mentioned
Closes https://github.com/rust-lang/rustc-dev-guide/issues/1861
> Clarify debugging graph dependency

- src/incrcomp-debugging.md
First, I'm sorry, I realize a sentence was not correctly ended in #1862.
Then, after re-reading UI documentation, I hope to slightly improve the documentation once again (at least, assuming that this time I totally understood how it works).
> Followup to #1862

- src/building/prerequisites.md
The rust repo's README was split up, so the link in the dev guide isn't pointing to the right place anymore which can make it unnecessarily difficult to find the list of denendencies, e.g. `CONTRIBUTING` doesn't list them.
> update link to rustc dependencies

- src/panic-implementation.md
Most files names are relatively explicit and probably don't need to be explicited.  However `rt.rs` is really not clear, and I believe it clarifies the text to indicate this is runtime service implementation.
> Clarify what rt.rs is.

- src/salsa.md
First, this add link to chalk and rust-analyzer. 
Secondly, it gives a very short statement explaining what it is.
I assume I won't be the only reader who don't know exactly what rust-analyzer is (it analyze rust, but that's vague), and no idea what chalk is. Those few words ensure we don't need to click the link to get a slight idea. This show what kind of usage Salsa is for
> Add link in salsa

- .github/workflows/ci.yml
- .github/workflows/date-check.yml
Account for https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> Upgrade actions to use Node.js v20

- src/the-parser.md
The way the example is written, it may seems like the output is just a list of meaningful character. I suspect it may be helpful to readers not used to lexers to show that a token may be multiple characters long.
> Replace letters by foo, bar and buz in lexing example

- src/macro-expansion.md
The first example is rewritten to follow the style of other examples:
* Using `id(foo)` instead of `expn_id_foo`.
* Using a single-line with arrow instead of a multi-line indented hierarchy.
If there is a diffrence and this rewritting is wrong, it would be interesting to explain it.
Also, this commit replace "first hierarchy" and "third hierarchy" by their name, ensuring it's more clear what is referred here. In particular, for the first hierarchy, it can be searched easier in the page if needed.
> Improving macro expansion section

- src/memory.md
- src/overview.md
I suspect that people who don't already know about arenas may be interested in the wikipedia page. It may not be the best material on this topic, but I could not find anything that is specific to the arena used by rustc, and this is still a good first approach.
I also copied the link about interning from overview to memory, as the reader may have forgotten that interning was already discussed previously.  Admittedly, the wikipedia page is called string interning, but it mentions "Objects other than strings can be interned.", and still explains the idea in a useful manner.
I suspect it may also be useful to link to
https://en.wikipedia.org/wiki/Hash_consing , as it seems the standard way to ensure that each tree (in this case, the AST of a type) is unique in memory. Except that I don't …
> Add links for arena and interning.

- src/panic-implementation.md
`BoxMeUp::box_me_up` was renamed to `take_box` in https://github.com/rust-lang/rust/pull/66766, and `BoxMeUp` was renamed to `PanicPayload` in https://github.com/rust-lang/rust/pull/116008. Updates the panic implementation docs to reflect that.
> Update uses of renamed BoxMeUp to PanicPayload

- src/borrow_check/drop_check.md
- src/building/bootstrapping.md
- src/llvm-coverage-instrumentation.md
An upcoming version of mdbook will have some minor changes in how it interprets markdown to better conform with the standards. The changes are:
* Fixed the missing footnote definition for `[^core]`.
* Headings now allow arbitrary attributes inside curly braces at the end to set HTML attributes. There was one heading where this caused it to be misinterpreted as an attribute. Fixed by using backslashes to avoid the attribute parsing.
* The `llvm-and-covmap-versions` footnote wasn't following GitHub-flavor footnote syntax. I adjusted it so it works in both the old and new versions.
> Update for upcoming markdown changes.

- src/compiler-debugging.md
- src/diagnostics/error-guaranteed.md
- src/ty.md
since this method has been renamed in rustc.
Also remove a link to  documentation in error-guaranteed.md because it was unused
> Rename occurrences of 'delay_span_bug' to 'span_delayed_bug'

- src/git.md
Discussed [here](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/rebase.20mishaps).
> Make git rebase commands more bulletproof

- src/tests/headers.md
- src/tests/ui.md
corresponding rustc PR: https://github.com/rust-lang/rust/pull/120881
> Update docs about ui tests now using `//@` headers

- src/tests/ui.md
The `//@` directives are currently only applicable for "ui" test suite, not ui test mode (because ui test mode includes "ui-fulldeps" test suite which do not yet use `//@` directives).
Additionally, `// ignore-tidy` and `// ignore-tidy-*` directives are handled by tidy, and are ignored by compiletest specifically in "ui" test suite.
> Specify ui test suite directives and add note on ignore-tidy directives

- src/building/suggested.md
It will cost about 4x time to run `x check` compared with `x check compiler`.
> Add notes on tweak rust-analyzer.check.overrideCommand

- src/tests/compiletest.md
- src/tests/headers.md
Waiting on https://github.com/rust-lang/rust/pull/121370 to be merged.
> Update compiletest directives to be in `ui_test` style `//@`

- src/SUMMARY.md
- src/traits/implied-bounds.md
> add implied bounds doc

- src/SUMMARY.md
- src/solve/opaque-types.md
moving an existing hackmd into the dev-guide
cc @rust-lang/initiative-trait-system-refactor @rust-lang/initiative-impl-trait
> opaque types in new solver

- src/building/suggested.md
This makes it less opinionated.
cc @Nadrieril @fee1-dead i know you're using nixos
> make shell.nix better

- src/implementing_new_features.md
Added some details on adding syntax feature gates. 
Also I am still having the issue from the last time I contributed here https://github.com/rust-lang/rustc-dev-guide/issues/1545#issuecomment-1424873804. On an entirely different computer as well. So I have no idea how this looks rendered.
> Add some more details on feature gating

- src/tests/compiletest.md
- src/tests/headers.md
https://github.com/rust-lang/rust/pull/113026 added infrastructure support for `run-make` tests to now use Rust recipes (small programs) instead of Makefiles. We plan to migrate all the existing Makefile tests over to Rust recipes, as described in https://github.com/rust-lang/rust/issues/40713. This PR updates the descriptions for `run-make` tests for creating Rust 
`run-make` recipes and to discourage new Makefile-based `run-make` tests.
> Update run-make test description

- src/ty.md
Sentences such as «without the argument u32» were ambiguous, as there were two distincts u32. Having a single one, the one in the monomorphization of the type, remove the ambiguity.
> Use different type in an example

- src/tests/compiletest.md
- src/tests/headers.md
This patch also adds docs for `//@ llvm-cov-flags:`, and notes that coverage tests support revisions (though none of the current tests actually do so).
> Add compiletest docs for FileCheck prefixes and `//@ filecheck-flags:`

- src/SUMMARY.md
- src/solve/caching.md
cc @rust-lang/initiative-trait-system-refactor @rust-lang/types
> next-solver: document caching

- src/solve/caching.md
> fix broken links

- src/building/how-to-build-and-run.md
The 'read this chapter' link under the 'What is x.py?' section returned a Document not found (404) error.
> Fix broken link in chapter '1. How to build and run the compiler'

- src/solve/canonicalization.md
- src/solve/normalization.md
- src/solve/significant-changes.md
while writing this doc I realized some further improvements to normalization.
Also, this existing system is far more involved than I expected as large parts of it are intuition based for me. Will try to play a bit with our approach in the near future and then improve this guide further.
cc @rust-lang/initiative-trait-system-refactor
> document difference between solvers + new solver normalization

- src/SUMMARY.md
- src/ast-lowering.md
- src/diagnostics.md
- src/overview.md
- src/return-position-impl-trait-in-trait.md
- src/turbofishing-and-early-late-bound.md
- src/ty.md
See rust-lang/compiler-team#723.
~~Blocked on rust-lang/rust#120926~~ (merged).
> [MCP 723] Rename AstConv to HIR ty lowering

- src/SUMMARY.md
- src/borrow_check/opaque-types-region-inference-restrictions.md
See https://github.com/rust-lang/rust/pull/116891#issuecomment-1836900102.
diff:
-removed status sections.
-added "Semantic lifetime equality" paragraph.
-various minor typos and rephrasing
r? @compiler-errors @oli-obk
> add opaque-types-region-inference-restrictions

- src/SUMMARY.md
- src/building/how-to-build-and-run.md
- src/building/quickstart.md
The chapter is quite long, and a lot of the information is, while valuable, not very important for newcomers. I think it makes sense to have a condensed version for anyone just wanting to get started with only the most important information.
> Add quickstart for how to build and run the compiler

- src/backend/debugging.md
This was renamed by https://github.com/rust-lang/rust/pull/116791.
> Replace -Zno-parallel-llvm with -Zno-parallel-backend

- src/tests/headers.md
This adds the `needs-threads` header command added in https://github.com/rust-lang/rust/pull/122109.
cc @alexcrichton FYI
> Add needs-threads header command

- src/tests/compiletest.md
To accompany https://github.com/rust-lang/rust/pull/122634.
> Add basic docs for the new `aux-bin` header

- src/tests/compiletest.md
I completely forgot that this was supported myself (`Makefile`s also support these directives, but they take the form of `# <directive>` instead).
> Explicitly mention compiletest directives are supported in rmake.rs

- src/tests/headers.md
The description was irking me because it casually drops "a special env var" and "one CI job" but refuses to elaborate.
> compiletest: specify which special env var and which particular CI job

- src/tests/compiletest.md
I had to dig around a bit to figure this out, so update the docs to make it more clear.
> Add a note about checks with multiple revisions

- src/compiler-debugging.md
- src/tests/compiletest.md
The `-Z verbose` option has been renamed to `-Z verbose-internals` in commit  b5d83619 [1] (PR #119129 [2]). This commit updates the remaining `-Z verbose` to `-Z verbose-internals`.
[1]: https://github.com/rust-lang/rust/commit/b5d8361909e9e30a11227aa773099c293a5dca55
[2]: https://github.com/rust-lang/rust/pull/119129
> Rename `-Z verbose` to `-Z verbose-internals`

- src/tests/ci.md
Reflects the recent CI changes on `rust-lang/rust`. I will later also update the [Forge](https://forge.rust-lang.org/infra/docs/rustc-ci.html) (actually, I would like to copy the forge CI page here and then just link to rustc-dev-guide from the Forge).
> Update CI documentation to avoid mentioning `expand-yaml-anchors`

- src/SUMMARY.md
- src/notification-groups/about.md
- src/notification-groups/apple.md
We discussed today [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/I'd.20like.20to.20contribute.20more.20.28to.20Apple-specific.20stuff.29/near/434259421) that it would be nice with some documentation on this ping group.
Additionally, I've tried to document a few of the common challenges that we face on Apple platforms.
Blocked on https://github.com/rust-lang/team/pull/1436.
> Add documentation on Apple notification group

- src/tests/headers.md
- src/tests/ui.md
This PR adds some (very conservative) documentation for a new compiletest directive regarding check-cfg; as well as documentation regarding the use of the `FALSE` cfg as convention for an always-false config.
Related to https://github.com/rust-lang/rust/pull/124345 and shouldn't be merged before that PR.
> Add documentation for check-cfg by-default in UI tests

- examples/rustc-driver-example.rs
- examples/rustc-driver-getting-diagnostics.rs
- examples/rustc-driver-interacting-with-the-ast.rs
- src/rustc-driver-getting-diagnostics.md
- src/rustc-driver-interacting-with-the-ast.md
Updates the three `rustc_interface` examples.
Tested with `rustc 1.80.0-nightly (87293c958 2024-05-08)`
> Update the rustc_interface examples for current rustc

- src/contributing.md
I added some `L-*` labels to help us categorize issues related to specific lints.
cc https://github.com/rust-lang/rust-forge/pull/744
> Link to lint `L-*` labels

- src/ast-validation.md
It adds unnecessary noise for a simple section
> Toc here is overkill

- src/getting-started.md
Discussed [here](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Label.20closed.20PRs.20that.20lacked.20autor.20bandwidth).
> Add note about how to pick up abandoned PRs

- src/hir.md
On the page https://rustc-dev-guide.rust-lang.org/hir.html and the [source file](https://github.com/rust-lang/rustc-dev-guide/blob/79bf0ba32b243ce0d6f5b058860d5322c07bbbbe/src/hir.md) there is a link to "Lowering" which tries to lead to `https://rustc-dev-guide.rust-lang.org/lowering.html` and `src/lowering.md` respectively.
By quickly poking around I assume it should be `ast-lowering.html` now but for all I know I've misattributed.
> Fix broken link to "Lowering"

- src/SUMMARY.md
- src/notification-groups/about.md
- src/notification-groups/rust-for-linux.md
Discussed [here](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Testing.20Rust.20for.20Linux.20in.20our.20CI).
> Add Rust for Linux notification group entry

- src/building/suggested.md
in `src/building/suggested.md`
> You can use `source ./src/etc/completions/x.py.<extension>`
to load completions for your shell of choice,
or `source .\src\etc\completions\x.py.ps1` for PowerShell.
to my best knowledge, `source` command is available only in POSIX Shell, and PowerShell is not a POSIX Shell.
hence there is no `source` command in powershell, and you will get an error if you actually run `source .\src\etc\completions\x.py.ps1` for PowerShell.
My suggestion: use call operator(&) to load .ps1 script file for powershell.
There are some other options (e.g. dot sourcing)
> use `&` to load completions for PowerShell

- src/memory.md
- src/ty_module/generic_arguments.md
found some dead links when I read this book
> Fix dead links

- src/tests/compiletest.md
- src/tests/headers.md
I wrote this for https://github.com/rust-lang/rust/pull/124706 but then completely forgot to actually file a PR, whoops.
> Document the `//@ unused-revision-names:` test header

- src/getting-started.md
This is a long running project that can be picked up rather easily, so it's a good fit for this section, IMO.
> Add run-make port initiative to the Recurring work section

- src/tests/compiletest.md
@Kobzol shared a good tip about using stage0 rustc to quickly check if rmake.rs tests can be compiled in https://rust-lang.zulipchat.com/#narrow/stream/421156-gsoc/topic/Project.3A.20Rewriting.20Makefile.20Tests.20Using.20Rust/near/443637248.
This PR adds that tip to the rmake.rs section.
r? @Kobzol
> run-make: add tip about quick-compile with stage0 rustc

- src/tests/headers.md
https://github.com/rust-lang/rust/pull/126256
> Add {{target}} to header substitutions

- src/tests/compiletest.md
- src/tests/headers.md
- https://github.com/rust-lang/rust/pull/126257
- https://github.com/rust-lang/rust/pull/126111
- https://github.com/rust-lang/rust/pull/126008
> Compiletest docs for recently-added features

- src/building/new-target.md
We just realized that the bootstrap target sanity check isn't documented anywhere, and it would be quite exhausting to learn this manually through a series of failing CI builds.
cc @Kobzol
> tell about `STAGE0_MISSING_TARGETS` for new targets

- src/tests/ui.md
`//@ rustfix-only-machine-applicable` actually only works in conjunction with `//@ run-rustfix`.
> Fix note about compiletest header `rustfix-only-machine-applicable`

- src/building/how-to-build-and-run.md
Implements https://github.com/rust-lang/compiler-team/issues/607. Sibling to https://github.com/rust-lang/rust/pull/110596 and https://github.com/rust-lang/stdarch/pull/1417.
This PR renames the `wasm32-wasi` target to `wasm32-wasi-preview1`, in accordance to the accepted compiler team MCP.
> Rename `wasm32-wasi` to `wasm32-wasip1`

- src/tests/running.md
Apparently it is very convoluted to run `run-make` on Windows...
> Document how to run `run-make` tests on Windows

- src/building/suggested.md
When `rustc` uses its self-contained lld, it cannot find `libstdc++.so.6`. Instead of creating a `lld-wrapper`, I think using `LD_LIBRARY_PATH` is easier to maintain.
The relevant error message is:
```
Building stage1 library artifacts (x86_64-unknown-linux-gnu)
error: process didn't exit successfully: `/path/rust/build/bootstrap/debug/rustc /path/rust/build/bootstrap/debug/rustc -vV` (exit status: 127)
--- stderr
/path/rust/build/x86_64-unknown-linux-gnu/stage1/bin/rustc: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```
r? @Nilstrieb
> provide `libstdc++.so.6` through `LD_LIBRARY_PATH`

- src/SUMMARY.md
- src/tests/integration.md
- src/tests/rust-for-linux.md
Documents our Rust for Linux integration tests, in a similar vein to https://github.com/rust-lang/rustc-dev-guide/pull/1989.
> Add Rust for Linux integration tests documentation

- src/building/new-target.md
With https://github.com/rust-lang/rust/pull/127026 we no longer want to use the `EXTRA_CHECK_CFGS` list in bootstrap. New target specific cfgs should be set directly in the appropriate `[lints.rust.unexpected_cfgs.check-cfg]` lint table in one of the `library/{std,alloc,core}/Cargo.toml`.
> Update new target check-cfg instructions

- src/building/how-to-build-and-run.md
- src/rustdoc.md
Let's stick with the single name "bootstrap" to refer to the bootstrap project to avoid confusion.
cc https://github.com/rust-lang/rust/pull/127434
> use "bootstrap" instead of "rustbuild"

- src/bug-fix-procedure.md
It's a bit of a tongue-twister it seems.
> Fix typo: lists -> lints

- src/SUMMARY.md
- src/mir/passes.md
This PR improve the documentation of MIR queries and passes.
Below is the summary of changes:
- delete `mir_validated`
- add `mir_promoted` and `mir_drops_elaborated_and_const_checked`
- replace the `NoLandingPads` pass example with `CleanupNonCodegenStatements`
- extend the stealing mechanism and give the dependency of MIR queries as an overview
- add `mdbook-mermaid` in the build instructions
FIXME:
- Does `ty::queries::foo::force(...)` still appear in rustc?
Since rust-lang/rust#99102 may significantly change the MIR queries (and thus its doc), we can wait for its result or send follow-up PRs. This is mostly documenting the code in `rustc_mir_transform`, so maybe cc @rust-lang/wg-mir-opt.
> Improve documentation of MIR queries & passes

- src/backend/updating-llvm.md
- src/mir/optimizations.md
- src/mir/passes.md
- src/mir/visitor.md
- src/profile-guided-optimization.md
Changes applied:
- updating-llvm.md: make consistent style in a listing
- CleanupNonCodegenStatements - renamed to CleanupPostBorrowck
- SimplifyCfg - fix link target (it is an enum now)
- LocalUseVisitor - remove the documentation as the type is already gone
- PGO in LLVM - embed link
> MIR docs: fix borked links and update style

- src/tests/ci.md
Found [here](https://github.com/rust-lang/rustc-dev-guide/pull/1972#discussion_r1689584985).
CC @marxin
> Fix invalid link to toolstate documentation

- src/llvm-coverage-instrumentation.md
In some of these cases there is no simple fix, because the text has been invalidated by major structural changes to the code, so instead I've rewritten or deleted those sections.
Fixes #2026.
> Fix broken links in `llvm-coverage-instrumentation.md`

- ci/linkcheck.sh
If I run the `mkbook build` on top of #2017, I get the following before this PR:
```
❯ RUST_LOG=info mdbook build
2024-07-23 16:33:33 [INFO] (mdbook::book): Book building has started
2024-07-23 16:33:33 [INFO] (mdbook::book): Running the html backend
2024-07-23 16:33:33 [INFO] (mdbook::book): Running the linkcheck backend
2024-07-23 16:33:33 [INFO] (mdbook::renderer): Invoking the "linkcheck" renderer
Checking files changed in master...: src/backend/updating-llvm.md src/mir/optimizations.md src/mir/passes.md src/mir/visitor.md src/profile-guided-optimization.md 
exec mdbook-linkcheck -f src/backend/updating-llvm.md src/mir/optimizations.md src/mir/passes.md src/mir/visitor.md src/profile-guided-optimization.md 
[2024-07-23T14:33:34Z INFO  mdbook_linkcheck] Started the link checker …
```
> linkcheck: fix filtering of the source files

- ci/linkcheck.sh
- src/SUMMARY.md
- src/mir/dataflow.md
While reading the guide, I noticed that the code example didn't compile. This change, simply corrects the code and adds syntax highlighting by marking the code block as rust code.
> Correct rust code block in *Dataflow Analysis*

- src/tests/running.md
Fixes #2038
But unfortunately, it's impossible. You should invoke following instead:
But unfortunately, it's impossible. You should invoke **the** following instead:
> Added 'the' in chapter "Running test" subtitle "Run unit tests on the compiler/library"

- src/backend/updating-llvm.md
The primary change here is to split the backport process into two. While upstream backports are accepted, they should be filed there first. Switch to direct backports after the upstream release is closed.
cc @rust-lang/wg-llvm
> Update LLVM docs

- src/mir/index.md
line 320:
original: "valtree back a to MIR constant"
updated: "valtree back to a MIR constant"
> Update index.html, 39. The MIR: fix typo

- src/borrow_check/opaque-types-region-inference-restrictions.md
- src/opaque-types-impl-trait-inference.md
- src/overview.md
- src/param_env/param_env_construction_internals.md
- src/solve/opaque-types.md
Use relative links to the corresponding md source files; this helps local browsing of generated docs.
> Replace direct http links to rustc-dev-guide.rust-lang.org

- src/compiler-debugging.md
- src/tests/ui.md
First of all, I'm not entirely sure if it's worth documenting this at all.
I guess it could be useful for newcomers who haven't heard of them yet.
Well, I guess the non-exhaustive table I added can be of use for seasoned rustc devs, too.
In fact, I added the table for selfish reasons as I often found myself grepping through `compiler/` and `tests/ui/` in search of specific attributes whose names I keep forgetting (their naming scheme is slightly inconsistent).
These TEST attributes serve a dual purpose. Namely as a means to "printf+"-debug the compiler as well as in UI tests to perform "white-box testing" (sorta). Hence *two* sections on this topic. I chose *compiler debugging* as the "main" article here (with the testing one referring back to the other one) but I'm open to switch it …
> Explain the internal `#[rustc_*]` TEST attributes used for debugging and inside tests

- src/tests/intro.md
Trivial fix to change `x.py` into `x`
> Fix x.py reference

- src/stability.md
This came up in https://github.com/rust-lang/rust/pull/129377.
@oli-obk I wonder if it would make sense to say that if a function is `#[unstable]` but a `const fn`, that implicitly makes it `#[rustc_const_unstable]` under the same feature gate?
> clarify the role of rustc_const_unstable

- src/queries/incremental-compilation-in-detail.md
- src/queries/incremental-compilation.md
- src/queries/query-evaluation-model-in-detail.md
Over the last week, I attempted to thoroughly understand rust's query system by implementing a toy one myself. That's not very relevant, but what is, is that I ended up reading the documentation of the query system a bunch of times. I was confused by a few things, and thought I'd clear them up for the next reader. Let me know if there's anything that should be changed.
> improve query system documentation

- src/coherence.md
@lcnr we overlooked a typo in the dev guide page we merged last Friday
> fix typo maker -> marker (thanks @lholten)

- src/walkthrough.md
While reading the [walkthrough](https://rustc-dev-guide.rust-lang.org/walkthrough.html) documentation, I noticed that the `to` word is missing. So I added it.
> fixed the typo

- src/memory.md
- src/mir/drop-elaboration.md
Make an implied internal link explicit, and fix the link for `elaborate_drop` transform.
> Fix a link and create an implied internal link 

- src/ast-validation.md
- src/mir/passes.md
This PR does two minor fixes:
1. Removes the line "c-variadic functions are declared with at least one named argument" as this is no longer true since https://github.com/rust-lang/rust/pull/124048 got merged.
2. Fixes typo: "lingint" -> "linting".
> Fix Typo and Remove Outdated Line About C Variadics

- src/tests/running.md
This brings the mention of `--rustc-args` in the "Running tests" chapter up to date with https://github.com/rust-lang/rust/pull/128841
> Reflect `x.py test`'s `--rustc-args` option being renamed to `--compiletest-rustc-args`

- src/solve/proof-trees.md
closes #2050
cc @rust-lang/initiative-trait-system-refactor
> update proof tree chapter

- src/mir/construction.md
It's really enum's with variants without fields but wrote the text a little bit similar to what it's said in the following section.
> Fix conditions lowering text for enums with no fields

- src/getting-started.md
The WG is retired and chalk is being replaced by the new solver.
> Remove chalk is owned by WG-traits

- src/building/how-to-build-and-run.md
This is just a few small edits to a sentence in the "What is x.py?" section where I felt changing some punctuation and verb tenses would help with clarity of meaning and ease of reading.
> Edit a sentence for clarity

- src/contributing.md
Prior discussion: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Expert.20map.20and.20suitable.20reviewer.20maps.3F/near/456305821.
Some context (partial summary of the prior discussion): I've noticed that we have had quite a few cases of the spin-the-bottle or pass-the-hot-potato review assignment reroll game (at least for the compiler reviewers) because some PRs might be very hard to review (due to being massive/complex/cross-cutting/highly domain specific etc.).
So in this PR, we add some advice for contributors about making potentially hard-to-review PRs (those that are large, complex, cross-cutting and/or highly domain-specific) to:
- Talk with t-compiler *before* submitting a very difficult to review PR
- Work with t-compiler to break down a large …
> Add advice about submitting potentially hard-to-review PRs

- src/building/how-to-build-and-run.md
And add advice for clearing out unused build artifacts and toolchains.
As suggested by @MarcoIeni in https://github.com/rust-lang/rust-forge/pull/768.
> Add remark on required free disk space

- src/tests/compiletest.md
Not sure about running lldb debuginfo on the Unixes, but AFAIK this is true on Windows.
> Note lldb debuginfo requires `python310.dll` to be present in `PATH` on Windows

- src/stability.md
This is based on my understanding of https://github.com/rust-lang/rust/pull/96478, its current implementation, and the wording of the section on `#[rustc_const_unstable]`.
> Document `#[rustc_default_body_unstable]`

- examples/rustc-driver-getting-diagnostics.rs
- src/rustc-driver-getting-diagnostics.md
This PR is motivated by [this PR](https://github.com/rust-lang/rust/pull/130299) over in the rust repo.
The example was broken as described in the aforementioned PR, but was also broken by [this PR](https://github.com/rust-lang/rust/pull/126834). I have 'fixed' that by calling `reset_err_count`, but I have no idea whether that actually is the appropriate way to handle the abort-on-error behavior.
> Fix getting diagnostics example

- src/tests/compiletest.md
Describe procedure for adding new crashes tests and removing crashes tests when the crash is intentionally fixed.
Also mention setting `COMPILETEST_VERBOSE_CRASHES=1` env var for verbose crashes test output.
This is adapted from `tests/crashes/README.md` and kinda duplicates that.
cc @matthiaskrgr
> Document `crashes` test suite

- src/diagnostics/diagnostic-items.md
Changed to use getter in https://github.com/rust-lang/rust/pull/94733
> Fix `is_diagnostic_item()` example

- src/stability.md
To my understanding, the rustc bug mentioned in the stability attributes chapter was fixed by https://github.com/rust-lang/rust/pull/95956. To be thorough, I kept the reference in and documented the `#[rustc_allowed_through_unstable_modules]` attribute introduced in the fix, as well as the cleanup issue for it.
> Mention rustc's stable-item-through-unstable-path bug being fixed

- src/building/how-to-build-and-run.md
I found this option, `--filter='blob:none'`, while setting up my clone of rustc, and I think it's much nicer than a shallow clone with `--depth 1` :).
https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone/ describes what it does compared to a `--depth 1` clone.
In short, as I understand it, it doesn't pull blobs per default, only on demand.
"Blobs" are all file and directory contents.
So initially, only file and directory contents for the current `HEAD` commit will be downloaded, and operations like jumping back in the git history will then automatically pull required blobs on demand.
I.e., this doesn't break git operations like a shallow clone does.
Question: Building the book locally worked fine, until I switched to a new branch.
Now `mdbook-linkcheck` …
> feat: Add section about partial clones with `git clone --filter='blob:none'`

- src/mir/index.md
Mario Carneiro noticed some issues in the [reading club meeting](https://rust-lang.zulipchat.com/#narrow/stream/196385-t-compiler.2Fwg-rustc-dev-guide/topic/.5Breading.20club.5D.202024.2E05.2E02.20chapter.2039.20.28MIR.29).
cc @digama0
> Clarify a little bit in MIR chapter

- src/rustdoc.md
I don't know when exactly this was changed since I effectively took a break from hacking on rustdoc for a few months until last month. I faintly remember a smaller `bootstrap` PR that might've affected this.
Basically from what I can tell under `profile = "tools"`, you now need to explicitly build the sysroot together with `rustdoc` via `./x b library rustdoc` whereas before you could just do `./x b`. I think this was an intentional change.
A month ago when I came back to rustdoc dev I first thought my build environment was beyond broken, lol.
Through trial-and-error I figured out the aforementioned bootstrap invocation. Note that separate invocations à la `./x b library; ./x b` or `./x b library; ./x b rustdoc` don't work either, the sysroot still wouldn't be available to rustdoc (at …
> Update rustdoc build instructions

- src/rustc-driver/getting-diagnostics.md
- src/rustc-driver/interacting-with-the-ast.md
This updates the paths to the example code in sections 35.1. and 35.2.
> Fix file paths to section 35.1 & 35.2 example code 

- src/building/suggested.md
Add instructions for setting up rust-analyzer with Emacs and Helix.
Additionally, move some content applicable to all editors out of the vscode section into its own section for visibility.
> building/suggested: Add instructions for Emacs & Helix

- src/compiler-debugging.md
- src/tests/ui.md
Follow-up to #2046.
Fixes a slightly broken hyperlink (broken URL fragment) and tweaks some wordings.
> Small follow-up to my "internal `#[rustc_*]` TEST attributes" PR

- src/traits/unsize.md
Completed T-lang FCP: https://github.com/rust-lang/lang-team/issues/286#issuecomment-2338905118.
Tracking issue: https://github.com/rust-lang/rust/issues/130852
> Rename "object safe" to "dyn compatible"

- src/building/build-install-distribution-artifacts.md
`x install` documentation was quite outdated, so it needed an update. Also added instructions on how to install in custom paths.
> update `x install` documentation

- src/building/suggested.md
These link were not rendered properly due to the lost address parts. For `rust_analyzer_settings.json` it worked because its reference is located at the end of the document.
> Fixed links to rust-analyzer configs for Emacs and Helix

- src/tests/compiletest.md
- src/tests/directives.md
Update some directive docs to be more up-to-date and mention in which test suites they are supported.
> [Testing 2/2] Revise revisions docs

- src/building/quickstart.md
- src/building/suggested.md
Update the guide as suggested. I reformatted the quickstart file and made a couple of smaller fixes too.
r? @Kobzol
> building: Update instructions for ./x setup editor

- src/SUMMARY.md
- src/profiling/with_perf.md
- src/profiling/with_rustc_perf.md
- src/tests/perf.md
This PR cleans up the section about profiling the compiler. It does the following things:
- Creates a new section that describes how to use `rustc-perf` for profiling.
- Documents the new `bootstrap` integration with `rustc-perf`, introduced in https://github.com/rust-lang/rust/pull/126318, https://github.com/rust-lang/rust/pull/127002 and https://github.com/rust-lang/rust/pull/128868.
- Removes example of `rustc-perf` usage from the `perf` section, since there is now a dedicated `rustc-perf` section. The new section mostly links to existing `rustc-perf` integration, I don't think that duplicating the docs is ideal (case in point: the existing `rustc-perf` example was using CLI options that are no longer used by `rustc-perf`).
> Document `bootstrap` integration with `rustc-perf`

- src/tests/best-practices.md
But accept test names that include non-prefix issue number.
> Revise test naming advice to discourage using issue numbers alone

- src/rustdoc-internals/search.md
https://github.com/rust-lang/rust/pull/119912
> rustdoc: docs for search deduplication

- src/tests/compiletest.md
Should be merged after https://github.com/rust-lang/rust/pull/131351 is merged.
> Purge `run-pass-valgrind` mentions

- src/tests/compiletest.md
- src/tests/directives.md
Follow-up to https://github.com/rust-lang/rust/pull/131400, which renamed these directives.
> Document compiletest directives `ignore-coverage-map` and `ignore-coverage-run`

- src/llvm-coverage-instrumentation.md
- src/tests/compiletest.md
- src/tests/directives.md
Dev-guide update to reflect https://github.com/rust-lang/rust/pull/131429.
> Rename `needs-profiler-support` to `needs-profiler-runtime`

- src/conventions.md
Auto-formatting for C++ code was added in https://github.com/rust-lang/rust/pull/123918.
> Advice on auto-formatting C++ code

- src/stability.md
This updates the docs for https://github.com/rust-lang/rust/pull/131349. Should only land once that PR landed.
> update const stability docs

- src/diagnostics/translation.md
See https://github.com/rust-lang/rust/issues/132181
> Update current status of diagnostics translation infra

- src/building/suggested.md
There is some existing advice about this in the dev guide, but it is terse and incomplete.
https://rust-lang.zulipchat.com/#narrow/channel/122651-general/topic/Setup.20multiple.20editors.20for.20work.20on.20standard.20lib.3F/near/479397923
> Describe why and how to use a separate build directory for rust-analyzer

- src/appendix/code-index.md
- src/compiler-src.md
- src/memory.md
- src/overview.md
- src/solve/invariants.md
- src/stabilization_guide.md
- src/syntax-intro.md
- src/tests/compiletest.md
This PR fixes broken internal links and proposes URLs/internal links where applicable to incomplete links  identified by linkcheck.
> Fix internal and incomplete links

- src/tests/rust-for-linux.md
cc https://github.com/Rust-for-Linux/linux/issues/1080#issuecomment-2449919389 @wesleywiser
> update rfl ci job policy

- src/SUMMARY.md
- src/coroutine-closures.md
I'm interested in stabilizing async closures *somewhat* soon, but before I can even think about writing a stabilization report or anything, I'd like to document all of the major parts of async closures and the parts of their implementation that have any significance.
I don't expect anyone to read this in its entirety, but feedback is obviously welcome.
> Async closures chapter

- src/contributing.md
> Describe how to revert a PR

- src/tests/directives.md
This adds a link for the `reference` compiletest header added in https://github.com/rust-lang/rust/pull/131382
This is a draft pending the reference side of things getting merged https://github.com/rust-lang/reference/pull/1646.
> Add a link for the `reference` compiletest header

- src/diagnostics.md
Hey there! In Rust, it seems that most user-facing types of content prefer unambiguous grammar. However, there currently isn't any instruction to use the Oxford comma when writing lists of items within diagnostics. 
I added that to avoid any ambiguity, such as that which I fixed in https://github.com/rust-lang/rust/pull/131038
Please let me know if any changes are necessary! :)
> Ask folks to use the Oxford comma in diagnostics

- src/tests/directives.md
Accompanying PR for https://github.com/rust-lang/rust/pull/131913.
> Rename `{ignore,only}-debug` -> `{ignore,needs}-{rustc,std}-debug-assertions`

- src/building/suggested.md
The [Suggested Workflows section on using a separate rust-analyzer build directory](https://rustc-dev-guide.rust-lang.org/building/suggested.html#using-a-separate-build-directory-for-rust-analyzer) has a bullet point saying to modify the [`rust-analyzer.procMacro.server` setting](https://github.com/rust-lang/rust/blob/d4822c2d84c242cc7403118b50c571464f38ef8f/src/etc/rust_analyzer_settings.json#L23), but does not mention the [`rust-analyzer.rustfmt.overrideCommand` setting](https://github.com/rust-lang/rust/blob/d4822c2d84c242cc7403118b50c571464f38ef8f/src/etc/rust_analyzer_settings.json#L19-L22). This PR adds that missing bullet point.
> Note Rustfmt for separate rust-analyzer directory

- src/tests/directives.md
For https://github.com/rust-lang/rust/pull/132310
> Document `max-llvm-major-version` directive

- src/SUMMARY.md
- src/tests/intro.md
- src/tests/misc.md
For https://github.com/rust-lang/rust/pull/132993
> Mention `RUSTC_BOOTSTRAP` for misc testing

- src/diagnostics.md
Since `Diag` struct  is the core struct in the Suggestions section, it would be better to make it a clickable link.
https://rustc-dev-guide.rust-lang.org/diagnostics.html#suggestions
> Make `Diag` a clickable link in Suggestion section

- src/mir/optimizations.md
Sibling PR for https://github.com/rust-lang/rust/pull/115293.
> Remove -Zfuel.

- src/tests/compiletest.md
For https://github.com/rust-lang/rust/pull/133470.
> Remove `pretty-expanded` as it no longer exists

- src/tests/compiletest.md
- src/tests/directives.md
For https://github.com/rust-lang/rust/pull/133540.
cc @ehuss
> Update `//@ proc-macro` aux build directive docs

- src/git.md
For when you are really hopeless.
> Spell out `git submodule deinit -f --all`

- src/tests/directives.md
For https://github.com/rust-lang/rust/pull/133736
> Document `needs-target-has-atomic` directive

- src/appendix/glossary.md
See https://github.com/rust-lang/rustc-dev-guide/pull/2158
> functionality removed from codebase

- src/queries/incremental-compilation-in-detail.md
Adds (CGU) clarification
This might seems kind of silly but I actually tripped up on this because I'm not familiar with codegen units nor with the other material in this document so going from codegen unit <-> CGU was kind of hard :laughing:
> Specify what a CGU is

- src/building/suggested.md
This adds a suggestion for `--keep-stage 0` when iteratively working on the standard library (and wanting to have a full toolchain otherwise).
> Add suggestion for `--keep-stage 0`

- src/overview.md
"Query-field" should be "Query-fied" - three instances.
Nitpicky for sure, but threw me for a slight loop first time I read it.
> Fix trivial typo of "query-fied"

- src/borrow_check/region_inference/closure_constraints.md
actually looked at it in detail now :3
> region-outlives propagation

- src/building/suggested.md
https://github.com/rust-lang/rust/blob/917bfa78478cbcc77406e5ea37b24c3eedefacf4/src/etc/completions/x.py.zsh
> completions: Zsh is now supported

- examples/rustc-driver-example.rs
- examples/rustc-driver-interacting-with-the-ast.rs
- examples/rustc-interface-example.rs
- examples/rustc-interface-getting-diagnostics.rs
- src/rustc-driver/getting-diagnostics.md
- src/rustc-driver/interacting-with-the-ast.md
- src/rustc-driver/intro.md
The removal of driver queries has changed the way rustc_interface can be used. I've also changed things a bit to fix things that were wrong in the docs even before the driver query removal. And finally this is now recommends using rustc_driver over rustc_interface like most tools are already doing. The rustc_driver api is a bit more stable and much easier to use when you don't need the flexibility of rustc_interface as is the case almost all the time. Rustdoc is one of the few tools that needs the flexibility of rustc_interface.
Blocked on https://github.com/rust-lang/rust/pull/134302 and testing the updated examples.
> Rework the driver docs

- src/appendix/bibliography.md
Fixes:
```
84 │ * [Rust-Bio: a fast and safe bioinformatics library](https://academic.oup.com/bioinformatics/article/32/3/444/1743419). Johannes Köster
│   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Server returned 403 Forbidden for https://academic.oup.com/bioinformatics/article/32/3/444/1743419
```
> Fix 403 received for HEAD request

- src/hir.md
Fixes:
```
error: Potential incomplete link
┌─ hir.md:99:47
│
99 │   Unlike [`DefId`]s, a [`HirId`] can refer to [fine-grained entities][Node] like expressions,
│                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Did you forget to define a URL for `Node`?
```
> Add missing link for [Node]

- book.toml
Addresses:
```
Server returned 500 Internal Server Error for https://github.com/rust-lang/rust/pulls?q=is%3Apr+label%3AS-inactive+is%3Aclosed
Server returned 401 Unauthorized for https://objects.githubusercontent.com/github-production-release-asset-2e65be/343907537/60cd5880-7b81-11eb-9502-68d5f473ebe2?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241103%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241103T085906Z&X-Amz-Expires=300&X-Amz-Signature=e532fd7d2bd271f12988982bc8e5a47a0f966b40452b55d444bbb74292ac1fb1&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Drustc.generic.wpaProfile&response-content-type=application%2Foctet-stream
Server returned 500 Internal Server Error for …
```
> Add a couple of linkcheck exceptions:

- .github/workflows/ci.yml
- README.md
- ci/linkcheck.sh
Fixes #2178.
This makes it less of a hassle to render the book locally.
> Opt into, rather than out of, linkcheck

- src/appendix/background.md
- src/borrow_check/region_inference.md
- src/borrow_check/region_inference/member_constraints.md
- src/bug-fix-procedure.md
- src/conventions.md
- src/hir.md
- src/mir/index.md
- src/notification-groups/about.md
- src/queries/incremental-compilation.md
- src/stabilization_guide.md
- src/tests/adding.md
- src/traits/canonical-queries.md
- src/traits/goals-and-clauses.md
- src/type-inference.md
- src/variance.md
- src/walkthrough.md
The `name` attribute on `<a>` elements [is deprecated and should be replaced by the `id` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#name).
`<a id="target">` is the pattern used by other mdbooks, e.g. the [Rust Book](https://github.com/rust-lang/book/blob/04d06dfe541607e6419f3d028c3f9b245f3be4d9/src/ch04-03-slices.md?plain=1#L237).
> Use `id` attribute on `<a>` elements instead of deprecated `name` attribute

- src/method-lookup.md
- src/solve/normalization.md
- src/solve/opaque-types.md
- src/tests/directives.md
Prevents FIXMEs from appearing on the UI. Unless I am missing something, displaying these to readers doesn't make much sense. Some of them might make sense to include on the UI, but I am unsure which ones. If you think any should be displayed please mark them specifically.
This is how it currently looks:
And this is how it looks after this patch:
> comment out FIXMEs to not display them on UI

- src/external-repos.md
Mention our usage of josh in `miri` and `rust-analyzer`, and add the cranelift backend to the list.
> Document josh subtrees and update subtree repository list

- src/tests/compiletest.md
This documents a local workaround that I found for the default lack of rust-analyzer integration for `rmake.rs` scripts.
(Actually, my original workaround was more complicated, but writing this PR prompted me to find the simpler version described here.)
> Describe how to use rust-analyzer with `rmake.rs`

- src/contributing.md
Closes https://github.com/rust-lang/rust-forge/issues/717.
> Only keep issue triage docs in Forge docs

- .github/workflows/ci.yml
- book.toml
This PR always stores the linkcheck cache when being run as part of the scheduled CI job. Note the normal PRs ignore the cache and check only the modified files. I also extended the cache expiration time so that the Nighly job can face the congressional limit from Github.com (`"Server returned 429 Too Many Requests"`).
Hopefully, it's a viable solution.
@camelid
> Save linkcheck cache always

- .github/workflows/ci.yml
cc #2030
This will cause the CI build to be marked successful even if the build
failed. Instead, use `if: '!cancelled()'` to always save the cache
(except when the job is cancelled), even if the linkcheck failed.
See https://stackoverflow.com/a/58859404 for more.
> ci: Remove incorrect use of `continue-on-error`

- src/tests/ci.md
This was changed in https://github.com/rust-lang/rust/pull/134898.
> Fix calculate-job-matrix.py link

- src/tests/ci.md
This documents how to determine which settings are used in CI, since I see this question come up regularly. We currently don't have a great way to answer the question, but at least there is something.
> Document how to find the configuration used in CI

- .github/workflows/rustc-pull.yml
- josh-sync/src/sync.rs
- triagebot.toml
The CI workflow is configured to run weekly on Monday morning, and it can also be executed manually through `workflow_dispatch`. The workflow runs `rustc-pull`, and if it actually pulled something, it force pushes to the `rustc-pull` branch, which is a sticky branch that should only be used for rustc pull updates.
If there is an open PR created by the Github Actions bot, it will be updated by that push. If not, the workflow creates a new PR. This PR also opts this repo into the auto open/close PR functionality from triagebot, so that CI runs on pull requests opened by the GitHub Actions bot user.
The PR also adds explicit error messages if there is nothing to pull during `rustc-pull`.
[This](https://github.com/Kobzol/rustc-dev-guide/pull/11) is how such a PR looks like.
> Add a CI workflow for performing rustc-pull automatically

- src/borrow_check/region_inference/closure_constraints.md
we look at universal regions required to be outlived by the `lower_bound`, not the other way around. I've already used it correctly further down xx
> incorrect wording

- src/solve/invariants.md
This PR removes the outdated comment about  wfx implies, as the issue has been resolved.  
The issue was discussed in [rust-lang/rustc-dev-guide#2161](https://github.com/rust-lang/rustc-dev-guide/issues/2161), and @JohnTitor confirmed that it is fixed:  
> "Indeed it seems to be fixed, we can remove that text now."  
Fixes #2161
> remove outdated text about wfx implies

- README.md
Stolen from https://github.com/rust-lang/rustc-dev-guide/blob/c1b4cfaa961f62c284868a8c248f62d5db21722f/.github/workflows/rustc-pull.yml#L28-L29
This might become outdated if the CI version ever gets bumped, but it's better than nothing.
r? @Kobzol
> Document how to install a suitable `josh-proxy` locally

- src/external-repos.md
Noticed [here](https://github.com/rust-lang/rustc-dev-guide/pull/2182#discussion_r1921628621).
> Add portable SIMD to list of subtrees

- josh-sync/src/sync.rs
Reverts rust-lang/rustc-dev-guide#2217. Looks like it shouldn't [be needed](https://rust-lang.zulipchat.com/#narrow/channel/196385-t-compiler.2Fwg-rustc-dev-guide/topic/a.20move.20to.20main.20repo.20.28rust-lang.2Frust.29/near/495564127).
> Revert "Add `@bors rollup=never` to rustc-push PR body"

- src/early_late_parameters.md
We will be transitioning mdbook to sync with rustdoc on how it interprets "boring" lines (https://github.com/rust-lang/mdBook/pull/2530). This requires a space after the leading `#`. This PR updates the rustc-dev-guide for this change.
> Update boring lines to sync with rustdoc

- src/backend/libs-and-metadata.md
Compression of dylibs was removed in https://github.com/rust-lang/rust/pull/113695 (and decompression removed in https://github.com/rust-lang/rust/pull/132402).
> Correct information on dylib compression

- .github/workflows/ci.yml
It seems one can't overwrite a cache entry:
```
Failed to save: Unable to reserve cache with key linkcheck--0.8.1, another job may be creating this cache. More details: Cache already exists. Scope: refs/heads/master, Key: linkcheck--0.8.1, Version: 33f8fd511bed9c91c40778bc5c27cb58425caa894ab50f9c5705d83cb78660e0
Warning: Cache save failed.
```
A proper solution is to use `restore-keys`:
https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache
I tested that in the following Draft PR (#2222), with the following Action result:
https://github.com/rust-lang/rustc-dev-guide/actions/runs/12966946869/job/36168260759
@camelid
> CI: use key-restore for cache GH action

- src/rustdoc.md
- https://github.com/rust-lang/rust/pull/135353
- https://github.com/rust-lang/rust/pull/136161
> Add some extra pointers for rustdoc frontend devs

- src/diagnostics.md
This PR closes #2114.
I added a link to the `declare_lint!` macro, which describes the format of a lint, including {{produces}} marker.
> Add a link to declare_lint! macro doc in diagnostics.md

- src/getting-started.md
This PR closes #2069. 
I added a short section mentioning `E-needs-test` label in getting-started.md
> Add "Writing tests" section in getting-started.md

- .github/workflows/rustc-pull.yml
- josh-sync/src/main.rs
- josh-sync/src/sync.rs
This PR runs the `rustc-pull` workflow every day, and changes the CI script so that it only sends a message to Zulip when something was actually pulled (regardless of whether an existing PR was updated or a new one was created).
> Make rustc pulls on CI more frequent

- .github/workflows/rustc-pull.yml
The token was [missing](https://github.com/rust-lang/rustc-dev-guide/actions/runs/13066144889/job/36459042391).
> Pass `GITHUB_TOKEN` to Zulip CI step

- .github/workflows/rustc-pull.yml
This is needed for the `gh` command to work.
> Checkout repository sources in rustc-pull CI action

- src/building/suggested.md
https://github.com/rust-lang/rust/pull/129620 added flake and direnv support for nix development
>  Use a more convinient way of developing rustc on NixOS

- src/diagnostics.md
Also, this follows the common (in this repo) practice of avoiding use of inline links
> overlong line

- .github/workflows/rustc-pull.yml
Recently, I made the rustc-pull workflow run every day, with the idea that it would create a "rolling" PR that would be merged from tiem to time. However, it is not clear when should such a PR be merged, and merging it every day creates unnecessary churn and a lot of useless merge commits.
This PR changes the cron workflow so that it runs twice a week (Monday and Thursday), to give us a faster notice when there are merge conflicts, but doesn't create a new PR every day. If there is a PR that is more than a week old, the workflow will notify us on Zulip.
> Make the rustc-pull workflow run less often

- src/tests/ci.md
Closes https://github.com/rust-lang/infra-team/issues/191
> improve CI cache docs

- src/param_env/param_env_acquisition.md
- src/param_env/param_env_what_is_it.md
Apparently there's necessary a bigger overhaul of the sections related to `ParamEnv` and the change author is working on that (@lcnr).
In the meantime, I would like to remove the 2 links so that green can be green again.
> Remove reference to enum.Reveal

- .github/workflows/ci.yml
Right now, the cache is properly loaded and updated during each run of the CI. However, we still hit `429`s every time the big portion of cache entries (pointing to GH) are invalidated. Plus, sometimes there are volatile links that tend to fail occasionally. Thus I recommend running the CI multiple times a day, it would run fast (only invalidated cache entries + failing will be checked).
@camelid What do you think?
> Run CI multiple times a day

- src/building/bootstrapping/debugging-bootstrap.md
I was trying to learn more about bootstrap, read about the tracing macros, thought they were cool, but also writing `#[cfg(tracing)] trace!` each time gets annoying.
So I thought I'd PR a shim macro that hides the `cfg` internally (and contribute to rustc finally),  but turns out @jieyouxu has already done that in https://github.com/rust-lang/rust/pull/136392
Well, guess I'll be content with just a doc change for now then 🙃
> Don't suggest explicitly `cfg`-gating `trace!` calls in bootstrap

- src/SUMMARY.md
- src/effects.md
[rendered](https://github.com/fee1-dead-contrib/rustc-dev-guide/blob/constck/src/effects.md)
cc @rust-lang/project-const-traits
> Rewrite effects checking chapter

- src/tests/directives.md
This compiletest directive was removed in rust-lang/rust#120265.
> Remove the doc for `no-system-llvm`

- src/SUMMARY.md
- src/rustc-driver/remarks-on-perma-unstable-features.md
Fixes rust-lang/rust#137421
r? @jieyouxu
> Add issue link for explaining that why rustc_private linker fails

- .github/workflows/ci.yml
This can block PR CI yet remain unactionable for the contributor, since this is subject to network conditions and availability of the servers hosting the external web links.
~~I don't see a way for PR CI to override the linkcheck config to skip external web links yet let the cron job CI to perform external web link checks, so this PR does the sledgehammer approach of disabling external web link checks for both.~~ EDIT: apparently `MDBOOK_OUTPUT__LINKCHECK__FOLLOW_WEB_LINKS` is a thing.
> Don't linkcheck external web links in PR CI

- src/rustc-driver/remarks-on-perma-unstable-features.md
This makes this command pass
mdbook test --chapter "Remarks on perma-unstable features"
> use correct code block markers

- src/building/prerequisites.md
https://github.com/rust-lang/rustc-dev-guide/commit/e4ddc21c8ab4bee43c905b1d4621b4c657c5d0ef This commit renamed `config.toml` to `bootstrap.toml`.
> doc: fix reference to #create-a-configtoml

- src/tests/ui.md
> mention that known-bug test directive takes arguments

- examples/rustc-driver-example.rs
This was removed, likely by mistake, during a refactor.
> example assumes a static exists

- src/building/how-to-build-and-run.md
This link currently points to the current section, instead of the section on partial clones
> Fix partial clone link

- src/rustdoc.md
> add some links about the rustdoc-gui test suite

- src/tests/ui.md
am unsure about "exceptional cases"... feels too prescrictive
but I did not want to change any meaning on this pr
> improve flow

- src/about-this-guide.md
1. added two new parts: Bootstrapping and Supporting Infrastructure;
2. touched up names of pre-existing parts, to match actual names in sidebar;
3. syntactic nits (start description of Analysis with a capital letter).
> Update table of contents in about-this-guide.md

- src/walkthrough.md
The URL fragment used suggests that this link was pointing to a section that has since been moved to its own page. This confused me at first.
I have edited the link to refer to the dedicated crater page.
> Update "crater" link to actually point to crater.md

- src/contributing.md
"how to much trust" implies the opposite
> remove implied information

- src/contributing.md
Not obvious what "sort by" means
> use more simple language

- triagebot.toml
This PR enables two new triagebot feature `[canonicalize-issue-links]` and `[no-mentions]`.
Documentation at https://forge.rust-lang.org/triagebot/canonicalize-issue-links.html and https://forge.rust-lang.org/triagebot/no-mentions.html.
> Enable `[canonicalize-issue-links]` and `[no-mentions]` in triagebot.toml

- src/tests/ui.md
See [#t-compiler/help > Warnings in UI tests](https://rust-lang.zulipchat.com/#narrow/channel/182449-t-compiler.2Fhelp/topic/Warnings.20in.20UI.20tests/with/511274232).
cc @nnethercote
> Document `-A {unused,internal_features}` ui test mode presets

- src/SUMMARY.md
- src/autodiff/debugging.md
- src/autodiff/flags.md
- src/autodiff/internals.md
- src/autodiff/limitations.md
Upstreaming of std::autodiff got approved, so I want to get rid of my docs under https://enzyme.mit.edu/rust/
These are the first ones, I'll add a few more docs here and to the nightly docs.
r? @jieyouxu
> Add a first version of autodiff docs

- src/SUMMARY.md
- src/building/bootstrapping/bootstrap-in-dependencies.md
> document `#[cfg(bootstrap)]` in dependencies

- src/autodiff/installation.md
We added some more pretty tests, so updating the test command. Also adding a feature-gate test, which I forgot about.
> update build and test instructions

- .github/workflows/rustc-pull.yml
- README.md
- Rust backcompat removes the need to specify the version here
- Using these commands can result in a needless toolchain getting downloaded, like in the case where user only has Nightly installed
> toolchain version does not need to be specified

- src/SUMMARY.md
Close: rust-lang/rustc-dev-guide#2341
> fix(docs): add newlines between prefix/suffix chapters

- src/git.md
closes rust-lang/rustc-dev-guide#2336
> replace command that does not work

- src/guides/editions.md
This adds some documentation on how to stabilize an edition, and how to migrate the standard library after that has happened.
cc @traviscross
> Add docs about stabilizing an edition

- src/compiler-src.md
Also, these are normal Rust things (crates/packages), so remove the word *normal*.
> for a more friendly output

- josh-sync/src/sync.rs
~Also, remove `@ghost` in pr description, to avoid confusion... thought it was a real user.~
Heh, I see [it has utility](https://forge.rust-lang.org/triagebot/pr-assignment.html#ghost).
> use repo name in push pr title

- triagebot.toml
Let's try running it on a repository first.
Doc: https://forge.rust-lang.org/triagebot/behind-upstream.html
r? @Urgau 
cc @Kobzol
> Enable [behind-upstream] triagebot option

- src/building/bootstrapping/intro.md
- src/building/bootstrapping/what-bootstrapping-does.md
The sentence
> However it was abandoned long ago and the only way to build a modern version of rustc is **a** slightly less modern version.
feels like it's grammatically missing the preposition 'with', as well as some commas around "However" etc.
> Adds 'with' to the bootstrapping docs to help clarify how to build a new compiler

- src/tests/best-practices.md
https://rustc-dev-guide.rust-lang.org/tests/best-practices.html#test-naming specifically asks devs to "Avoid using only issue numbers as test names".
This commit introduces a minor change to https://rustc-dev-guide.rust-lang.org/tests/compiletest.html#crashes-tests that changes the advice to use only issue numbers as names to the advice to append them at the end of the file name.
> Align advice to discourage issue-number-only names

- src/traits/unsize.md
Tuple unsizing (behind `unsized_tuple_coercion`) was removed by https://github.com/rust-lang/rust/pull/137728.
Discovered via https://github.com/rust-lang/rust/pull/140919.
> Remove obsolete reference to `unsized_tuple_coercion`

- src/backend/libs-and-metadata.md
A few issues I couldn't help but notice while reading [Libraries and Metadata](https://rustc-dev-guide.rust-lang.org/backend/libs-and-metadata.html#libraries-and-metadata).
> Fix typos in "Libraries and Metadata"

- src/SUMMARY.md
Better, because then one knows how to run the examples.
> Make run instructions first

- src/cli.md
The old link does not exist anymore (404).
> Update link to Forge guide on new flags

- src/ty_module/binders.md
Normally I refrain from nit picking, but this seamed worth it.
> Small typo and style fixes in  binders.md

- src/ty_module/instantiating_binders.md
- src/ty_module/param_ty_const_regions.md
The order might have been reversed at some point, leading to the two chapters talking about each other in the wrong order.
> Update links between ty-module and binders

- src/early_late_parameters.md
While this is implicit, since "early bound params" are the ones that are bound when naming a function, for the non-expert (myself; most people motivated to read the manual) it helps to be explicit here.
Not feeling strongly about this one. Feel free to ignore/tell me to close PR.
Also let me know if I should rather not propose similar changes in the future.
> Make it clear we talk about early bound params

- src/tests/ui.md
It does not do any line matching, so it should be separated from the other types
> ~? annotation type is special

- src/rustdoc.md
I initially just added this at the bottom of the list but I think it would be a bit more natural if the mention of `tsc` stayed as the final element.
> rustdoc.md: reorder list so test suites are not split up

- src/appendix/compiler-lecture.md
A good talk to catch up with the status of Rust with LLVM.
> Add LLVM link in appendix

- src/tests/ci.md
Now that CI has been finally migrated to `rust-lang/rust`. Might want to wait a few hours (from this PR being opened) to see if everything works fine.
Context: https://github.com/rust-lang/infra-team/issues/188
> Remove mentions of rust-lang-ci/rust

- src/normalization.md
I inferred the tracking info myself. If you review this PR, please confirm that it's correct. Is such info useful in the docs in your opinion?
> Add time reference and tracking info for trait system refactor

- src/solve/coinduction.md
Although they are clickable in the github preview, they aren't in the actual rendered HTML on https://rustc-dev-guide.rust-lang.org/.
The commit fixes that.
Let me know if you'd like it modified in some way, e.g. to use part of the text instead of the URL as the click target.
> Make links in coinduction.md clickable

- src/tests/directives.md
> directives.md: Fix `//@ build_aux_docs` -> `//@ build-aux-docs`

- triagebot.toml
Best reviewed commit-by-commit.
Closes rust-lang/rustc-dev-guide#2411. No `adhoc_groups` are set up yet, intended as follow-up.
cc @BoxyUwU
r? @Kobzol
> Adjust triagebot config

- triagebot.toml
This is a set of **opt-in** reviewers that PR authors can request reviews from via `r? rustc-dev-guide` following discussions in [#t-compiler/rustc-dev-guide > Adjust triagebot configs @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/196385-t-compiler.2Frustc-dev-guide/topic/Adjust.20triagebot.20configs/near/521342052). I added initial WG members who indicated that they would like to be added to the opt-in review group.
No new PR messages are configured yet, as it is not yet a supported triagebot functionality.
Part of https://github.com/rust-lang/rustc-dev-guide/issues/2428.
> Setup basic `r? rustc-dev-guide` review group

- src/return-position-impl-trait-in-trait.md
There is no `foo` symbol in the preceding example. I assume the method `bar` is meant.
> Trivial: fix typo (change `foo` to `bar`)

- src/opaque-types-impl-trait-inference.md
This allows for the code to compile on `nightly`.
> Add opaque type attributes

- src/building/bootstrapping/debugging-bootstrap.md
> Fix incorrect use of "recommend" over "recommended"

- src/SUMMARY.md
- src/rustdoc-internals.md
- src/rustdoc-internals/rustdoc-gui-test-suite.md
- src/rustdoc-internals/rustdoc-json-test-suite.md
- src/rustdoc-internals/rustdoc-test-suite.md
- src/rustdoc.md
- src/tests/compiletest.md
- src/tests/directives.md
Follow-up to rust-lang/rustc-dev-guide#2295 (applies my remaining review comments).
This is WIP / a draft because I g2g. Will impl all FIXME(fmease)s when I come back.
cc @lolbinarycat @jieyouxu @notriddle
> rustdoc: Further improve chapters and sections on testing

- src/rustdoc-internals/rustdoc-test-suite.md
Follow up to https://github.com/rust-lang/rustc-dev-guide/pull/2298, I'm tired...
> Follow up: Fix typo

- src/queries/incremental-compilation-in-detail.md
> use sentence case

- src/contributing.md
Building the docs with stage 0 does not work anymore.
> Use stage 1 for building docs

- src/building/new-target.md
That was intended to be a list.
Also, the order is not relevant.
r? ghost
> fix markup

- src/contributing.md
> Explain where rdg changes should be submitted

- src/hir/lowering.md
- `for` loops now use two `match`es for all of their bindings. I'm not sure this is the most helpful way of conveying that, but it's about as informative as before while staying brief. I'd be happy to make this clearer, if anyone has ideas.
- `while let` and `if let` don't use `match`; they use `let` expressions in their conditions. Since `if let` no longer has a significantly different desugaring and having a whole bullet point for `while` would feel redundant with `for`, I've removed those examples.
> update AST-to-HIR lowering examples for conditionals and loops

- src/tests/ui.md
The last part of the paragraph did not fit
> build-fail directive: make explanation more uniform

- src/tests/intro.md
That is, calling it an example is misleading
> distcheck has only one possible invocation

- .github/workflows/rustc-pull.yml
Replace the CI workflow in this repo with a generalized workflow from `josh-sync`. I tested this on my forks, but there's no other good way to test this than just merge it and see what happens on CI =D
> Migrate rustc-pull to CI workflow from `josh-sync`

- src/tests/directives.md
> directives.md: build-aux-docs does not work with aux-crate

- src/solve/invariants.md
> go over invariants again :3

- src/serialization.md
`TyDecoder` and `TyEncoder` are the **subtraits** of `Decoder` and `Encoder`. The guide says they are the **supertraits**.
> Mistake in section serialization in rustc

- src/external-repos.md
> add rdg push git config entry for git protocol pushers (again)

- src/external-repos.md
Now all our Josh subtrees should be using josh-sync (https://github.com/rust-lang/rust-analyzer/pull/20280, https://github.com/rust-lang/miri/pull/4490).
> Update josh sync documentation

- src/tests/docker.md
Not sure how I managed to miss this for so long :man_facepalming:
> Remove outdated ci.py reference

- src/appendix/humorust.md
- src/tests/directives.md
- src/tests/ui.md
The previous documentation suggested tests could be placed "anywhere" in `tests/ui`, according to current requirement (https://github.com/rust-lang/rust/pull/144813) for proper subdirectory organization. This clarifies that tests must be placed in appropriate subdirectories, removes the outdated `hello.rs` example and fixes few more links to old tests.
r? rustc-dev-guide
> Update documentation for current tests requirements

- src/about-this-guide.md
- src/diagnostics/error-codes.md
- src/getting-started.md
The official Discord server is no longer active (cannot be posted to).
> Remove mentions of Discord.

- src/SUMMARY.md
- src/offload/installation.md
- src/offload/usage.md
WIP, I will develop this along with https://github.com/rust-lang/rust/pull/142696
command:
```
RUSTFLAGS="-Ctarget-cpu=gfx90a --emit=llvm-ir" cargo +offload build -Zunstable-options -r -v --target amdgcn-amd-amdhsa -Zbuild-std=core
```
> add gpu device side instructions

- src/building/bootstrapping/what-bootstrapping-does.md
see https://github.com/rust-lang/rust/pull/145253 for reference.
> Update bootstrapping docs to account for new stage meanings

- src/backend/updating-llvm.md
- src/fuzzing.md
- src/overview.md
- src/parallel-rustc.md
- src/profiling.md
- src/rustdoc-internals.md
Updated explicit date annotations to 2025-08 
Addresses https://github.com/rust-lang/rustc-dev-guide/issues/2528.
> dates: refresh infra/tooling date annotations to Aug 2025

- src/queries/query-evaluation-model-in-detail.md
- src/queries/salsa.md
- src/query.md
Updated date-check annotations to **2025-08**, preserving the local format at each site.
**Addresses rust-lang/rustc-dev-guide#2528**
> dates: refresh query-system date annotations to 2025-08 (preserve style)

- src/borrow_check/region_inference/member_constraints.md
- src/opaque-types-type-alias-impl-trait.md
- src/stability.md
- src/thir.md
- src/traits/chalk.md
- src/traits/resolution.md
- src/ty-fold.md
- src/type-inference.md
Updated date-check annotations to the current month.
**Addresses rust-lang/rustc-dev-guide#2528**
> dates: refresh type system & traits date annotations to Aug/2025

- src/stabilization_guide.md
- Use `gate_all!` consistently in both the example and the explanation.
- Fix `#[pub_restricted]` → `pub(restricted)`.
- No other example or API changes.
Fixes rust-lang/rustc-dev-guide#2401
> stabilization_guide: fix macro name and syntax in gating example

- src/contributing.md
Sister PR of [rust-forge#926](https://github.com/rust-lang/rust-forge/pull/926).
Add clearer wording about our "spellchecking / typos" contributing policy to discourage spellcheck patches on internal documentation.
> Mention our policy on typofixes for internal docs

- src/queries/query-evaluation-model-in-detail.md
- src/queries/salsa.md
- src/query.md
Reverts rust-lang/rustc-dev-guide#2558
See https://github.com/rust-lang/rustc-dev-guide/issues/2528#issuecomment-3239543008
> Revert "dates: refresh query-system date annotations to 2025-08 (preserve style)"

- src/backend/updating-llvm.md
- src/fuzzing.md
- src/overview.md
- src/parallel-rustc.md
- src/profiling.md
- src/rustdoc-internals.md
Reverts rust-lang/rustc-dev-guide#2557
See https://github.com/rust-lang/rustc-dev-guide/issues/2528#issuecomment-3239543008
> Revert "dates: refresh infra/tooling date annotations to Aug 2025"

- src/type-inference.md
This was first renamed to `get_region_var_origins` in https://github.com/rust-lang/rust/pull/109753, and then to `get_region_var_infos` in https://github.com/rust-lang/rust/commit/b0fc1d47d5dcffb5d516059d4a5af3b6843132d5
> Update renamed `take_region_var_origins`

- src/compiler-src.md
- src/rustdoc-internals/rustdoc-json-test-suite.md
Closes https://github.com/rust-lang/rust/issues/100515
[Rendered](https://github.com/aDotInTheVoid/rustc-dev-guide/blob/tenthousandyears/src/rustdoc-internals/rustdoc-json-test-suite.md)
> Start documenting tests/rustdoc-json

- src/about-this-guide.md
> about-this-guide.md: improve a bit

- src/tests/codegen-backend-tests/cg_gcc.md
Since we're now going to make GCC backend mandatory for CI (https://github.com/rust-lang/rust/pull/146414), we need to make it as easy as possible for contributors to be able to test their code with this backend as well.
r? @Kobzol
> Add missing documentation for running tests with GCC backend

- src/building/how-to-build-and-run.md
Not sure `--all` flag is well-known, and also not sure if `rm -r build` is cross-platform.
> how-to-build-and-run.md: replace "rm build" with "x clean --all"

- src/building/how-to-build-and-run.md
These were not updated after a bootstrap change where std cannot be built with stage0 rustc
> how-to-build-and-run.md: update "building compiler" section

- src/tests/codegen-backend-tests/cg_gcc.md
Context: https://rust-lang.zulipchat.com/#narrow/channel/233931-t-compiler.2Fmajor-changes/topic/Run.20more.20tests.20for.20rustc_codegen_gcc.20in.20t.E2.80.A6.20compiler-team.23891/with/543584710
> Add debug assertions flag to `cg_gcc` invocation
