rust-lang/rustc-dev-guide

- src/mir.md
> Copy MIR readme

- src/type-inference.md
The links are already to the other chapters of the book, but the link _text_ needs to be updated.
> Update link text

- src/glossary.md
> Alphabetize glossary

- ci/install.sh
> Force mdbook update on CI if there is a version mismatch.

- src/SUMMARY.md
- src/incrcomp-debugging.md
cc @nikomatsakis @michaelwoerister
cc #2 #87
> Add incremental compilation debugging subchapter

- src/tests/running.md
> Fix a typo

- src/how-to-build-and-run.md
[#115](https://github.com/rust-lang-nursery/rustc-guide/issues/115)
> Expand descriptions of compilation stages

- src/appendix-background.md
A+++++ resource IMHO!
r? @nikomatsakis
> appendix-background: Link to *Static Program Analysis*

- src/conventions.md
This is already mentioned elsewhere, but important things are mentioned twice.
Closes #124
> Add how to run tidy script in isolation to text

- src/hir.md
Fix #116
@Michael-F-Bryan @3442853561 Let me know what you think.
> Reword HIR intro

- src/SUMMARY.md
- src/chalk-overview.md
- src/traits-slg.md
This is the overview of [chalk](https://github.com/rust-lang-nursery/chalk) given to me by Niko in the #wg-traits Discord channel.
r? @nikomatsakis 
[Rendered](https://github.com/sunjay/rustc-guide/blob/8cfd5c5aede5fe17cc286c230ccd2eba4cc966bd/src/chalk-overview.md)
Even more rendered: (click for full size)
> Added An Overview of Chalk

- src/high-level-overview.md
- src/hir.md
IR is a foreign acronym to me, so having it fully expressed in the beginning as Intermediate Representation helps me comprehend the subject.
I also verified that the link works correctly.
> Define HIR more specifically

- src/query.md
I wasn't clear on what a Cycle was when reading through the document.
Defining it will be helpful for other readers not familiar with it as
well.
> Define a Cycle in the Query guide.

- src/how-to-build-and-run.md
> Add bit about ctags

- book.toml
> removed whitespace

- README.md
> Add a link to the rustc docs

- README.md
- src/appendix/background.md
- src/compiler-debugging.md
- src/compiletest.md
- src/conventions.md
- src/incrcomp-debugging.md
- src/mir/borrowck.md
- src/mir/index.md
- src/mir/passes.md
- src/mir/regionck.md
- src/mir/visitor.md
- src/query.md
- src/tests/adding.md
- src/tests/intro.md
- src/tests/running.md
- src/traits/associated-types.md
- src/traits/canonical-queries.md
- src/traits/canonicalization.md
- src/traits/goals-and-clauses.md
- src/traits/index.md
- src/traits/lowering-module.md
- src/traits/lowering-rules.md
- src/traits/lowering-to-logic.md
- src/type-checking.md
- src/variance.md
> fix all the not-en-dashes

- src/diag.md
> Add a bit about buffered lints

- src/SUMMARY.md
- src/existential-types.md
> existential type resolution

- src/SUMMARY.md
- src/compiler-team.md
> add a section about the compiler team

- src/tests/adding.md
> No copyright notices on new tests

- README.md
> Update a few parts of the readme

- src/traits/implied-bounds.md
Complete overview of the implementation of implied bounds. It references the chapter on WF checks, which I'm also currently writing.
> Write implied bounds chapter

- src/compiler-debugging.md
Fix #78 
cc @ehuss @Mark-Simulacrum
> Add a note on bisecting

- src/ty.md
This has been renamed in https://github.com/rust-lang/rust/pull/53581.
> Update TypeVariants to TyKind

- src/traits/canonicalization.md
@alexreg @nikomatsakis Does this look right?
Fix #185
> Clarify why 'static is free

- src/tests/adding.md
> Remove reference to copyright comment

- src/name-resolution.md
"The name resolution is a separate pass" is a wishful thinking :(
> document the interaction between macros and nameres

- src/mir/construction.md
r? @nikomatsakis 
Most of these things are already pretty well documented in https://github.com/rust-lang/rust/blob/e8009885794e6108313683087fc6bfcd55145395/src/librustc_mir/build/expr/mod.rs#L11 so I created more of an overview
Is this what you had in mind? I can also add examples to demonstrate the things explained in text.
> Document MIR building somewhat

- ci/check_line_lengths.sh
> make the line-length script respect 100 char limit XD

- src/SUMMARY.md
- src/codegen/updating-llvm.md
I was talking with @tromey about LLDB/clang updates and I think it's about time we document all this!
> Add some documentation about updating LLVM

- src/diag.md
- src/hir.md
Broken link hunt :bow_and_arrow:
> Fixes broken links

- src/traits/specialization.md
> Add link to sunjay talk

- src/kinds.md
Addresses https://github.com/rust-lang/rustc-guide/pull/282#discussion_r265550258.
> Fix mask -> tag terminology

- src/tests/intro.md
Follow up for Assembly test suite introduced in https://github.com/rust-lang/rust/pull/58791.
cc @mark-i-m
> Add a note about Assembly test suite

- src/traits/lowering-module.md
Both test annotation and test result changed.
> Update lowering-module test case

- .travis.yml
cc @igaray Sorry for the trouble <3
> Use nightly rust for CI

- src/type-inference.md
Also try to test the top example
> Fix a few typos in type inference chapter

- src/SUMMARY.md
- src/borrow_check/two_phase_borrows.md
- src/closure.md
cc @blitzerr @nikomatsakis 
Hi @blitzerr! I am going to go ahead and merge your changes with my edits to address Niko's comments (I hope this is ok with you). Please feel free to open a PR and make any changes you want.
Also, sorry about all the github shinanigans... I'm not really sure what github is doing...
> Closure expansion notes

- src/compiler-team.md
> fix compiler-team

- src/SUMMARY.md
- src/appendix/bibliography.md
> Add bibligraphy appendix

- src/borrow_check/region_inference/constraint_propagation.md
CI is failed due to broken links so I fixed them.
r? @mark-i-m
> Fix broken links

- src/compiler-team.md
> Update experts' link

- README.md
- src/SUMMARY.md
- src/borrow_check/moves_and_initialization/move_paths.md
- src/borrow_check/region_inference.md
- src/borrow_check/region_inference/constraint_propagation.md
- src/borrow_check/region_inference/lifetime_parameters.md
- src/borrow_check/region_inference/member_constraints.md
- src/traits/index.md
Fixes as follows:
- fixes spelling
- removes unnecessary white spaces and blank lines
**Updated**: I added some minor fixes.
> Some minor fixes

- src/appendix/humorust.md
> break rust;

- src/the-parser.md
see https://github.com/rust-lang/rust/pull/59706
cc @mark-i-m
> write a short paragraph about the new lexer

- src/borrow_check/moves_and_initialization/move_paths.md
> Place is now a struct on nightly

- src/appendix/humorust.md
- src/compiler-team.md
This fixes 2 of the 3 broken links in the repository.
> Fix broken links.

- src/appendix/humorust.md
- src/compiletest.md
- src/how-to-build-and-run.md
- src/tests/adding.md
- src/tests/running.md
> run-pass dir is gone

- src/SUMMARY.md
- src/stability.md
cc @oli-obk @Centril @RalfJung @shepmaster
> Explain stability attrs

- README.md
> Add some instructions to fix toolstate

- README.md
This is a follow-up PR of #446.
r? @spastorino
> Add guidance for making a PR fixes toolstate

- src/SUMMARY.md
Should of been part of 2ef961e45465a5edfbd3d5c49e4a16cee356b44b
> file has since been removed from content

- src/ice-breaker/about.md
> Fix missing link

- src/conventions.md
This is more in line with current practices.
> Please don't rustfmt (yet).

- src/macro-expansion.md
We can remove when it has been transcribed
> Add discussion transcript so we don't lose it

- src/miri.md
r? @oli-obk @eddyb
Cc @iwikal whose questions triggered this PR: feedback would be welcome! As someone who is still new to rustc and Miri, how comprehensible do you think this all is?
> expand and update Miri description

- src/SUMMARY.md
- src/appendix/compiler-lecture.md
> Add compiler lecture series appendix

- book.toml
By this link, we can go to the repo quickly.
> Add link to git repository for book

- src/traits/chalk-overview.md
- src/traits/wf.md
> Fix chalk links

- src/appendix/glossary.md
- src/mir/optimizations.md
cc @oli-obk @JohnTitor #331 
This is a really minimal version until we have something more later.
> Write a minimal MIR opt chapter

- src/ty.md
NB: Thank you for this guide :)
> ty.md: fix a typo

- src/rustdoc.md
> Website has disappeared

- .travis.yml
We don't want to test almost any of our code blocks... none of them are valid on their own...
> Don't run mdbook test

- src/rustdoc.md
Reverts rust-lang/rustc-guide#523
> Revert "Website has disappeared"

- src/walkthrough.md
> Define FCP where first used

- book.toml
- src/SUMMARY.md
- src/salsa.md
Closes #401
cc @Karrq (who gets all credit for this content)
This great content, but Karrq doesn't seem to have time ATM and the PR has been open for too long.
> Add Karrq's salsa chapter

- src/tests/intro.md
r? @mark-i-m 
Not sure this is enough, but...
Fixes #531.
> Remove reference to run-pass tests

- src/codegen.md
- src/conventions.md
- src/diagnostics.md
Made minor grammatical fixes to the rustc-guide.
> minor grammar fixes

- src/panic-implementation.md
Fixes #550
I can no longer reproduce the issue
> Add missing hash marks

- src/ice-breaker/about.md
> Add an example PR to join the Cleanup Crew ICE-Breakers

- src/ice-breaker/about.md
(I figure its low cost to just list all the possible pings, compared to the cost of people getting the command wrong or not even knowing the full set of teams possible.)
> Added example of icebreakers-cleanup-crew

- src/codegen/backend-agnostic.md
> minor typo fix

- src/query.md
Hi !
A little typo in the Query pages. Happy to make my first little contribution !
Loris
> Minor typo correction

- src/macro-expansion.md
Follow-up for #580 
r? @mark-i-m
> Update section following current state

- src/tests/intro.md
> Document ./x.py fmt

- src/queries/query-evaluation-model-in-detail.md
> Fixed wrong variable name

- src/tests/adding.md
- src/tests/running.md
> Move bless section to running chapter

- src/appendix/compiler-lecture.md
NB: the line 28 (`- assigned to @juanbono`) has been discarded.
> Make all links in Appendix E active

- README.md
*There's two kind of people in this world. Those who spell French properly, and those who don't.*
> Spell `Voilà` properly in README.md

- src/param_env.md
Based on https://github.com/rust-lang/rustc-dev-guide/pull/589#issuecomment-589239894
> Add some more info to param_env

- src/rustc-driver.md
Now that the example has been merged, the CI link check should pass.
@mark-i-m
> Reference example from #621

- src/queries/incremental-compilation-in-detail.md
- src/queries/query-evaluation-model-in-detail.md
This PR adds a bit more information about cache promotion and how the compiler backend is integrated with incremental compilation.
> Update description of incremental compilation.

- src/appendix/glossary.md
> Add BodyId to glossary, and links for ids to HIR identifiers section

- src/rustc-driver-interacting-with-the-ast.md
> add pre-requisite for calling into compiler API

- README.md
Addresses discussion in https://rust-lang.zulipchat.com/#narrow/stream/196385-t-compiler.2Fwg-rustc-dev-guide/topic/429.20errors
> Add README build instructions, link check configuration instructions, link check error documentation

- src/appendix/glossary.md
- src/backend/monomorph.md
- src/borrow_check.md
- src/borrow_check/region_inference/constraint_propagation.md
- src/building/suggested.md
- src/mir/index.md
- src/mir/optimizations.md
- src/query.md
- src/traits/hrtb.md
> Add ids to all glossary items, fix existing links

- .travis.yml
fixes #650 
It turns out this was a known issue that was fixed in mdbook 0.3.5
cc @anp @JohnTitor
> Update to mdbook 0.3.7

- src/overview.md
> Fix some whitespace

- src/SUMMARY.md
- src/parallel-rustc.md
cc @Zoxc @michaelwoerister @aturon @nikomatsakis @alexcrichton @Mark-Simulacrum (though, unfortunately, a significant number of these awesome folks are no longer active) 
cc #81 
This is towards the "guide technical debt" effort we are doing this sprint. Unfortunately, I don't have a lot to add here.
> Add a bit more on parallel compilation

- src/building/bootstrapping.md
> Document `RUSTFLAGS_STAGE_` bootstrap environment variables

- .travis.yml
I want to see if we can update to ubuntu 20.04 (the latest LTS). Perhaps that will solve some of the cert issues?
> Playing with travis images

- src/tests/adding.md
Companion to rust-lang/rust#73044.
> Document needs-* compiletest directives

- .travis.yml
Just need to specify `origin`. I'm not sure what made previous PRs pass and this one fail...
> Fix CI rebase

- src/tests/adding.md
And some drive-by additions to the `ignore-X` list.
> Add some more detail on compiletest normalization.

- src/compiler-debugging.md
- src/rustdoc.md
- `RUSTDOC_LOG`
- `// aux-build:filename.rs`
- `// build-aux-docs`
> Document rustdoc behavior

- .travis.yml
Blocked on #757 
Redo of #737 but correct (I hope)
> Fix rebase

- book.toml
> Fold chapters by default to make ToC shorter

- src/ty.md
Makes various edits throughout for formatting, punctuation, and typo fixes. Also makes some edits and re-wording for clarity.
(This is my first contribution to this to this guide, so hopefully I haven't misunderstood too much! 😇 )
> Edit ty.md

- src/SUMMARY.md
This seems to fit better with analysis IMHO.
Thoughts?
> Move Errors and Lints to Analysis

- src/building/suggested.md
As discussed on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/incremental.20compilation.20question/near/202742715). Those suggestions are not mine and I can't personally judge if they are sensible. I linked to their sources.
cc @mark-i-m
> Suggest selectively disabling debug and optimizations

- src/crates-io.md
- src/stability.md
Fixed according to https://github.com/rust-lang/rust/commit/62cf767a4a39b47677d18110359d9e7152dc9d1c.
> Avoid "whitelist" according to rust-lang/rust changes

- src/serialization.md
> Remove unneeded hashmarks

- src/queries/incremental-compilation.md
For someone hasn't learnt about graph theory, edge concept is incomplete.
> Link ref to edge concept in graph theory

- src/building/suggested.md
That's the workflow I personally use (as I am using auto-save), so I guess others might find it useful as well (where "others" includes "me on the other laptop").
> Document how to use build task for x.py check

- src/SUMMARY.md
- src/part-5-intro.md
> Remove duplicate MIR chapter entry

- src/mir/construction.md
Also cleaned up some other minor stuff.
I do not know much about how MIR works (that's why I was reading this section!), so I'm not 100% sure if this was the intended meaning. Maybe someone who knows more about MIR could check this?
> Clarify section on MIR construction

- src/building/prerequisites.md
> Update prerequisites, with an eye towards windows

- src/queries/profiling.md
Some small things that I've went through meanwhile reading some stuff.
> Small improvements

- src/the-parser.md
This seemed to be out of date!
> Improve link and description of entry points in parser section

- src/SUMMARY.md
- src/contributing.md
- src/rustbot.md
> Add a chapter on useful `@rustbot` commands

- src/tests/adding.md
Closes https://github.com/rust-lang/rustc-dev-guide/issues/854.
r? @pickfire
> Document edition flag for UI tests

- .travis.yml
0.4.1 -> 0.4.3
Looking at the changelog, it looks like only minor changes and improvements.
> Bump mdbook version

- src/SUMMARY.md
- src/appendix/background.md
- src/mir/index.md
Adds a new graphical representation of one of the examples of MIR and
basic blocks!
And makes some other minor improvements.
r? @oli-obk
> Improve MIR sections in appendix

- src/tests/running.md
Thought of this while reading https://internals.rust-lang.org/t/contributing-changes-to-std/12829/.
> Don't recommend building the compiler for running tests on the standard library

- src/contributing.md
> correct output path in Writing Documentation

- src/getting-started.md
cc @camelid @Dylan-DPC
Closes #837.
> Add a paragraph about reviewers and review latency in Getting Started chapter

- src/appendix/glossary.md
> Added description of word Scrutinee to the glossary

- src/diagnostics.md
I had to grep through code to find out how to do this today, so I thought this could be written down here.
> Explain lint renaming/removing

- src/implementing_new_features.md
correct `a lots` to `a lot` on implementing_new_features.md
> correct minor grammar mistake

- examples/rustc-driver-interacting-with-the-ast.rs
- Make it compile
- Update documentation on components
- Add example of using ast::Crate
r? @spastorino
> Add some more examples of using the compiler

- src/mir/dataflow.md
> Add a section on data-flow convergence

- src/git.md
r? @lokathor
I finally got around to writing this up, it only took me 2 months :sweat_smile:
> Add information about common git issues

- src/rustbot.md
'rustbot modify labels: ...' -> 'rustbot label ...'
> Use shorter 'rustbot label' command

- src/contributing.md
Fixes #995 
Thanks @lnicola for noticing the link!
> Fix broken link in the contributing guide

- src/building/bootstrapping.md
> Clarify that `check` uses a different stage than `build`

- src/queries/query-evaluation-model-in-detail.md
> Tweak wording around provider purity

- src/mir/index.md
> Add link to promotion.md

- src/git.md
The text doesn't show up because of the angle brackets.
> Make "URL" show up

- src/query.md
> Fix broken links in query.md

- src/git.md
I guess like any other is what the writer was trying to say. cc @jyn514
> Complete unfinished statement

- src/rustdoc.md
> Fix rustdocs test command typo

- src/building/suggested.md
Cc https://github.com/rust-analyzer/rust-analyzer/issues/8667 @matklad
> more RA config suggestions

- .github/workflows/ci.yml
- .github/workflows/date-check.yml
- README.md
- ci/linkcheck.sh
> Some tweaks for GHA

- src/building/prerequisites.md
See: https://github.com/rust-lang/rustc-dev-guide/blob/master/src/getting-started.md#system-requirements
> Unified CPU Requirements

- src/thir.md
This flag is useful for debugging the THIR.
> Document -Zunpretty=thir-tree

- src/miri.md
> explain Miri engine vs Miri-the-tool

- src/salsa.md
> Spelling change intermidiate to intermediate

- src/SUMMARY.md
- src/constants.md
link to it in the toc and fix the new feature gates
> const generics update

- src/about-this-guide.md
PR fixes a sentence in `about-this-guide.md` to start sentence with a captial letter.
> tiny capitalization fix

- src/compiletest.md
- src/tests/adding.md
These test suites don't exist anymore.
> Remove some legacy test suites.

- src/appendix/humorust.md
update for: https://github.com/rust-lang/rust/pull/91476/files
> Update humor docs for special-casing ferris emoji

- src/building/prerequisites.md
Fixes #1278.
The section was removed in #1030 and re-added in a different place in
2d42cf7.
> Update link to moved section

- src/diagnostics.md
Just a simple addition, like the title says.
I hope that everyone reading this is having a great day. Keep up the good work :upside_down_face:
> Add example how lints can be feature gated

- src/building/bootstrapping.md
> Fix format

- src/queries/incremental-compilation-in-detail.md
> Fix some wording on the "Incremental Compilation In Detail" page

- src/overview.md
I think this PR could slightly improve the readability of the paragraph.
> Add an "is" and rearange "We next" to "Next, we"

- src/salsa.md
This removes an unnecessary "is" and moves some commas.
> Few readability fixes

- src/building/suggested.md
> Change the old filename, "src/stage0.txt" to "src/stage0.json"

- src/profiling.md
> update date reference on MIR inliner

- src/backend/backend-agnostic.md
> date triage: backend/backend-agnostic.md

- src/git.md
> Update the date reference around Git submodule bug

- src/diagnostics/diagnostic-structs.md
This (incorrect) line cost me an hour of confusion in https://github.com/rust-lang/rust/pull/100730. 😝
> Fix incorrect #[note] syntax

- book.toml
> fix quick-edit link

- src/test-implementation.md
- src/the-parser.md
Noticed it while checking https://github.com/rust-lang/rustc-dev-guide/issues/1451 and https://github.com/rust-lang/rustc-dev-guide/actions/runs/2944001680.
> Remove some dangling links

- src/implementing_new_features.md
[A discussion on zulip](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/-Zinline-llvm/near/297903037) led pnkfelix to conclude that it would be good to publicize MCP's a bit more.
> Link from "implementing to new features" to mcp.md

- src/opaque-types-impl-trait-inference.md
> Fix some typos

- .github/workflows/ci.yml
- .github/workflows/date-check.yml
I recommend reviewing commit by commit. Regarding mdbook changes, it seems fine on my local.
> Refine GHA config

- src/rustdoc.md
Sorry if this being really minor is a bad thing, but I noticed it and thought I might as well suggest the edit
> fix typo and make paragraph consistent

- src/tests/ui.md
Source: https://github.com/rust-lang/rust/pull/103014#issuecomment-1280003635
cc @Mark-Simulacrum
> Add note for err annotation formatting

- src/traits/resolution.md
> trans -> codegen

- src/building/how-to-build-and-run.md
- src/building/suggested.md
cc https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/x.2Epy.20--keep-stage-rustc.20N.20.28a.20.22smarter.22.20ke.E2.80.A6.20compiler-team.23571
> Link directly to the section on `--keep-stage`

- src/diagnostics/lintstore.md
Removing outdated paragraph that was improved in #1429
> Remove duplicate paragraph

- src/asm.md
> Update asm.md 

- src/contributing.md
> bumpt date-check examples to current month

- src/llvm-coverage-instrumentation.md
Removed in https://github.com/rust-lang/rust/pull/106625
(part of #1539)
> version 5 is now not supported

- src/ast-validation.md
Fixes https://github.com/rust-lang/rustc-dev-guide/issues/656
> Create a chapter for AST validation

- src/backend/monomorph.md
Fixes https://github.com/rust-lang/rustc-dev-guide/issues/1584
> Fixed small grammar mistake in monomorph.md

- src/git.md
Found in https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/.E2.9C.94.20Tool.20needs.20merging.20when.20git.20pulling
> Improve git submodule help

- src/crates-io.md
> Vetting deps datecheck

- src/getting-started.md
Just a tiny fix, otherwise the link works but all the styles fail to load
> Fix extra slash

- src/tests/headers.md
This header was added in https://github.com/rust-lang/rust/pull/110644/.
> Add unset-exec-env compiletest header.

- src/SUMMARY.md
- src/solve/proof-trees.md
> add stub for proof trees

- src/constants.md
See https://github.com/rust-lang/rust/pull/113321
> ty::ConstKind has moved

- src/getting-started.md
> Fix a bug in getting-started.md

- src/notification-groups/cleanup-crew.md
Add a post which explains how to use C-reduce with Rust in cleanup-crew.md
> Improve cleanup-crew.md with an example post

- src/about-this-guide.md
Forge is already mentioned in an item above.
> remove duplicate reference in about-this-guide.md

- src/SUMMARY.md
- src/return-position-impl-trait-in-trait.md
This is more or less the document we've created for the types team deep dive as in but I don't think it needs more work.
r? @compiler-errors
> Add RPITIT documentation

- src/SUMMARY.md
> Add link for unsize.md

- src/SUMMARY.md
As recommended at https://github.com/rust-lang/rustc-dev-guide/pull/1835#discussion_r1425277170.
> Move Editions chapter to "Contributing to Rust".

- src/diagnostics/translation.md
I did not touch parts about `Emitter` trait... perhaps someone that knows what movement went there could do a follow-up PR.
> update some of the diagnostic translations info

- src/backend/updating-llvm.md
Also, directory does not exist
> updating-llvm.md: command does not work

- src/serialization.md
These were removed in 2021.
https://github.com/rust-lang/rust/pull/85993
> Remove references to -Z ast-json and -Z ast-json-noexpand

- src/tests/ui.md
Waiting on PR https://github.com/rust-lang/rust/pull/121992 to be merged.
> Document that test names cannot contain dots

- src/SUMMARY.md
> add chapter to summary

- src/rustdoc-internals/search.md
> Add docs for sharded descriptions

- src/appendix/code-index.md
- src/const-eval.md
- src/traits/caching.md
- src/traits/resolution.md
Edit Parameter Environments's url as it has been edited in #1953
> Edit `Parameter Environments`'s url as it has been edited in #1953

- src/building/suggested.md
Followup to https://github.com/rust-lang/rust/pull/124883
> sync the stage0 filename

- src/tests/headers.md
Added in <https://github.com/rust-lang/rust/pull/126862>.
> Document `needs-symlink` directive

- src/git.md
Closes https://github.com/rust-lang/rust/issues/130737.
> Describe `.git-blame-ignore-rev`

- src/tests/headers.md
Blocked on https://github.com/rust-lang/rust/pull/129687
> Add documentation for `{{rust-src-base}}`

- src/coroutine-closures.md
> Linkify the footnotes in the async closure chapter

- src/appendix/background.md
- src/appendix/bibliography.md
- src/appendix/humorust.md
> Fix borked links

- src/borrow_check/moves_and_initialization/move_paths.md
- src/mir/dataflow.md
E.g. https://github.com/rust-lang/rust/pull/130022 and https://github.com/rust-lang/rust/pull/131481.
Fixes #2113.
> Update for recent dataflow simplifications.

- src/tests/directives.md
For https://github.com/rust-lang/rust/pull/132995.
> Document `exact-llvm-major-version` directive

- src/stability.md
Update for https://github.com/rust-lang/rust/pull/133142
> update for rustc_intrinsic_const_stable_indirect

- src/borrow_check/region_inference/closure_constraints.md
wrote this while looking into it myself, I think it's probably useful, but definitely not perfect :thinking:
> extend closure constraints section

- src/appendix/bibliography.md
See https://github.com/rust-lang/rustc-dev-guide/pull/2158
> functionality removed from codebase (part 2)

- src/tests/compiletest.md
cc @jieyouxu 
https://github.com/rust-lang/rust/pull/134629
> compiletest: Document the `--debugger` flag

- src/tests/compiletest.md
cc @jieyouxu 
https://github.com/rust-lang/rust/pull/134809
> Document `x test --no-capture`

- .github/workflows/rustc-pull.yml
This should let us know when a sync finishes, be it succesfully or with a failure.
> Send a message to Zulip when a sync finishes

- .github/workflows/rustc-pull.yml
> Fix rustc-pull CI's bash commands

- src/profiling/with_perf.md
I encountered this issue and spent extra time resolving it.
> Add note for perf issue

- .github/workflows/ci.yml
> Bump mdbook-linkcheck2 dependency version

- .github/workflows/rustc-pull.yml
I wonder when I'll get this workflow right… :laughing:
> Fix posting message to Zulip

- src/backend/updating-llvm.md
ticks 1 box in https://github.com/rust-lang/rustc-dev-guide/issues/2267
> mention llvm 20 in example prs

- README.md
See [#t-compiler/wg-rustc-dev-guide > Subtree sync automation @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/196385-t-compiler.2Fwg-rustc-dev-guide/topic/Subtree.20sync.20automation/near/505336225).
> Document `fetch.prunetags = true` gotcha during rustc-pull

- src/tests/codegen-backend-tests/intro.md
> Fix code generation link

- book.toml
See https://rust-lang.github.io/mdBook/format/configuration/general.html#general-metadata
> Update book.toml fix the authors field

- src/SUMMARY.md
- src/autodiff/installation.md
It feels prohibited, but I was told that as domain experts, contributors are allowed to merge their own PRs.
> upstream autodiff build instructions

- .github/workflows/ci.yml
This updates to the latest version of mdbook which has had a variety of fixes of new features since the last update.
Changelog: https://github.com/rust-lang/mdBook/blob/master/CHANGELOG.md#mdbook-0448
> Update mdbook to 0.4.48

- src/macro-expansion.md
See parent commit, which made them dangle
> remove dangling references

- src/tests/intro.md
The 2 commands do the same thing.
Also, follow style used elsewhere in the guide.
> avoid duplicating commands

- src/building/suggested.md
The main sections is about configuring LSP for use with the codebase, so this does not need repeating. Also, the sentence is missing some words.
> replace a broken sentence

- src/external-repos.md
https://github.com/rust-lang/stdarch/pull/1844
> Mention that stdarch is managed by josh-sync

- src/SUMMARY.md
- src/solve/candidate-preference.md
> add a chapter documenting candidate preference

- src/git.md
> place link on the more suitable text

- src/typing_parameter_envs.md
> reduce overlong physical lines (sembr)

- src/tests/ci.md
> a valid state is achieved by passing the test suite

- src/contributing.md
> name of the tool is lower case
