rust-lang/rustc-dev-guide

src/src/SUMMARY.md
src/src/glossary.md

Add glossary

---

.travis.yml
ci/github_pages.sh
ci/install.sh

This should set up travis so it'll rebuild the `rustc-guide` whenever there's a commit to master. Unfortunately, I'm not a contributor on this repo so I can't add it to `travis.yml`.
Once we enable travis it may take a couple extra commits to make sure everything is working as desired.
(fixes #1)

Set up the basic CI infrastructure

---

.travis.yml
ci/install.sh

cc @Michael-F-Bryan -- does this look right? 
(I'm also not sure what the `~/.cargo/env` command does, but it seemed likely it might be needed to run cargo, so I moved it up)

invoke `cargo` to install mdbook

---

src/hir-lowering.md

Literally just copy-pasting (s/README/chapter/) @nikomatsakis's README from librustc.
Not sure if it's worth landing this as-is or if we should wait until I've added some more content.

Copy contents of README.md from librustc/hir

---

src/how-to-build-and-run.md

Fixes https://github.com/rust-lang-nursery/rustc-guide/issues/8

how to build and run compiler, first shot

---

src/the-parser.md

This is the first instalment towards #13. I'm planning to do a quick high-level overview of the parser and `libsyntax` and mentioning the major players (`Parser`, `ParseSess`, etc) and what they do.

WIP: Started working on the Parser

---

src/name-resolution.md

The first attempt to write something useful about the name resolution.
As the TODO section says, his is not finished thing, but it might
hopefully be useful to someone already.
This is part of #16, but this wouldn't be complete enough to call that one done. My next plan is to do a more thorough read through the code than just a fast scan, annotating the undocumented items with comments (what is the convention, is it OK to put doc comments on private items?) and then try to improve this.
Apart from the possible usefulness for others, I already wrote this incomplete thing to make sure I don't forget what I've already learned ‒ I don't know when I'll have the time to do another pass (which will take longer than the first scan).
Few questions:
* Should this go into master in the current form, …

The first approximation of name resolution

---

src/how-to-build-and-run.md

Could somebody please confirm that this is accurate info?
Fix #32

Add a paragraph about bootstrapping

---

src/glossary.md

The DAG is mentioned on the [incremental compilation](https://rust-lang-nursery.github.io/rustc-guide/incremental-compilation.html#the-basic-algorithm) page, I guess it makes sense to have it in the glossary, too?

Add DAG to glossary

---

src/glossary.md

Add soundness and completeness to glossary

---

src/SUMMARY.md
src/conventions.md
src/how-to-build-and-run.md
src/running-tests.md
src/tests/adding.md
src/tests/intro.md
src/tests/running.md

cc #10
This content is *mostly* taken from the `COMPILER_TESTS.md` in the compiler source tree, but I added some more notes.

document the test infrastructure

---

.travis.yml

The newer version of mdBook uses a different path for the html output.

Fix Github Pages path.

---

src/SUMMARY.md
src/compiletest.md

describe the steps required to add a test and a header command to compiletest

created compiletest.md

---

src/SUMMARY.md
src/const-eval.md
src/glossary.md
src/miri.md
src/param_env.md
src/trait-resolution.md

Add some documentation for const eval and related topics

---

src/tests/intro.md
src/tests/running.md

Add some more information about the various tests that get run.

---

src/glossary.md

Add a few more terms to the glossary

---

src/tests/intro.md

CC #10
I'm not sure if this is useful, but it is a start for documenting testing on different platforms.  Maybe someone else can help answer the questions I left behind?

Start documentation for test infrastructure.

---

src/glossary.md

cc #48 
EDIT: also remove duplicate MIR def...

Add some codegen related terminology to glossary

---

src/name-resolution.md

Hello
I found a bit of more time for the name resolution (#16) and put some more stuff there.
However, I'm afraid the whole chapter is above my abilities (or time, at least) to document reasonably ‒ I'm reading through the code and still don't understand most of it and have no idea about which part of code relates to the other bullet points in the issue description. Therefore, if there's someone else who might want to have a look at it, I'd like to release the lock on the task and I'll find some other way to contribute to rust (pull requests to random crates I use seem to have better cost-effect ratio for me).

Second pass of name resolution

---

src/SUMMARY.md
src/appendix-background.md
src/appendix-code-index.md
src/appendix-glossary.md
src/appendix-stupid-stats.md
src/mir-borrowck.md
src/mir-regionck.md
src/mir.md
src/rustc-driver.md
src/traits-canonicalization.md

I've started working on a `rustc-driver` chapter. 
It's still very early days and I've written it as someone with experience instrumenting `rustc` from the outside so I don't know if it'll flow with the other chapters, so feedback, comments, and criticism are most welcome! :grin: 
The basic points covered are:
- What is it? glue code/the compiler's `main()` function
- What phases does it go through?
- At which points in the compilation process can I inspect the compiler's state, and what can I see
I also want to add something like @nrc's https://github.com/nrc/stupid-stats (which is awesome btw, thanks @nrc!) as an appendix for future explorers. If it's fine with him, I might end up copying most of it across and update it to take into account any changes to the compiler since the tutorial …

Rustc Driver Chapter

---

src/SUMMARY.md
src/appendix-background.md
src/appendix-code-index.md
src/appendix-glossary.md
src/method-lookup.md
src/type-checking.md
src/variance.md

cc #2 
This is pretty much a straight copy the READMEs from `librustc_typeck`, which can be removed after this is merged.

Add the contents of the typeck READMEs

---

src/SUMMARY.md
src/appendix-code-index.md
src/rustdoc.md

cc @QuietMisdreavus @Michael-F-Bryan 
After this merges, I hope to remove the README from librustdoc so that we can have everything in one place.

Add the rustdoc readme

---

src/traits-lowering-rules.md

This allows cross-references from the code.

add names to the trait lowering rules

---

src/SUMMARY.md
src/traits-lowering-module.md

describe how the lowering code works

---

ci/install.sh

bump mdbook to 0.1.5

---

book.toml
ci/install.sh

May want to wait for 0.1.6 to be released since there is a minor CSS issue, but I thought this was nifty!

Add mdbook search.

---

src/trait-caching.md
src/traits-associated-types.md
src/type-inference.md

Minor grammar and syntax fixes found while reading.

Minor grammar and syntax fixes

---

src/appendix-stupid-stats.md
src/const-eval.md
src/method-lookup.md
src/miri.md
src/type-checking.md

This PR is for issue https://github.com/rust-lang-nursery/rustc-guide/issues/100 for private documentation.
@mark-i-m  @Michael-F-Bryan @nikomatsakis 
Please hold merging as there are still some items are not found in documentation.

[WIP] update nightly documentation for issue#100-b

---

src/tests/adding.md

I just learned that there's a counterpart to `ignore-X` called `only-X` which was really helpful for a test i needed to write.

talk about `only-X` in compiletest

---

src/tests/adding.md

Rename `must-compile-successfully` to `compile-pass` in ui test doc as per https://github.com/rust-lang/rust/issues/49568.

Update header commands in adding.md

---

src/appendix-background.md
src/conventions.md
src/incremental-compilation.md
src/mir-regionck.md
src/mir.md
src/tests/adding.md
src/traits-associated-types.md
src/traits-bibliography.md
src/traits-canonical-queries.md
src/traits-goals-and-clauses.md
src/traits-lowering-module.md
src/traits-lowering-rules.md
src/type-inference.md
src/variance.md

This tag is extra and must have been added mistakenly. Results in the entire rest of the page getting underlined on mouse over for no reason.

Deleted <a> tag which was messing up the associated types page

---

src/compiletest.md

mdBook doesn't display links inside code, so these links look very confusing.
Additionally, these types of links don't seem to be code on other pages of the book.

Make chapter links in compiletest not be code

---

src/type-inference.md

This should make the chapter a bit more approachable, as it doesn't
start out with a reference to the HM type inference algorithm.

Add type inference example

---

src/trait-resolution.md
src/traits-goals-and-clauses.md
src/traits-lowering-rules.md

I felt the introduction to domain goals would be gentler with some examples and a brief discussion of each. Feedback wanted!

Explain what each domain goal means

---

src/tests/adding.md

Fixes #141

---

src/traits-associated-types.md
src/traits-lowering-rules.md

Add the lowering rules from https://github.com/rust-lang-nursery/chalk/issues/12#issuecomment-377258347 that were added to Chalk in https://github.com/rust-lang-nursery/chalk/pull/134/.
cc #137, @scalexm, @nikomatsakis

Add lowering rules for GATs

---

src/tests/intro.md

closes #10
r? @Mark-Simulacrum

Add a bit about crater

---

src/appendix/glossary.md

add a bunch of type-related terms to glossary (and few others)

---

src/traits/lowering-rules.md

Small sub section about `WellFormed` and `FromEnv` predicates for types.

Add chalk rules for type defs

---

src/rustdoc.md

(updating a link, and making commands more literally copy-pasteable)

proposed copy edits to rustdoc chapter

---

src/high-level-overview.md
src/query.md

For https://github.com/rust-lang/rust/pull/51550.

rustc: rename ty::maps to ty::query.

---

src/SUMMARY.md
src/high-level-overview.md
src/hir.md
src/lowering.md
src/name-resolution.md

Add some explanation of lowering

---

src/SUMMARY.md
src/codegen.md
src/compiler-debugging.md

Augment notes one LLVM IR debugging

---

src/tests/adding.md

Update the compiler test documentation to document ignore-gdb-version
and min-system-llvm-version; and expand the min-gdb-version,
min-lldb-version, and min-llvm-version documentation a little.

Update compiler test documentation

---

src/compiletest.md
src/conventions.md
src/tests/adding.md

Previously approved in https://github.com/rust-lang/rust/pull/43498 ;
update the guide to match.

Update copyright guidance to omit notices for new files.

---

src/hir.md

sprinkle links to rustdoc through the HIR explanation

---

src/tests/running.md

The `--incremental` flag was only briefly mentioned in [how_to_build_and_run.html][how_to_build_and_run]
so far. Faster testing means faster iteration, happy contributors and perhaps even
more added tests.
[how_to_build_and_run]: https://rust-lang-nursery.github.io/rustc-guide/how-to-build-and-run.html

Mention incremental compilation in testing chapter

---

src/how-to-build-and-run.md
src/tests/running.md

This documents the `--keep-stage 1` workflow (thanks @Mark-Simulacrum !) and tries to clarify a bit how staging works.
cc @sunjay -- the new language is intended to clear up some of the confusion you had around why building `--stage 1 src/libstd` does more than build the standard library. What do you think?

document keep-stage1 and also try to clarify

---

README.md
book.toml
ci/install.sh
src/appendix/background.md
src/appendix/code-index.md
src/appendix/glossary.md
src/appendix/stupid-stats.md
src/borrow_check/region_inference.md
src/const-eval.md
src/diag.md
src/mir/index.md
src/mir/passes.md
src/miri.md
src/profiling/with_perf.md
src/tests/intro.md
src/traits/associated-types.md
src/traits/caching.md
src/traits/canonical-queries.md
src/traits/canonicalization.md
src/traits/chalk-overview.md
src/traits/goals-and-clauses.md
src/traits/index.md
src/traits/lowering-module.md
src/traits/lowering-rules.md
src/traits/lowering-to-logic.md
src/traits/resolution.md

fixes #172, fixes #109
Dropped travis caches...
Currently it looks like linkcheck is passing despite broken links?
r? @Michael-F-Bryan

Update to mdbook 0.2

---

src/traits/associated-types.md
src/traits/goals-and-clauses.md
src/traits/index.md
src/traits/lowering-rules.md

I updated a bit the lowering-to-logic chapters. In particular, I changed the name of two logical rules: I'll adjust documentation accordingly in rustc and chalk. The implied bounds chapter still needs to be written (which I'm currently doing).

Polish lowering chapters and update rules

---

src/compiler-documenting.md
src/how-to-build-and-run.md

@mark-i-m updated the rustc documentation location as discussed in https://github.com/rust-lang-nursery/rustc-guide/issues/100#issuecomment-431906066
Please review and let me know your comments

issue_100_4 Updated the rustc documentation location

---

src/traits/wf.md

This covers types, traits and trait impls.
cc @nikomatsakis @tmandry

Write well-formedness checking chapter

---

src/tests/adding.md

This documents the ignore-llvm-version directive.

Document ignore-llvm-version

---

src/how-to-build-and-run.md

I revised a jemalloc statement concerned with creating config.toml.

revised a jemalloc statement in how-to-build-and-run.md

---

src/mir/index.md

Fixed Spelling Mistake In MIR/index.md - "alloated"

---

src/traits/slg.md

This is mostly just an adapted version of Niko's blog post.
From here we need to add a subsection on negative reasoning, and possibly one on how the solver handles regions. Also one on using the solver via the `Context` and related traits.
cc @nikomatsakis @scalexm

Add traits SLG solver section

---

README.md
src/about-this-guide.md
src/diag.md

The `issues` link in the root has linkrotted since this is no longer `rust-lang-nursery`, just updating it.
I also found another two links that aren't quite right but still redirect correctly:
`rls` in `src/diag.md` - rls has also moved out of nursery
`Github repository` in `src/about-this-guide.md` - that's a link to this repo but under `rust-lang-nursery`
Should I update those links as well? I'm not sure if github redirects remain valid forever and I don't want to go just changing stuff around willy nilly

fix issues link

---

src/tests/running.md

As mentioned here:
https://github.com/rust-lang/rust/issues/52452#issuecomment-440354255
It would be good is the rust compiler guide mentioned that the compiler tests need gdb with Python support.
Are there any other test dependencies that we should mention? If there are a few, perhaps we'd even want a subsection listing them.
Thanks

Mention that tests need a Python-enabled gdb.

---

src/mir/construction.md

It currently looks like the following:
(in [https://doc.rust-lang.org/nightly/nightly-rustc/rustc_mir/hair/cx/expr/index.html])
This makes it look like:
(in [rustc_mir::hair::cx::expr])
[rustc_mir::hair::cx::expr]: https://doc.rust-lang.org/nightly/nightly-rustc/rustc_mir/hair/cx/expr/index.html

Fix link to rustc_mir::hair::cx::expr

---

src/how-to-build-and-run.md

My editor also removed some trailing whitespace, sorry about that. I can do this again without that if needed. 
In my first commit I accidentally did nothing, but the fact that my editor removed whitespace tricked me into believing I had added the clarification.
My second commit, "Do what the last commit said it did," actually does what it should.

Clarify line about RLS being unable to handle rustc

---

src/incremental-compilation.md

That's the first document that I stumbled upon, which actually explained what _red/green_ mean and what is the red/green algorithm (except for this doc).
Does it make sense to include that? I liked the graphs, more high-level overview and the motivation, but wouldn't like to post links to something that might be obsolete by now.
r? @nikomatsakis

Mention old incr. comp. design doc

---

src/SUMMARY.md
src/stabilization_guide.md
src/walkthrough.md

@mark-i-m @pietroalbini This PR addresses [Stabilization guide] of issue https://github.com/rust-lang/rustc-guide/issues/133.
Please review and let me know your feedback.

issue_130_stabilization_guide

---

src/compiler-debugging.md

> `debug!` are removed by default
old: https://github.com/rust-lang/rust/blob/90346eae18e83887517e096c17678a74838ff995/src/liblog/macros.rs#L163-L166
new: https://github.com/rust-lang-nursery/log/blob/433731637477b27f573a3e40cd2297c5a776ff1b/src/macros.rs#L136-L144
I can't find conditional compilation that will remove `debug!`, only find runtime `cfg!(debug_assertions)` check in the old liblog, maybe I need to dig into the more distant history.
> expressions *within* the `debug!` call are run whenever RUST_LOG is set, even if the filter would exclude the log
https://github.com/rust-lang-nursery/log/blob/433731637477b27f573a3e40cd2297c5a776ff1b/src/macros.rs#L36-L41
It seems RUST_LOG's presence alone does not make a difference, it's the value that matters
> expressions are *evaluated* even …

Remove outdated doc that no longer holds true

---

src/SUMMARY.md
src/about-this-guide.md
src/part-1-intro.md
src/part-2-intro.md

The guide is quite long and contains _tons_ of useful info, but it at the moment, it lacks flow IMHO.
I propose we organize the guide as two parts: (1) Useful info for contributing, and (2) How the compiler works.
(1) is where we would move general knowledge chapters like "about the compiler team", "building", "debugging", "stabilization process", etc. This section would serve as a reference for stuff that is useful regardless of what you are working on.
(2) is where everything else would live. This section is about how the compiler works.
r? @nikomatsakis

Reorganize the book into 3 parts

---

src/diag.md

The simpler `span_suggestion` method name now takes the applicability argument, thanks to @euclio (rust-lang/rust@0897ffc28f6).

`_with_applicability` methods are gone

---

src/SUMMARY.md
src/kinds.md
src/ty.md

This chapter briefly describes the use of `Kind`, `UnpackedKind` and `Subst`.
This has been delayed long enough that I think it's worth getting *something* in the guide, just to provide some explanation. We can always extend this in the future with more examples.
Fixes https://github.com/rust-lang/rustc-guide/issues/97.

Add a (short) chapter on `Kind`

---

src/SUMMARY.md
src/conventions.md
src/crates-io.md

Update Conventions chapters, add chapter on dependencies

---

src/compiler-team.md

@nikomatsakis @davidtwco added a section to link the experts map.

Add experts map section to compiler team page

---

src/codegen.md

The debugging LLVM page was moved into the Code Generation section

Update link to debugging codegen

---

src/compiler-debugging.md

r? @eddyb since they made the suggestion in https://github.com/rust-lang/rustc-guide/issues/11#issuecomment-463398054

Emphasize use of most specific module for RUST_LOG

---

src/query.md

There was a big macro rewrite in these pull requests:
https://github.com/rust-lang/rust/pull/56462
https://github.com/rust-lang/rust/pull/59517
Update the query chapter to describe the new macro usage.
@Zoxc it would be nice if you could review this.

Update query chapter for the query macro rewrite

---

src/test-implementation.md

`test_main_static` is now used instead of `test_static_main`.
The libsyntax no longer generates a `TESTS` constant but rather passes all test cases directly into `test_main_static` as a slice.
Update the guide accordingly.

Update test-implementation chapter to current code

---

src/hir.md

It is now a newtype'd HirId, not NodeId.
See https://github.com/rust-lang/rust/pull/58167.

Update BodyId description

---

src/compiler-debugging.md

Explain new powers of the `treat-err-as-bug` flag

---

src/traits/lowering-rules.md
src/traits/wf.md

Fixed some links broken by https://github.com/rust-lang/chalk/pull/215/

Broken chalk links

---

src/walkthrough.md

It seems there is a missing link to the  stabilization report in the [current walkthrough document](https://rust-lang.github.io/rustc-guide/walkthrough.html), near the very end of the page. 
I looked for the stabilization PR mentioned and I believe I found the right one. I linked it in the Markdown file.

Fix link in walkthrough

---

src/how-to-build-and-run.md

As mentioned in the comments of #301

Added mention of universal ctags

---

src/compiler-debugging.md

https://github.com/rust-lang/rust/pull/60401 was merged, so we should also rename this guide's wording.

Rename to RUSTC_LOG

---

src/how-to-build-and-run.md
src/tests/running.md

Adds documentation for https://github.com/rust-lang/rust/pull/60719 to the rustc-guide.

Mention running tests for subdirectories

---

src/SUMMARY.md
src/appendix/code-index.md
src/diagnostics.md
src/implementing_new_features.md

When I recently searched for infos in this guide on how to create a warning, I couldn't find any. Later I found it through #14.
The reason was that I didn't know the term 'diagnostics' and that it is the collective term for errors, warnings and lints.
Renaming the chapter to include the word 'error' should help. I think also including 'warning' in the title shouldn't be neccessary, because it's close enough.

Renamed the file and title of the diagnostics chapter.

---

src/about-this-guide.md

Add more info subsection with links to forge and rustc api docs

---

src/compiler-debugging.md
src/how-to-build-and-run.md
src/profiling/with_perf.md

Fixes https://github.com/rust-lang/rustc-guide/issues/327

Update information about debuginfo configuration

---

src/compiler-debugging.md
src/how-to-build-and-run.md

r? @spastorino 
I'm not really sure what github is doing but it made me open another PR...

Debuginfo level

---

src/appendix/code-index.md
src/appendix/glossary.md
src/compiler-debugging.md
src/conventions.md
src/mir/visitor.md
src/profiling/with_perf.md
src/query.md
src/ty.md
src/type-inference.md

See https://github.com/rust-lang/rust/pull/61722 and https://github.com/rust-lang/rust/pull/61817 for some backstory.
cc @mark-i-m @rust-lang/compiler

Update for TyCtxt<'a, 'gcx, 'tcx> -> TyCtxt<'tcx>.

---

src/SUMMARY.md
src/debugging-support-in-rustc.md

This is still work-in-progress but I wanted to open a PR for an early review to see if I am on the right path (also suggested by @spastorino).
This document is built on top of https://www.youtube.com/watch?v=elBxMRSNYr4 by @tromey.
For the sake of simplicity, I have added this document at the top level. Please advise if this should be under a directory or group of docs.
This issue has been assigned to @amanjeev via [this comment](https://github.com/rust-lang/rustc-guide/pull/316#issuecomment-501476525).

Debugging support in rustc

---

src/tests/adding.md

Update pass modes for ui tests

---

src/SUMMARY.md
src/appendix/humorust.md

Add humor appendix

---

book.toml

I think for now, the proper policy to follow is to blacklist links that fail often, especially when they are unlikely to change often.
We may also want to include a warning about unchecked links... or we could just let people find them for us...
cc #385 #249

Blacklist some commonly problematic links

---

src/tests/running.md

Document `--pass $mode`

---

.travis.yml
ci/build-ignore-timeouts.sh

r? @spastorino 
Basically we check if the error message is for a timeout ("error while fetching ...") and if all of the errors are timeouts we just pass. This extremely brittle, but it should work until we figure out something better...

Hack around timeouts

---

src/traits/bibliography.md

This link caused the most recent cron failure. It doesn't seem to provide any useful information, so I removed it.

Remove flaky link

---

src/profiling.md

Add mentions and links to `rustc-perf` and `measureme`.

Improve "Profiling the compiler" docs

---

src/stability.md

These comments seem to have been lost in https://github.com/rust-lang/rustc-guide/pull/424.
On another note, should the "stabilization" page link to the "stability attribute" one? I couldn't find a good place to add that link, though.

mention stable-in-unstable issue

---

src/query.md

I'm not sure why the link checker didn't catch this...
There are a couple of other broken links I've not touched too:
```
error: Unable to retrieve "https://public.etherpad-mozilla.org/p/rust-compiler-meeting": https://public.e
therpad-mozilla.org/p/rust-compiler-meeting: error trying to connect: Connection refused (os error 111)
- compiler-team.md:32:1                                                                                 
|                                                                                                    
32 | [the rust-compiler-meeting etherpad][etherpad]. It works roughly as                                
|                                                                                                    
```
^ Genuinely a dead link.
```
error: Unable to …
```

Fix a link in the query docs.

---

.travis.yml
ci/install.sh

I recently rewrote large chunks of `mdbook-linkcheck` to take advantage of caching and parallelism, and thought you might want to take advantage of it for CI.
I'm not sure how this would interact with [these lines](https://github.com/rust-lang/rustc-guide/blob/78b63d19e57cfe3b309d6bf394640dfc193f403e/ci/build-ignore-timeouts.sh#L14-L15) in the `build-ignore-timeouts.sh` script, though.

Updated the mdbook-linkcheck version

---

.travis.yml
book.toml
ci/build-ignore-timeouts.sh
src/SUMMARY.md

hack + drive-by-fix

---

src/mir/construction.md
src/mir/passes.md
src/test-implementation.md

Found and fixed some minor typos in the rustc-guide. Thank you.

minor typo fixes

---

src/codegen/updating-llvm.md

Make sure existing sections are up-to-date and then also add some words
about the recent convention we developed for updating LLVM versions with
respect to branch naming as well.

Update the "Updating LLVM" documentation

---

src/appendix/bibliography.md
src/borrow_check.md
src/borrow_check/region_inference.md
src/mir/index.md
src/traits/chalk-overview.md
src/traits/slg.md

Find and replace with:
```bash
git grep -l 'http://.*\.github\.io' | xargs sed -E -i 's@http://(.*\.github\.io)@https://\1@g'
```

Prefer https in GitHub pages urls

---

src/tests/adding.md

...and encourage compiler devs to better organize the tests.

Emphasise that issues/issue-12345.rs is an anti-pattern

---

src/implementing_new_features.md

This is what we actually do these days.

Update feature gating docs to fit reality

---

src/SUMMARY.md
src/codegen/debugging.md
src/ice-breaker/about.md
src/ice-breaker/llvm.md

create guide to ICE-breaker groups and specifically advice for LLVM

---

src/stability.md

@Centril requested some extra documentation on stability (https://github.com/rust-lang/rust/pull/64882#discussion_r332688034), so here it is.  Along the way I added some related things that seemed like it would be good to document. I am not an expert on these things, but they seem mostly correct.

Expand on stability documentation.

---

src/macro-expansion.md

The text didn't match the actual link (or source path).

Fix some paths: tt -> mbe

---

src/implementing_new_features.md

Also...
- fix path to active.rs
- use example of something not yet stabilized

format examples better

---

src/diagnostics.md

Extracted from the unstable book since it needs to be removed from there.
Doing this as part of https://github.com/rust-lang/rust/pull/65794.

Explain `rustc_on_unimplemented`

---

src/SUMMARY.md
src/diagnostics.md
src/diagnostics/lintstore.md

r? (?) @nikomatsakis 
This accompanies https://github.com/rust-lang/rust/pull/65193. I would appreciate thoughts as to _what_ we should be documenting (and how) -- once we figure things out here I'll also delete https://forge.rust-lang.org/compiler/bug-fix-procedure.html#issuing-future-compatibility-warnings as I believe it's subsumed by the documentation in rustc-guide.

Add some docs around the lint store

---

src/diagnostics/lintstore.md

Fixes post-merge comments on  https://github.com/rust-lang/rustc-guide/pull/476

Fixup links in lintstore docs

---

src/implementing_new_features.md

Removed link to Forge instructions for documentation since they no longer seem to exist.

Updated instructions for tracking issue

---

book.toml

This makes the sidebar much shorter and more readable by default. One can still see the subchapters by clicking the little arrow to unfold the chapter.

Fold subchapters

---

src/rustc-driver.md

rustc_interface::interface::run_compiler 
(https://doc.rust-lang.org/nightly/nightly-rustc/rustc_interface/interface/fn.run_compiler.html)

Clarify function name and add links

---

src/tests/intro.md

The testing infrastructure was migrated from Travis and AppVeyor to
Azure Pipelines some time ago. This commit updates the documentation to
reflect this change.
Fixes #500.

Update the "Testing infrastructure" section

---

src/compiler-debugging.md

This description
backtraces **don't work** on Mac and on MinGW
seems outdated. Just checked and it works.

Fix: backtraces do work on Mac

---

src/appendix/background.md

Add compilers bibliography

---

src/building/how-to-build-and-run.md
src/diagnostics.md
src/hir.md
src/profiling/with_perf.md
src/tests/running.md

This makes copying inconvenient as `> ./x.py build -i --stage 1 src/libstd` will actually render your `x.py` file empty...

Don't include ">" in bash scripts

---

src/borrow_check.md
src/borrow_check/region_inference.md
src/borrow_check/region_inference/constraint_propagation.md
src/borrow_check/region_inference/lifetime_parameters.md
src/borrow_check/type_check.md

cc https://github.com/rust-lang/rust/pull/66886 https://github.com/rust-lang/rust/pull/66815

Update NLL links after refactorings

---

src/diagnostics.md

Right now the documentation states it lives under "libsyntax" but this is not true anymore, it can be found with the human readable emitter under "librustc_errors"
Closes #537

Old information where JSON error emitter can be found

---

src/building/bootstrapping.md

cc #436 @pnkfelix @nikomatsakis @Mark-Simulacrum  https://github.com/rust-lang/rust/issues/38686
From: https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/env.20vars.20and.20x.2Epy.20.2338686

Document rustc internal env vars a little bit

---

src/stability.md

See https://github.com/rust-lang/rust/pull/67480

Update stability documentation, mention `issue = "none"`

---

src/stability.md

Introduce `rustc_const_stable` and explain `rustc_const_unstable`

---

src/hir.md

Moved from the `ty::Ty` chapter PR...
cc @spastorino

Add a bit about def path

---

src/SUMMARY.md
src/panic-implementation.md

This PR adds a descirption of the implementation of panicking in Rust, starting from the `panic!` macros and ending at the invocation of the platforms-specific unwind logic.
This is not fully complete - for one thing, it might be useful to have a description of how this works under Miri.
I developed this while working on the implementation of panics in Miri. Having this document available would have made things a lot easier for me :smile: 
Closes #486

[WIP] Add panic implementation docs

---

src/ty.md

This is coming out as part of the effort from the @rust-lang/wg-learning working group :tada: :tada: :tada:.
As currently is I have two comments that may worth fixing:
1. This probably needs a very deep review in the way things are located and explained. I may have messed some stuff after adding a lot of content and after merging with what the guide already had. Right now I need a little break from this, maybe when I come back I will realize all my mistakes :smile: 
2. There are probably a lot of style mistakes, this was just exported from Paper.
This may be better fixed using this [link](https://hackmd.io/gwqG8yppTjWPd_uteyWLjw), then I can place the fixes into the PR.
Closes #375

Summarize the lecture of ty into a chapter

---

src/appendix/code-index.md
src/hir.md
src/rustdoc.md
src/ty.md

Some `rustc::hir` items have been moved to `rustc_hir`.

Fix links and paths

---

src/SUMMARY.md
src/ice-breaker/cleanup-crew.md

First draft of describing the "cleanup crew" ICE-breakers team.

add cleanup crew

---

src/implementing_new_features.md

In the *Implementing new features* chapter, we are shown the syntax for the declaration of a feature in the `declare_features` block:
```rust
// description of feature
(active, $feature_name, "$current_nightly_version", Some($tracking_issue_number), $edition)
```
The description in this code is written in a "plain" comment. However, in the [`librustc_feature/active.rs`][active] file, features are documented using documentation comments instead of "plain" comments. As the snippet is probably meant for copy-pasting, I thought this small detail might need to be fixed.
[active]: https://github.com/rust-lang/rust/blob/master/src/librustc_feature/active.rs

Mark feature description comment as a doc comment

---

src/mir/index.md

This is the companion to https://github.com/rust-lang/rust/pull/56231, which added these separate debuginfo annotations.
I tried to stick in as much information as I could, but the example does not help me - compare its single `scope 1` (with only a `debug` inside, no `let`s), with the example in https://github.com/rust-lang/rust/pull/56231.
r? @nikomatsakis cc @rust-lang/wg-mir-opt

mir: begin documenting user variable debuginfo.

---

src/borrow_check/region_inference/constraint_propagation.md

`ConstraintSet` => `OutlivesConstraintSet`

Correction of type name

---

src/SUMMARY.md
src/appendix/glossary.md
src/memory.md
src/rustc-driver.md
src/ty.md
src/type-inference.md

as discussed in #530 and elsewhere
resolves #419

Interning chapter

---

src/name-resolution.md

I've been looking into `librustc_resolve` the past couple of days and saw that the rustc-guide could use some updates. This adds a small intro section to the name resolution chapter.

Add introductory section for name resolution chapter

---

src/traits/lowering-module.md

Chalkify tests were removed entirely in rust-lang/rust#69247 but the lower-module chapter is still reasonable to me. So just removed the references to chalkify ui tests.

Remove references to chalkify tests

---

src/conventions.md
src/diagnostics/diagnostic-codes.md
src/tests/intro.md
src/tests/running.md

We are updating the rust repository `./x.py test` docs to use the `tidy` argument in https://github.com/rust-lang/rust/pull/69603:
```
./x.py test tidy
```
This replaces the previous recommendation to use the source directory path:
```
./x.py test src/tools/tidy
```
This PR updates the rustc-dev-guide docs to use the same recommendation.

Update ./x.py tidy testing documentation

---

README.md
book.toml
src/about-this-guide.md
src/debugging-support-in-rustc.md
src/ice-breaker/llvm.md
src/implementing_new_features.md
src/macro-expansion.md
src/mir/optimizations.md
src/part-1-intro.md
src/part-2-intro.md
src/traits/chalk-overview.md

This is in preparation for https://github.com/rust-lang/rustc-guide/issues/470
Needs to be merged after we actually rename the guide.
Have used this to rename:
`git grep -l 'rustc-guide' | xargs sed -i 's/rustc-guide/rustc-dev-guide/g'`
`git grep -l 'rustc guide' | xargs sed -i 's/rustc guide/rustc dev guide/g'`

Rename rustc-guide to rustc-dev-guide

---

src/appendix/bibliography.md

The original link is 404 now, use web archive instead.

Fix broken link

---

examples/rustc-driver-example.rs
src/rustc-driver.md

It's not necessary to use rustc_interface::interface::run_compiler to get to the run_compiler function---this function is re-exported by the top-level module of the rustc_interface crate.

Simplify path rustc_interface::interface::run_compiler

---

src/appendix/stupid-stats.md

Convert rustc_codegen_utils link to rustc_codegen_ssa

---

src/SUMMARY.md
src/licenses.md

Adds Part 1 documentation of the dual Apache License v2.0 and MIT license structure of the rust-lang/rust source repository, and links to the rust-lang/rust COPYRIGHT document for more information on contributor copyrights and other licenses that apply to areas of the source. This document is placed at the end of the Part 1 ToC.

Add license documentation

---

src/SUMMARY.md
src/codegen/implicit-caller-location.md

Documenting the overall feature here as the current implementation is spread across several PRs and has deviated a good bit from the RFC.
recommended in https://github.com/rust-lang/rust/issues/47809#issuecomment-572497766

Implicit Caller Location section.

---

src/SUMMARY.md
src/rustc-driver-interacting-with-the-ast.md

I am learning rustc_interface, and I am trying to improve the docs as I go. I am eager for feedback if there's a better way to do what I am documenting here. My [first PR](https://github.com/rust-lang/rustc-dev-guide/pull/621) added a "Hello world" working example for rustc_interface.
This PR creates a new page, which will document how to do various common tasks with rustc_interface. It's less of a reference and more of a howto. The rustc_interface API surface is very large and so it's quite hard to get started---this page is designed to remedy that. 
This page will have multiple examples, but as a place to start, I am showing how to get the type of an expression. 
@mark-i-m FYI

Document how to get the type of an expression using rustc_interface

---

src/ice-breaker/about.md

I'm not sure if this is really useful, but I think the "full" invocation is really long and not convenient to learn.
Related to rust-lang/rust#69949

Change ICE-breaker ping to use the new aliases

---

src/about-this-guide.md
src/part-1-intro.md
src/part-2-intro.md
src/part-5-intro.md

This PR updates the About This Guide page with the new section titles/descriptions following the reorganization in #651.

"About This Guide" updates following Guide reorganization

---

src/debugging-support-in-rustc.md

Implementation PR in Rust: https://github.com/rust-lang/rust/pull/69718

Add section: Source file checksums in debug info

---

src/compiler-src.md

has been renamed in the compiler afaik

compiler-src: replace rustc with rustc_middle

---

src/compiler-debugging.md

I don't like the "on the `nth` error on" part but maybe someone can suggest an edit for that :).

treat-err-as-bug=n means panic on nth error

---

src/queries/profiling.md

Missing `[` from the hyperlink

Minute formatting fix

---

src/queries/incremental-compilation.md

It currently does not appear as a clickable link here https://rustc-dev-guide.rust-lang.org/queries/incremental-compilation.html
Additionally, this is a particularly long and nasty link.

Hide link behind a clickable text

---

src/traits/resolution.md

This example mentioned a method `get_it` which does not exist afaict.
This is still not optimal IMO as we get the following error when using this
outside of std.
```
error[E0119]: conflicting implementations of trait `Get` for type `std::boxed::Box<_>`:
--> src/lib.rs:11:1
|
5  | impl<T: Copy> Get for T {
| ----------------------- first implementation here
...
11 | impl<T: Get> Get for Box<T> {
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `std::boxed::Box<_>`
|
= note: downstream crates may implement trait `std::marker::Copy` for type `std::boxed::Box<_>`
```

Fix example for winnowing

---

book.toml

It would be nice to catch broken links a bit faster. The tradeoff is that we might end up with more spurious failures.
I propose that we shorten the cache timeout from 2 days to 1 day as an experiment.
Thoughts?

Reduce cache timeout to catch broken links faster.

---

examples/rustc-driver-example.rs
examples/rustc-driver-getting-diagnostics.rs
examples/rustc-driver-interacting-with-the-ast.rs
src/SUMMARY.md
src/rustc-driver-getting-diagnostics.md
src/rustc-driver-interacting-with-the-ast.md

Follow-up of [forum chat](https://internals.rust-lang.org/t/using-the-rustc-interface-crate/11982/20), https://github.com/rust-lang/rust/issues/71770, and [zulip chat](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/Is.20rustc_interface.20a.20rustc.20interface.3F)
Using `rustc_session::DiagnosticOutput::Raw` and parsing the resulting JSON seems to be the recommended way to get diagnostics from rustc, so this is a minimal example of how to do that.
The code example is long, but there are a bunch of top-level subtleties, and so I think it is necessary to give a complete working program. If we just give the central snippet, I think future readers will have difficulty figuring out the surrounding context they need to get the program to work.

Example of getting diagnostics

---

src/memory.md

Since rust-lang/rust#72055, `Predicate` is no longer a enum alias to `PredicateKind`, but is a struct containing a `PredicateKind`. Should we point to `PredicateKind` instead?

Update outdated reference to `ty::Predicate`

---

src/codegen/implicit-caller-location.md

since https://github.com/rust-lang/rust/pull/70916

Extern blocks are allowed for #[track_caller] now.

---

src/const-eval.md
src/miri.md

The main point of this PR is to update `tcx.const_eval` since it was separated into some `tcx.const_eval_*` queries.
The `const-eval` chapter is relatively short. But about the `miri` chapter, I'm totally not sure how we evaluate consts in Miri now instead of `tcx.const_eval`.
I just replaced `tcx.const_eval` with `tcx.const_eval_*` but I guess we could specify the query that we actually use in some places.
r? @oli-obk @RalfJung

Update docs related to const-eval/Miri

---

src/closure.md

Follow-up of https://github.com/rust-lang/rust/pull/72544.

Rename `upvars` query to `upvars_mentioned`

---

src/compiler-debugging.md

Add section for debugging rustc type layouts

---

src/query.md

I'm about to release version `0.6.0` of `mdbook-linkcheck` and found this broken link while testing it on the rustc dev guide. 
Hopefully I'm correct in guessing `high-level-overview.md` was renamed to `overview.md`. If not, let me know and I'll update it accordingly.

Broken Link to the high-level overview

---

src/SUMMARY.md
src/cli.md

This provides some guidelines on CLI flags. I'm sure there is more to say here, but this is a start.  Sourced from [rustc-ux-guidelines](https://github.com/rust-lang/rust/blob/e5335592e78354e33d798d20c04bcd677c1df62d/src/doc/rustc-ux-guidelines.md), https://github.com/rust-lang/rust/pull/70729, and my own experience.

Add some guidelines on the CLI.

---

src/diagnostics.md

This is a start on adding some guidelines for diagnostics. I would love to see more input from those who actually work on diagnostics, but I figure this might help get the ball rolling.
This is sourced from several places (RFCs, comments, [rustc-ux-guidelines](https://github.com/rust-lang/rust/blob/e5335592e78354e33d798d20c04bcd677c1df62d/src/doc/rustc-ux-guidelines.md)), along with my own editorializing.
cc #14

Add some guidelines on diagnostics.

---

src/tests/adding.md

Adds new examples to demonstrate how to use the UI error annotations idioms for expected error message : error line definitions
Also includes a comment about tidy lints of line length with these error annotations in UI tests which was a gotcha that I ran into this week.

Expand error annotations section with examples

---

src/tests/adding.md

This adds a [useful tip from @mark-i-m](https://rust-lang.zulipchat.com/#narrow/stream/196385-t-compiler.2Fwg-rustc-dev-guide/topic/https.3A.2F.2Fgithub.2Ecom.2Frust-lang.2Frustc-dev-guide.2Fpull.2F724) about UI test error annotation message substring support to address tidy line length requirements.
Associated #724

Add documentation of UI test error annotation message substring support

---

src/tests/adding.md
src/tests/intro.md

Document how to run tests on remote machines (which may be emulated).
This provides accompanying documentation for https://github.com/rust-lang/rust/pull/72704/, and should remain WIP until that is merged. 
r? @ehuss

[WIP] Document remote testing

---

src/diagnostics.md

Update lint declaration example

---

src/building/suggested.md

Closes #703.
cc @mark-i-m I've never used git worktrees before, can you check everything seems correct, and add things that may be missing?

Add more info on useful workflows

---

src/SUMMARY.md
src/appendix/background.md
src/appendix/glossary.md
src/early-late-bound.md

A lot of this is taken straight from Niko's writings here:
- https://gist.github.com/nikomatsakis/fe440aec437f7e8ad4cce8319954a973
- https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/reintegrating.20chalk.20into.20rustc/near/190518417
r? @nikomatsakis 
resolves #177 I think

Add a bit about various type system concepts

---

.travis.yml

The goal here is that people won't have to rebase over the latest master to get link fixes; instead, travis will automatically rebase on master before testing so that the latest fixes are automatically pulled in.
cc @rust-lang/wg-rustc-dev-guide This is unconventional to do in a CI tmk, so let me know if anyone sees problems here.
One disadvantage is that if there are conflicts, the build will fail, but I think that is acceptable.

Do a rebase before link checking

---

src/building/how-to-build-and-run.md

This command shouldn't be used very often, and it has its own whole
section below anyway.

Don't give `x.py clean` as the first x.py example

---

src/SUMMARY.md
src/getting-started.md

cc @rust-lang/wg-rustc-dev-guide @rust-lang/compiler @rust-lang/libs (not sure if I missed any other teams)
The eventual goal is to replace CONTRIBUTING.md and the README.md in rust-lang/rust with pointers to this document.
This is still very WIP, but it aims to address some of the concerns that WG-rustc-dev-guide was feeling with respect to organization, as well as some of the concerns that have come up in the contributor survey.
Feedback is welcome, especially on the structure and content of the document (e.g. if you feel something else should be added, or something should be removed)! It still pretty early, so I expect that this will change a bit before things settle.
Also, please excuse me if there is some delay in responding.

Getting started guide

---

src/ty.md

Blocked on https://github.com/rust-lang/rust/pull/70551

New tykind::error convention

---

src/building/how-to-build-and-run.md

The Rust codebase is large, not to mention the submodules. It would be helpful for some to have a warning or note about storage required before they spend possible hours to build, only to get a message in some form that they are running out/already out of storage. I did a stage1 build incrementally and it produced a build directory of about 14 gigabytes, which is where the estimated figure is obtained. If there's a way to make this statement better or more clear, I'm willing to help.

Add information about size for building the Rust Compiler

---

src/diagnostics.md

The guide is based on [existing rustdoc].
[existing rustdoc]: https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/struct.Diagnostic.html#method.span_suggestion
Not sure if this should be merged with the diagnostic style guide above. I didn't merge it because suggestions hadn't been talked about in detail at that point.

add suggestion style guide

---

src/SUMMARY.md
src/building/prerequisites.md

Fixes #722 
Currently only includes instructions for Windows, I didn't have a Linux machine available.
Taken from [@yoshuawuyts](https://gist.github.com/yoshuawuyts/9d0797afddd378e7cc06788c0a278c58) instructions.

Add prerequisite page

---

src/building/bootstrapping.md
src/overview.md

- Move most of the overview to building/bootstrapping.md
- Add things besides stages to bootstrapping.md
I didn't touch most of the existing `bootstrapping.md` because to be honest it looked really dense and I didn't want to read it 😅 
Addresses https://github.com/rust-lang/rustc-dev-guide/issues/674
r? @Mark-Simulacrum 
cc @mark-i-m

Revamp bootstrapping section

---

src/macro-expansion.md
src/name-resolution.md

Follows https://github.com/rust-lang/rust/pull/73813.

Rename resolvers following the latest rustc change

---

src/SUMMARY.md

Getting started feels more general than just "Building and debugging" ...
Thoughts?

Move Getting Started to a "prefix chapter"

---

src/SUMMARY.md
src/contributing.md

cc https://github.com/rust-lang/compiler-team/issues/296 @ecstatic-morse @rust-lang/compiler 
This PR moves CONTRIBUTING.md to the rust-dev-guide. It should not merge before #731. The objective is to point all new contributors in one place. In the contributor survey, a surprisingly high number of people (more than half) pointed to CONTRIBUTING.md as a major resource they use to contribute to the compiler, whereas the new "Getting Started" guide is likely a better place to start.
That said, the content in CONTRIBUTING.md is still useful, so we move it here and take the opportunity to also move some other contributing-related chapters together in the guide.
Feedback is welcome.

Move CONTRIBUTING.md to rustc-dev-guide

---

src/appendix/background.md
src/appendix/code-index.md
src/appendix/glossary.md

Not to write the part of Appendix `A` in heading along with other appendix.
before
Left side is Appendix A but heading is Appendix B.
after
Appendix part in heading is removed same as Appendix D, E or Z.

Fix the names of table of contents and heading are different

---

src/tests/intro.md

Companion to https://github.com/rust-lang/rust/pull/73952.

Update docs on using Docker images.

---

src/tests/intro.md

Follow-up for https://github.com/rust-lang/rust/pull/73650.

Fix link for armhf-gnu Dockerfile

---

src/contributing.md

I think these links would be better choices:
* The "search" link included PRs as well as issues, and didn't have a search field to actually enter a search term.
* Change the "new issue" link to give a choice of template.

Update bug report links.

---

src/implementing_new_features.md

I've introduced an explanation of "pFCP" abbreviation earlier in the text. Originally it was not very clear for me what "p" stands for until it was introduced later in the text.
Also fixed a typo: an -> a (probably a remnant from the days when it was followed by just "FCP" and not "pFCP").

Earlier clarification of pFCP abbreviation

---

src/SUMMARY.md

Left side is `Background material` but title is `Background topics`, so I fix it to `Background topics`. ( If `Background material` is preferrable, I fix it like that.)

Fix the difference of title in appendix A

---

src/getting-started.md

- Clean up wording
- Suggest `build --stage 1 src/libstd`, which doesn't recompile rustc
twice unnecessarily
- Fix rustdoc globs which only work on Linux
- Add suggestion for `build --stage 0 src/libstd`
- Suggest `-j1` for very slow builds
- Suggesting letting CI run tests when using a slow machine
Note that most of this will become outdated when/if https://github.com/rust-lang/compiler-team/issues/326 is implemented.

Improve getting-started guide

---

src/SUMMARY.md
src/backend/backend-agnostic.md
src/backend/debugging.md
src/backend/implicit-caller-location.md
src/backend/lowering-mir.md
src/part-3-intro.md

I think "Source Code Representation" is more natural than "Representations" here. Also fix some typos.

Fix distortions of "representation"

---

src/diagnostics.md
src/diagnostics/lintstore.md
src/memory.md
src/mir/visitor.md
src/overview.md
src/ty.md

Now it looks like `rustc_middle::*` is used not `rustc::*`.
I didn't change everything. For example, I didn't know if I should change `src/compiler-debugging.md` because it includes the backtrace message.

Change `rustc::*` to `rustc_middle::*`

---

book.toml

Now it causes timeout. And I think we don't have to check it since it won't be likely invalid or outdated. Let's take this opportunity to exclude it.

Exclude `rustaceans.org` from linkcheck

---

src/compiler-debugging.md
src/contributing.md
src/getting-started.md

- Fix a typo and wording
- Remove mention to `#t-compiler` on Discord
- Rename `rustc` to `rustc_middle`

Clean-up minor issues

---

src/backend/backend-agnostic.md
src/backend/codegen.md

The wasmtime renamed their default branch to `main` thus its link returns 404 now.
This replaces `master` with `HEAD` which is an alias for the default branch on GitHub, not `main`, just in case.

Fix links for cranelift

---

src/backend/monomorph.md

This PR elaborates on the existing documentation for polymorphization now that polymorphization has almost landed in rustc (rust-lang/rust#69749).
**Note:** CI will fail as this links to rustc rustdoc entries which won't exist until polymorphization is merged.

Expand on the documentation for polymorphization.

---

.travis.yml

Based on the discussion on Zulip: https://rust-lang.zulipchat.com/#narrow/stream/196385-t-compiler.2Fwg-rustc-dev-guide/topic/failing.20CI.20notifications
ref. https://docs.travis-ci.com/user/notifications/#configuring-email-notifications
cc @rust-lang/wg-rustc-dev-guide let me know if someone still wants to get emails.

Turn off travis' email notifications

---

src/SUMMARY.md
src/notification-groups/about.md
src/notification-groups/arm.md
src/notification-groups/risc-v.md
src/notification-groups/windows.md

~~This is still WIP as we don't have the Zulip stream (`#t-compiler/risc-v`) yet.~~
Now it's ready to review!

Add RISC-V notification group instructions

---

README.md
src/building/compiler-documenting.md
src/building/how-to-build-and-run.md
src/building/suggested.md
src/contributing.md
src/getting-started.md
src/queries/profiling.md
src/rustdoc.md
src/tests/running.md

⚠️ This should not be merged until https://github.com/rust-lang/rust/pull/73964 lands. ⚠️ 
- Update most pages to use `build`/`test` instead of `build --stage 1`
- Update pages to use `build --stage 2` instead of `build`
- Remove `debuginfo` from the example config.toml, since the defaults now match the recommended value.
I probably missed some `build` without --stage and some wording, but I figure the leftovers can be fixed in a follow-up PR.

Update docs to match the new x.py defaults

---

README.md
src/notification-groups/llvm.md
src/tests/intro.md
src/tests/running.md
src/walkthrough.md

So, we've migrated our CI to GitHub Actions almost, except for macOS.
There're some mentions to Pipelines and even Travis in the guide, let's replace them with GHA. I don't think we have to mention macOS build but any suggestions are welcome.

Adjust mentions about CI to GitHub Actions

---

src/SUMMARY.md
src/borrow_check/two_phase_borrows.md
src/mir/construction.md
src/overview.md

rust-lang/rust#74582 is merged, let's cut our hair here as well :)
The nightly rustc doc isn't updated so the links are currently broken.
Closes #806

Rename `HAIR` to `THIR`

---

src/overview.md

Follow-up of https://github.com/rust-lang/rust/pull/74826

Fix link/wording for `parse_nt`

---

src/name-resolution.md
src/parallel-rustc.md
src/queries/incremental-compilation-in-detail.md

- Enable a link `https://github.com/rust-lang/rust/issues/47389`
- Fix a broken link `https://crates.io/rayon`
- Fix typo

Some small fixes

---

src/SUMMARY.md
src/serialization.md

This documents serialization after rust-lang/rust#73851

Document serialization in rustc

---

src/building/how-to-build-and-run.md

- `verbose-tests` is for debugging the test harness, not the tests
themselves. See also https://github.com/rust-lang/rust/pull/76141
- `codegen-units` defaults to `256` whenever `incremental = true`. So
there's no need to explicitly set it to `0` if we already recommend
incremental. See also https://github.com/rust-lang/rustc-dev-guide/pull/795#discussion_r479762977.
r? @eddyb

Fix misguided suggestions in config.toml

---

src/compiler-debugging.md
src/mir/debugging.md

Documents the feature introduced in https://github.com/rust-lang/rust/pull/76074.
r? @tmandry 
FYI @wesleywiser

Adds documentation to cover spanview output

---

src/compiler-src.md

I noticed this was slightly out of date!

update docs to refer to the `compiler/` move

---

src/building/how-to-build-and-run.md

Several of the commands on 'how to build' use python.
But we haven't yet told the user how to install it!
Do that first before going into detail on how x.py works.

Link to 'prerequisites' immediately

---

src/backend/monomorph.md

The `<br>` make sure that the first two columns don't get completely wrapped.
Looks something like: 
r? @wesleywiser 
Closes https://github.com/rust-lang/wg-incr-comp/issues/2

Document CGU partioning in case of generic and inline functions

---

src/building/bootstrapping.md
src/building/how-to-build-and-run.md

Previously, 'How to build and run' had a long section on the different
stages of boostrap. But new contributors aren't interested in bootstrap;
they want to start their build (because they heard it takes forever and
want to start it so they aren't waiting more than necessary).
This moves the section on stages into the bootstrapping page, and links
there instead of discussing it on the main page.

Consolidate information about bootstrapping into one place

---

src/diagnostics/diagnostic-codes.md

- All codes are in one crate, `rustc_error_codes`
- Extended descriptions are loaded using `include_str!`
I wrote this just by looking at the code, not by talking with anyone about it, so this might not be perfectly accurate.
Follow-up to https://github.com/rust-lang/rustc-dev-guide/pull/838#discussion_r479810627.
r? @mark-i-m

Update error codes to match the current implementation

---

src/building/bootstrapping.md

The only thing I'm not sure of is whether this is a good place for the docs - maybe they should go in https://rustc-dev-guide.rust-lang.org/building/how-to-build-and-run.html instead?

Add information about default stages for x.py

---

src/building/suggested.md

Fix broken hyperlink

---

src/compiler-debugging.md

Just noticed the link was not correct. Fixed here.

broken intra-page link from spanview to graphviz

---

src/building/how-to-build-and-run.md

`build library/core` builds the compiler, not just the standard library.
cc @thomcc

Fix incorrect docs about stages

---

src/contributing.md

Clean up 'Contributing to Rust - Pull Requests'

---

src/stability.md

It looks like there was a copy and paste mistake
on the `#[rustc_const_stable(...)]` attribute section.

Correct stability attribute example

---

src/SUMMARY.md
src/mir/dataflow.md

Resolves #564.
I'm a few PRs away from transitioning all existing dataflow analyses in the compiler to the new framework, which can handle gen-kill problems as well as more general ones. When this is finished, we'll want to have an overview of the new framework in the guide.
This is a rough draft, and most of the links don't work since the module structure will change when the old framework is removed. For now, it exists mostly to prove that I've not forgotten about doing this :smile:.

Give overview of MIR dataflow framework

---

src/SUMMARY.md
src/hir.md
src/identifiers.md

@rust-lang/wg-rustc-dev-guide I don't really know what's the best way organizing all of this. I'm not satisfied with the HIR IDs being described in detail in both the HIR chapter and this new one, and at the same time I'm not sure we should remove them from the HIR chapter because they are needed to understand the rest of the chapter.
Replaces #759, closes #748.

Add a chapter on all the identifiers used through `rustc`

---

src/tests/adding.md

- Add a section for library tests
- Expand section on rustdoc tests
From https://github.com/rust-lang/rust/issues/76268#issuecomment-692867148

Improve instructions for adding a new test

---

src/const-eval.md

I believe this was changed in rust-lang/rust#74949, so r? @oli-obk

`ConstEvalResult` is now `EvalToConstValueResult`

---

src/mir/optimizations.md

I was confused about what the different levels mean. This PR adds a paragraph that shortly explains the rationale behind different mir-opt-levels and links to the current proposal where there's some information about them.
Let me know if I wrote something unreasonable or incorrect.

Link to the -Zmir-opt-level proposal

---

src/conventions.md

Cleans up a reference to copyright notices that are not supposed to be there in the first place.

Remove reference to copyright notices.

---

src/closure.md
src/compiler-src.md

Hello! 🦀  This PR contains 2 commits.
1. update description of `ByRef` borrows of closures
The current version of `src/closure.md` explains that `ByRef` borrows can either be `shared`, `shallow`, `unique` or `mut` (enum variants of [`rustc_middle::mir::BorrowKind`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/enum.BorrowKind.html)). 
However, the actual enum type used for representing borrows from closures seems to be a different type with the same name.  This PR updates the description for borrow types of closures. I found this out while tracking the type definitions.
([`InferBorrowKind`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_typeck/check/upvar/struct.InferBorrowKind.html) -> [`UpvarCaptureMap`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_midd …

update 'ByRef' borrow types of closures + minor fixes

---

src/getting-started.md

A link to the relevant section of the contributing documentation makes it easier for contributors to locate the relevant information. (e.g. via an in-page search for "doc".)
This is particularly important currently as e.g. https://github.com/rust-lang/rust/blob/85072e330394440776ace5ae612e3ced32ef6348/CONTRIBUTING.md links directly to the (currently `rustc`-focused) "Getting Started" guide rather than the general Rust contribution content to which it used to point.
Related:
* https://github.com/rust-lang/rust/pull/77195

Add link from "Writing Documentation" suggestion

---

src/getting-started.md

Follow-up to https://github.com/rust-lang/rust/pull/76631

Add docs for x.py setup

---

src/contributing.md

Linking directly to the relevant/example document source locations makes it easier for potential contributors to find the sources.
The choice of the `lib.rs` example is somewhat arbitrary based primarily on where I first encountered the question of where the docs were located:
* https://github.com/rust-lang/rust/pull/77195#discussion_r495115432
* https://github.com/rust-lang/rust/pull/77050

Add links to documentation sources.

---

src/cli.md

For instance https://github.com/rust-lang/rust/blob/master/compiler/rustc_mir/src/util/pretty.rs#L333

--verbose is useful when not compiling and when compiling

---

src/SUMMARY.md
src/git.md

Begins to address #850 .
I am mostly looking for feedback in these areas right now:
1. **Scope:** Does the current version assume too much or too little knowledge of git? Are there any big topics missing? For now, I have only focused on the things that are likely to be *necessary* to contribute. But there are a lot of additional helpful things that could be added. Should they be included in this page?
One thing that was mentioned in the issue that should probably be included is some documentation on dealing with submodules. Unfortunately, I have only a basic understanding of this myself so would not be comfortable writing this. Maybe someone else wants to pick this up, or it can wait for a future PR.
Another thing is addressing the capabilities of various IDEs more directly. I'm not sure …

Add section on using git

---

README.md
ci/check_line_lengths.sh

I've run into lots of annoying failures from this.
- Make it runnable without arguments
- Add it in the README
Open questions: How does this work on Windows (if at all)?

Recommend setting up `check_line_lengths` as a pre-commit script

---

src/getting-started.md

This is something that I found during reading the docs. All the other places have backticks around the `t-compiler` part, but this was the a part where it was missing.

add the last missing code highlight to t-compiler in the docs

---

src/git.md

`git merge-base master` does not work, you need
`git merge-base master HEAD` instead.
r? @jyn514

Fix instructions for squashing

---

src/appendix/bibliography.md

Fixes #906
I also couldn't find the paper on the website so let's use dl.acm.org's.

Fix the report link

---

src/building/suggested.md

Implemented in https://github.com/rust-lang/rust/pull/76349
r? @Mark-Simulacrum

Document new way to not build LLVM

---

src/profiling.md

Here I document what I learned while making rust-lang/rust#76680:
* How to use cargo-llvm-lines with x.py. 
* You can do `CARGOFLAGS="-Ztimings" ./x.py whatever` to get a nice timing chart.
* Unrelated, I played around with [tracy](https://github.com/wolfpld/tracy). Would need more work though to integrate with measureme.
~~This is blocked on dtolnay/cargo-llvm-lines#32.~~

Document the usage of cargo-llvm-lines and -Ztimings.

---

src/building/suggested.md

Talked about this in zulip, this makes it to cargo fmt and editor integrations kindof just work

add suggested workflow to setup nightly rustup for rust/

---

triagebot.toml

Allows anyone to change the status of PRs by using the `@rustbot modify labels` command, so [this](https://github.com/rust-lang/rustc-dev-guide/pull/905#issuecomment-703255140) is allowed now.

Allow anyone to change the status of a PR

---

src/building/bootstrapping.md

r? @Mark-Simulacrum 
Follow-up to #857
Closes #911

Document `Assemble` in bootstrap

---

src/building/suggested.md

This is a companion to [this PR](https://github.com/rust-lang/rust/pull/76356), which deals with including functionality for automatically running `tidy --bless` on each commit.

Add section describing git hook functionality

---

.travis.yml
book.toml
ci/linkcheck.sh

Closes #886
In this PR, we change the CI setup to only check files that have changed in the
most recent git commit. This means that changes in PRs are less likely to get
blocked on unrelated breakage (it's still possible if that breakage happens to
be in the same file).
On the other hand, we do want to periodically check all files. Currently, there
is a cron job that runs every day. We change the CI script to check if the
Travis run is a cron job and if so do a full link check. The hope is that by
having the cron job run often enough and preserving the linkcheck cache, we can
continue to find breakage relatively soon while avoiding the 429 Too Many
Requests issues we've been seeing.
This is currently blocked on a new mdbook-linkcheck release.

Linkcheck only changed files (except for cron jobs)

---

src/building/how-to-build-and-run.md

This makes the compiler faster to run without sacrificing too much
functionality. It still shows logging so contributors aren't confused by
`debug!` doing nothing.
This includes the changes from https://github.com/rust-lang/rust/pull/77701.
cc @Mark-Simulacrum

Recommend debug-logging instead of debug

---

src/git.md

Talk about git submodules

---

README.md

Following up #913, cc @mark-i-m @jyn514

Update installation instructions for `mdbook-linkcheck`

---

.travis.yml
README.md

We were using an alpha version before, pinned to a Git hash, so that we
could access a new feature (Michael-F-Bryan/mdbook-linkcheck#42).
Now there is a point release though (0.7.1), so we can update to that!

Use official mdbook-linkcheck version

---

src/pat-exhaustive-checking.md

A first pass at documenting pattern exhaustiveness. Given that the algorithm is very self-contained and well-explained in the source file, I didn't think it was useful to give more details.
See https://github.com/rust-lang/rustc-dev-guide/issues/657
Ping @mark-i-m

Explain pattern exhaustiveness checking

---

src/rustdoc-internals.md

It builds with stage 1 by default.
r? @jyn514 for correctness

Remove outdated build rustdoc --stage 1

---

src/rustdoc-internals.md

I forgot that --stage 0 is the default; I have it set to --stage 1 by default locally and forgot that it was my specific configuration.
cc @pickfire

Revert "Remove outdated build rustdoc --stage 1"

---

src/compiler-team.md
src/contributing.md
src/getting-started.md
src/tests/intro.md

We've migrated to bors.rust-lang.org, thanks to Pietro :)

Replace links to `buildbot2.r-l.o` with `bors.r-l.o`

---

src/getting-started.md

I think this would also help new contributors understand how the comment works.

Add reference PRs for `r?` and `r+` comments

---

ci/check-in.sh

Example usage:
```
$ ./check-in.sh
usage: ./check-in.sh <since> <number-of-prs-merged>
$ ./check-in.sh 2020-09-03
usage: ./check-in.sh <since> <number-of-prs-merged>
help: you can find the number of PRs merged at https://github.com/rust-lang/rustc-dev-guide/pulls?q=is%3Apr+is%3Aclosed+updated%3A%3E2020-09-03
$ ./check-in.sh 2020-09-03 72
Authors:
- **@1c3t3a**
- **@arora-aman**
... snip ...
Changes:
- Replace links to `buildbot2.r-l.o` with `bors.r-l.o` [#929](https://github.com/rust-lang/rustc-dev-guide/pull/929)
- Add reference PRs for `r?` and `r+` comments [#928](https://github.com/rust-lang/rustc-dev-guide/pull/928)
... snip ...
Changes in progress:
```
r? @spastorino

Add a `check-in.sh` script to automate writing markdown links for weekly check-in

---

src/building/prerequisites.md

- Migrate two sections about Windows
- Update the link to rust-lang/rust's README

Improve prerequisites section for Windows

---

src/SUMMARY.md
src/compiletest.md

* Improve wording
* Improve formatting

Clean up `compiletest` chapter

---

src/building/how-to-build-and-run.md

Document the newly added `x` binary that wraps `x.py`, which can be installed system-wide, and can be run from any subdirectory of a rust repo checkout.
This landed recently in https://github.com/rust-lang/rust/pull/78658, and I was requested to document it here.

Document `src/tools/x`, an `x.py` wrapper

---

src/compiler-debugging.md

Link didn't point to latest version of `env_logger` crate.
Add an explanation to disambiguate the RUSTC_LOG syntax.

Update link in compiler-debugging.md

---

src/rustdoc-internals.md

[Zulip discussion for context](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/r.23item.20in.20rustdoc's.20intradoclinks)
This adds some links to [htmldocck.py](https://github.com/rust-lang/rust/blob/master/src/etc/htmldocck.py) and the `@has`/`@matches` attributes to help with searchability in the dev guide.

Links to htmldocck/@has/@matches for searchability

---

CODE_OF_CONDUCT.md

This PR updates the broken link of the Code of Conduct from http://citizencodeofconduct.org to https://github.com/stumpsyn/policies/blob/master/citizen_code_of_conduct.md as discussed for other occurrences in the rust repositories in https://github.com/rust-lang/www.rust-lang.org/issues/1212 and implemented via https://github.com/rust-lang/www.rust-lang.org/pull/1215. 
Additionally it switches from using HTML linking to using native markdown syntax.

updated link for Citizen Code of Conduct

---

src/mir/optimizations.md

add mir-opt section for optimization fuel

---

src/param_env.md

`rustc_ty` was recently [renamed] to `rustc_ty_utils`, so this link has
to be updated.
cc @LeSeulArtichaut
[renamed]: https://github.com/rust-lang/rust/commit/f59d03038c8601a66bd165a2f1980109665d077c

Update `param_env` link

---

src/building/bootstrapping.md

An update to the documentation for passing RUSTFLAGS to stages.
Follows https://github.com/rust-lang/rust/pull/63722

Update bootstrap documentation with the new envvars for RUSTFLAGS

---

src/diagnostics.md

I don't know if there's an official guideline (that's why we need these docs!);
this is just what sounded reasonable to me.
r? @estebank

Document when errors should have an associated error code

---

src/SUMMARY.md
src/feature-gates.md
src/implementing_new_features.md

How to remove them and how to rename them.
cc <https://github.com/rust-lang/rust/pull/79336#discussion_r528627318>
cc @varkor

Document how to modify feature gates

---

README.md
ci/linkcheck.sh

- Fix typos in the README
- Don't echo all instructions in the linkcheck.sh shellscript; this is
noisy and unhelpful when developing locally. Verbose output is still
enabled in CI.
- Link to the index page for compiler docs, not `rustc_middle`
- Remove outdated instructions about avoiding 429s. These should no
longer be occurring locally now that we're using caching.
- Consolidate info about `mdbook` and `mdbook-linkcheck` near each other
r? @spastorino

Improve contributor experience for the dev-guide itself

---

src/tests/running.md

Add notes about running the UI test suite

---

src/SUMMARY.md
src/diagnostics.md
src/diagnostics/sessiondiagnostic.md

Documents the `#[derive(SessionDiagnostic)` macro implemented in https://github.com/rust-lang/rust/pull/75138.
cc @oli-obk

Document the SessionDiagnostic derive macro.

---

src/rustdoc.md

This makes a) makes it easier to find info about rustdoc's features and
b) redirects people in the wrong place to where they should be looking.

Link to the Rustdoc book in the rustdoc chapter

---

src/mir/index.md

It's nice to have the links as it aids looking up the basic MIR types. I keep returning to this page for a quick reference, and get annoyed each time that I need to then search in the crate :) This should fix my annoyance.

Add links to the rust documentation for all MIR structs

---

src/mir/index.md

- Remove dead reference to Mir. reflow sentence to talk about
`Body::local_decls`
- Fix broken links to render properly.
- Add links for `Terminator`, `RETURN_PLACE`, `ProjectionElem`.

Edit the Mir page to fix infelicities.

---

src/identifiers.md

r? @oli-obk
By the way, let me know if there are other people I can ping for review so I
don't assign every MIR PR to you :)
@rustbot modify labels: waiting-on-review

Add a section on identifiers in the MIR

---

src/tests/adding.md

Document `error-pattern` header

---

src/appendix/compiler-lecture.md

Added the following links as per the discussion in #778:
- [Responsive compilers - Nicholas Matsakis - PLISS 2019](https://www.youtube.com/watch?v=N6b44kMS6OM)
- [Things I Learned (TIL) - Nicholas Matsakis - PLISS 2019](https://www.youtube.com/watch?v=LIYkT3p5gTs)
- [Felix Klock - Subtyping in Rust and Clarke's Third Law](https://www.youtube.com/watch?v=fI4RG_uq-WU)
- [Felix Klock - Rust: A type system you didn't know you wanted - Curry On](https://www.youtube.com/watch?v=Q7lQCgnNWU0)
Only these links were added, none were removed, but they were reorganized to be closer grouped by topic and date.
The approximated date was also prefixed to the link text to give some sense of how old the information therein is.

[Fixes #778] Added and reorganized lecture links

---

src/backend/debugging.md
src/closure.md
src/compiler-debugging.md
src/diagnostics.md
src/hir-debugging.md
src/hir.md
src/llvm-coverage-instrumentation.md
src/mir/dataflow.md
src/mir/debugging.md
src/notification-groups/llvm.md
src/overview.md
src/profile-guided-optimization.md
src/profiling.md
src/profiling/with_perf.md
src/sanitizers.md
src/stability.md
src/tests/adding.md

[Fixes #614]
As mentioned in #614, `rustc` is invoked in different ways throughout the book, although there were not that many fixable instances. 
I ripgrep'd for `rustc\ ` and fixed the ones I found.

rustc invocation standarized

---

src/compiler-debugging.md

Update logging section and explain `RUSTC_LOG_COLOR`

---

src/early-late-bound.md

Caused by https://github.com/rust-lang/rust/pull/80163.

Fix broken link for `BoundRegion`

---

src/compiler-debugging.md

Also, renames `env-logger` to `env_logger`.

Fix "Potential incomplete link" error on compiler-debugging.md

---

src/compiler-debugging.md

It was mistakenly not removed in #997.

Remove old sentence that should have been removed

---

src/compiler-debugging.md

I made the mistake of not updating the config file on this machine I'm using which has never built rustc before. This was an easy fix (especially since I knew what the issue was), but I think this information should be more prominently placed.

Make instructions for configuring compiler for debug more explicit

---

src/identifiers.md

cc https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/changing.20error.20message/near/222198371
r? @jyn514

Point to `HirId` instead of `NodeId`

---

src/SUMMARY.md
src/about-this-guide.md
src/backend/backend-agnostic.md
src/borrow_check/region_inference/member_constraints.md
src/contributing.md
src/debugging-support-in-rustc.md
src/diagnostics.md
src/diagnostics/lintstore.md
src/git.md
src/llvm-coverage-instrumentation.md
src/miri.md
src/opaque-types-type-alias-impl-trait.md
src/overview.md
src/parallel-rustc.md
src/profiling.md
src/queries/incremental-compilation-in-detail.md
src/queries/profiling.md
src/queries/query-evaluation-model-in-detail.md
src/query.md
src/salsa.md
src/tests/intro.md
src/the-parser.md
src/traits/chalk.md
src/traits/lowering-module.md
src/traits/resolution.md

Searching for references to "future" and "currently", these non-contextualized (context-free? isolated?) sections have been identified and modified. 
In addition, the About This Guide and Contributing sections have been updated to reflect our policy of trying to contextualize future additions to the guide.

Add context to dated information

---

src/tests/adding.md

https://github.com/rust-lang/rust/pull/79959 added a tidy check to ensure the number of UI test entries. This PR documents it and adds a note not to place more tests on `src/test/ui` and `src/test/ui/issues` as possible.

Add a note about UI test entry limitation

---

README.md
src/part-5-intro.md

In this PR I have corrected the hyperlink for MIR in the page https://github.com/rust-lang/rustc-dev-guide/blob/master/src/part-5-intro.md
> So far, we've shown how the compiler can take raw source code in text format and transform it into ```MIR```. We have also shown how the compiler does various analyses on the code to detect things like type or lifetime errors. Now, we will finally take the MIR and produce some executable machine code.
The link that originally pointed to the highlighted ```MIR``` was incorrectly set to https://github.com/rust-lang/rustc-dev-guide/blob/master/src/mir/index.html. I have set it to https://github.com/rust-lang/rustc-dev-guide/blob/master/src/mir/index.md.
Plus, I have corrected a typo in the readme.md.

Corrected MIR file path and fixed a typo

---

src/getting-started.md

The hardware requirements section at https://rustc-dev-guide.rust-lang.org/getting-started.html#system-requirements has the line
>Recommended >=2 cores; more cores really helps.
This should be either
>Recommended >=2 cores; having more cores really helps.
where the verb help is being used in a singular form
or
>Recommended >=2 cores; more cores really help.
where the verb help is being used for the plural _cores_
The PR fixes this little error which makes the text better readable and technically better.

Fixed a grammatical error in hardware requirements section

---

src/getting-started.md

On the _Cloning and Building_ section on the page https://rustc-dev-guide.rust-lang.org/getting-started.html#cloning-and-building, the following line can be made better readable : 
> clone these immediately, but the build tool will automatically clone and sync them (more later).` 
In this PR, I have added the following : 
> clone these immediately, but the build tool will automatically clone and sync them (more on this later).` 
I believe this makes the text better readable and more precise technically.

improved the readablity of a line

---

src/building/bootstrapping.md

This was added in https://github.com/rust-lang/rust/pull/81064 (and shouldn't be merged until after that PR is merged).

Note that `x.py check` now allows using any stage

---

src/implementing_new_features.md

I want to link to an example PR before merging this, but putting this up just so I won't forget about it.

Link to `feature_err` in stability section

---

src/backend/updating-llvm.md
src/building/suggested.md

`download-ci-llvm` is available and enabled by default for all tier 1
platforms (since https://github.com/rust-lang/rust/pull/80932/), so there is no need to change it.
Using system LLVM over CI llvm is still supported, but is not recommended. Building LLVM from
source is still supported.
This also notes that you need to explicitly disable downloading LLVM
when updating the submodule.

Remove "Skipping LLVM build" section

---

src/backend/updating-llvm.md
src/compiler-src.md

Closes #1038.
cc rust-lang/rust#74787 rust-lang/rust#74862

Update links to `librustc_llvm` and `rustllvm`

---

src/building/bootstrapping.md

I was reading the book and I found a little bug. This fix turns x.py -> `x.py`

put `x.py` in ticks

---

src/tests/intro.md

Several of these test suites have been moved to `ui`, and I added a few that were undocumented.

Update test suite descriptions.

---

ci/check_line_lengths.sh
src/building/bootstrapping.md
src/stability.md
src/stabilization_guide.md

Closes https://github.com/rust-lang/rustc-dev-guide/issues/932.
r? @m-ou-se

Document how to stabilize a library feature

---

ci/check-in.sh

I think our checkins should look more like https://hackmd.io/Umz8k0PwRb-YVUUEK8i0aQ#2021-02-04, without authors and more condensed.
r? @jyn514

Make check-in.sh output in way that suggest to add only the most relevant info

---

src/SUMMARY.md
src/backend/libs-and-metadata.md

This adds a new chapter on library files and metadata, and how these things interact.
This leans a bit heavy from a Cargo/build-tools perspective, but I think this information is useful.  I think it is difficult to hit a good balance of too-much or too-little detail, since things tend to change a lot over time. Not sure if I hit the mark there.
I think this is pretty accurate, but I am not involved with compiler development a lot, so there may be some things that are incomplete or wrong.
Closes #468 (I think?)

Add chapter on libs and metadata.

---

src/bug-fix-procedure.md

Hi!
This patch just fixes a few typos in "Bug Fix Procedure".

Fix typo in Bug Fix Procedure

---

src/llvm-coverage-instrumentation.md
src/profile-guided-optimization.md
src/sanitizers.md

Their default branch is now main. Other failures should be addressed by #1043.

Point to main branch on llvm-project's links

---

src/diagnostics.md
src/git.md
src/llvm-coverage-instrumentation.md
src/opaque-types-type-alias-impl-trait.md
src/query.md
src/traits/chalk.md
src/type-inference.md

Fix date-check comment formatting
I realized that the format I had been previously using for date-checks
(as of January 2021 )
left a space before the closing parenthesis in the rendered output,
which looks weird.
I could fix this by removing the space between `2021` and ` January 2021)

Fix date-check comment formatting

---

src/compiler-src.md
src/overview.md
src/parallel-rustc.md
src/rustdoc-internals.md
src/tests/adding.md
src/type-inference.md

Closes #1046.
The biggest change was updating the list of rustdoc passes. Several new
ones have been added since that documentation was written, so I added
those, and I also sorted the list so it is roughly alphabetical (except
for the part for the `strip-*` passes, which I left in the same order
since one of the list items has two passes so there's no "correct"
order).

Update docs from date triage for 2021-02

---

src/backend/backend-agnostic.md
src/borrow_check/region_inference/member_constraints.md
src/compiler-src.md
src/contributing.md
src/diagnostics/lintstore.md
src/miri.md
src/overview.md
src/parallel-rustc.md
src/profiling.md
src/queries/profiling.md
src/queries/query-evaluation-model-in-detail.md
src/rustdoc-internals.md
src/salsa.md
src/tests/adding.md
src/tests/intro.md
src/the-parser.md
src/traits/resolution.md
src/type-inference.md

It turns out I missed several in #1066.

Fix formatting of more date references

---

src/getting-started.md

Fixes a small typo in the `getting-started.md` page.

Fixes typo in getting started guide

---

src/appendix/humorust.md
src/backend/updating-llvm.md
src/building/new-target.md
src/getting-started.md
src/traits/chalk.md

Fixes #1040. (And some other stuff.)

Update some out-of-date information

---

src/SUMMARY.md
src/rustdoc-internals.md
src/rustdoc.md

* Rename "The walking tour of rustdoc" to "Rustdoc overview",
which I think is a more accurate name
* Use same name in sidebar TOC as in chapter text
* Make links between the two chapters prominent
* Convert a few `.html` links to `.md`
Probably we should just merge the chapters, but leaving that for later.

Cleanup rustdoc chapters a bit

---

src/profiling.md

The `--emit=llvm-ir` emits an optimized LLVM IR. For optimized builds it will be
highly inaccurate estimate of the amount IR generated initially.  While the
inaccuracy can be somewhat reduce after disabling the optimization, that in turn
has other unintended consequences, since opt-level controls the emission of
lifetime markers, sharing of generics between crates, instantiation of inline
functions, etc.
Use `-Csave-temps` and `no-opt` bitcode as a basis for more accurate estimate of
initial work handed of to the LLVM.

Use more accurate estimate of generated LLVM IR with llvm-lines

---

src/building/prerequisites.md

LLVM requires at least cmake 3.13.4.
https://www.llvm.org/docs/CMake.html
Corresponding PR in https://github.com/rust-lang/rust/pull/82937

Update cmake version in prerequisites.md

---

src/borrow_check/region_inference/member_constraints.md
src/borrow_check/region_inference/placeholders_and_universes.md
src/mir/dataflow.md
src/param_env.md

Inspired by #1079. I used this command to find these typos:
rg --multiline --pcre2 '\b([a-zA-Z]+) \1\b' src -tmd
There were a couple false positives of the form "that that" meaning
"that it" or "that this".

Fix double-word typos

---

src/compiler-team.md

Probably my wording here is ungreat :). Feel free to start from my text and fix the weird english I've used :P.

Fix rust compiler meeting info

---

examples/rustc-driver-example.rs
examples/rustc-driver-getting-diagnostics.rs
examples/rustc-driver-interacting-with-the-ast.rs

remove the unused fields and change unknown field

Update rustc-driver-*.rs examples

---

src/rustc-driver-getting-diagnostics.md
src/rustc-driver-interacting-with-the-ast.md

Follow-up of #1095, now the docs mention the specific nightly version for the readers not to encounter a breaking change.
Also, extracted the example links from the snippets so that we can click them easily.

Add notes about nightly rustc version for the rustc-driver examples

---

src/tests/adding.md

I force-pushed this in the last commit and accidentally deleted the
github suggestion.

Add back example of `{{cwd}}`

---

src/mir/optimizations.md

Add quickstart for adding a new optimization

---

src/backend/updating-llvm.md

cc #1100
Related topic on Zulip: https://rust-lang.zulipchat.com/#narrow/stream/187780-t-compiler.2Fwg-llvm/topic/.22LLVM.20updates.22.20section.20on.20the.20rustc-dev-guide

Update the "LLVM updates" section

---

src/method-lookup.md

Change wording a bit: `module` => `crate`

---

src/building/how-to-build-and-run.md
src/building/suggested.md

This also suggests using `x.py setup` instead of copying config.toml.
Setting `profile = "tools"` is bad because not everyone wants that, but I don't know another good way to give a sample config.toml :/

Add sample nix shell

---

src/git.md

I have found it to be very helpful when rebasing.

Suggest using `git range-diff`

---

ci/check-in.sh

Link to Zulip search for finding the most recent check-in

---

src/contributing.md

This is by far the most common incantation contributors will need, so I think it'd be good to not have it just behind a link.
Fixes https://github.com/rust-lang/rustc-dev-guide/issues/1123

add 'waiting-for-review' incantation to main contrib page

---

src/llvm-coverage-instrumentation.md

r? @tmandry 
Before landing this PR, we should wait for:
* rust-lang/rust#84815 - because this new version of the dev guide document refers to a revised path to the Rust Unstable Book page on the compiler flag `-Z instrument-coverage`
* rust-lang/rust#84797 - because this new version of the document refers to coverage tests in `src/test/run-make`, the new location as of that PR

Update coverage docs

---

src/rustdoc-internals.md
src/rustdoc.md

Requested by @jyn514 on [zulip](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/compiling.20rustdoc.20lib.2Fstd/near/238041043)

Remove `--stage 1` argument from cheat sheet

---

src/contributing.md
src/git.md

rustfmt was recently changed from a submodule to a subtree (https://github.com/rust-lang/rust/pull/82208) so this accordingly updates a few rustfmt submodule references
cc @RalfJung and @Xanewok, as I largely did a lazy replacement of rustfmt wording in submodule-related sections with miri or rls since those seem to be the most used. Please let me know if any of those changes are off base though for your respective tools

update rustfmt references to reflect change from submod to subtree

---

src/diagnostics.md

I was a little uncertain about the relationship between these crates.

Describe the difference of rustc_lint vs rustc_lint_defs.

---

src/contributing.md

For example, Miri installs a recent toolchain directly from the master branch using `rustup-toolchain-install-master`.
This fixes the docs so they are no longer incorrect for Miri. I do not know what other tools do.

not all tools require waiting for a nightly release before they can be fixed

---

src/appendix/bibliography.md
src/compiler-team.md
src/identifiers.md
src/query.md
src/thir.md

Reference PRs/commits:
- https://github.com/rust-lang/rust/pull/85273
- https://github.com/rust-lang/rust/pull/85829/commits/1ef98856c741ceeeec8509c0d22698a531649f3f
- https://github.com/rust-lang/rust/commit/c47eeac61290cd3ef7994e0d68e754eb36d15001
And <http://www.cs.uwm.edu/faculty/boyland/papers/unique-preprint.ps> returns 403 now, therefore replace it with acm's one.

Fix some links

---

src/about-this-guide.md
src/contributing.md
src/git.md

I was a bit lost yesterday as I don't actually use git regularly in my day job. I tried to clarify some more common git workflows in a new section and add some more links to funnel people into reading git.md and the relevant sections:
1. had people use --ff-only (i think we EXPECT master to also ff, but before making this PR in this repo, it actually failed to fast-forward, so avoiding a merge commit there is good.) Also mentioned that you can apparently do `git config pull.ff only` to force this. I actually know little about the difference between --rebase and --ff-only, so perhaps we can clarify.
2. Made a new section called "Keeping things up to date" and went into more detail about how to keep feature branches up to date, how to rebase, and how to reset master onto upstream
3. added …

Add a section on keeping things up to date in the git section

---

src/stability.md

The previous one was not following the process we're documenting: it was a PR, which an FCP was started on after the fact. This doesn't match what the stated process is: we should instead link to an issue where t-libs started an fcp, then a pr was written later.

Change the feature used as an example of stabilizing lib features

---

src/stability.md

We stopped using allow_internal_unstable a while ago

---

src/tests/running.md

Document how to run unit tests

---

src/type-inference.md

Fixes #1116
Const variable was introduced in rust-lang/rust#59008.

Update "Inference variables" section

---

src/about-this-guide.md

the number of the parts should be seven if we count "Appendices" as one.

Correct the wrong serial number

---

src/contributing.md
src/git.md

Closes #900 (see the issue's comments for more details)

Remove requests or suggestions about rebase and fixup contradictory to rust-highfive bot comment

---

src/feature-gates.md

This was changed in https://github.com/rust-lang/rust/pull/86446 such that incompleteness is included in the declaration.

Document how to mark features as incomplete

---

src/ast-validation.md
src/backend/inline-asm.md
src/crates-io.md
src/debugging-support-in-rustc.md
src/feature-gate-ck.md
src/hir-debugging.md
src/identifiers.md
src/macro-expansion.md
src/name-resolution.md
src/type-checking.md

Create issues for many TODOs

---

src/compiler-src.md
src/diagnostics/lintstore.md
src/git.md
src/miri.md
src/parallel-rustc.md
src/query.md
src/salsa.md

Update around half of the January 2021 date references

---

src/diagnostics.md
src/diagnostics/lintstore.md

This change does a few things:
* Clarify some information around sources of lints (internal and builtin lints are now treated separately)
* Update information on future-incompatible lints which have undergone some changes due to Rust 2021
* Make some of the prose flow a bit better

Update information on lints

---

src/SUMMARY.md
src/lang-items.md

This is mostly the text from https://github.com/rust-lang/rustc-dev-guide/pull/978 with the exhaustive list of lang items removed.
cc @mikailbag, @nikomatsakis, @camelid

Document lang items

---

src/backend/libs-and-metadata.md

cc https://github.com/rust-lang/rust/pull/85804

Update for merge of CrateDisambiguator into StableCrateId

---

src/stabilization_guide.md

Fixes #1172.
Previously, readers had to scroll through tons of comments to find the
report.

Link directly to stabilization report comments

---

src/git.md

This is supposed to be a link but since it's using brackets for both URL and name, it's obviously not working.

git.md: Fix No-Merge Policy link

---

src/compiler-team.md

My reasoning is that PRs closed due to inactivity were neither closed by the team as rejected nor by the author as superseded by another PR or defective for whatever reason so they are more likely to contain things that could have made it.

Add S-Inactive PRs as another source of things contributors could work on

---

src/stability.md

As @m-ou-se pointed out in https://github.com/rust-lang/rust/pull/86879#issuecomment-892896170 `T-libs-api` should be used instead of `T-libs` for stabilization purposes.

Fixed team responsible for stabilization

---

src/backend/debugging.md

This adds a description of the `-opt-bisect-limit` LLVM option to the (very helpful!) doc on debugging LLVM. (We found this option to be essential in honing in on an LLVM optimization issue -- but it's not easy to find if you don't already know about it!)

Add description of -opt-bisect-limit LLVM option

---

src/building/new-target.md

The "Skipping LLVM Build" section was removed in 4e48f42e057a5e0736d256f02433e90acfb5fff5 (the `sysllvm` reference link was removed in 07b5693a90ff790b00635a2db020bb13f908c61a). The relevant bits were added back in ca851c6b709ce8e3323a3a134d0e6998c2e07f84 to this section so we should no longer need to link to anything anyways.

Remove a dead link in `new-target.md` + other nits

---

src/thir.md

This adds some more details about how the THIR works. It also adds as an example what some THIR looks like, along with some annotations I added.
Contributes to https://github.com/rust-lang/project-thir-unsafeck/issues/6. (cc @LeSeulArtichaut)

Expand THIR section with more details

---

src/query.md

Fix typo “a Rc” → “an Rc”

---

book.toml

Output of `mdbook build` currently includes
```
2021-08-27 22:01:01 [WARN] (mdbook::renderer): Renderer command `../../ci/linkcheck.sh` uses
a path relative to the renderer output directory `/PATH_TO/rustc-dev-guide/book/linkcheck`.
This was previously accepted, but has been deprecated. Relative executable paths should be
relative to the book root.
```
This PR aims to fix that.

Fix warning "Renderer command uses a path relative to the renderer output directory ..."

---

src/rustdoc-internals.md
src/tests/adding.md

Trailing date comments in a line inside of paragraph caused beginning of a new paragraph.
This PR fixes the 2 occurrences of that.
(I'm not sure if there's an underlying issue with mdbook or if this is working as intended.)

Fix trailing date comments in a line inside of a paragraph

---

src/building/suggested.md

This allows loading the sources for crates loaded from the sysroot. See https://github.com/rust-analyzer/rust-analyzer/issues/6842.

Add rustc-source to suggested rust-analyzer config

---

src/appendix/glossary.md

Add link to `Span`

---

src/SUMMARY.md
src/diagnostics/diagnostic-items.md

[:framed_picture:   **Rendered** :framed_picture:](https://github.com/xFrednet/rustc-dev-guide/blob/1188-diag-item-docs/src/diagnostics/diagnostic-items.md)
This PR documents the following aspects about diagnostic items:
* Background
* How To Find Diagnostic Items
* How To Add Diagnostic Items
* Naming Conventions
* How To Use Diagnostic Items
* Check For A Type
* Check For A Trait Implementation
* Associated Types
* Usage In Clippy
* Related Issues
I focussed on general information that is true for both, writing lints in rustc and Clippy. The documentation still contains some related links and comments about the usage in Clippy. I hope that this is a nice balance.
cc: @rust-lang/clippy, @rust-lang/wg-diagnostics 
---
**Meta**
Closes #1188
Also referencing rust-lang/rust-clippy#5393 for …

Documenting diagnostic items with their usage and naming conventions

---

src/overview.md

`parse_crate_mod` and `parse_mod` methods is in the `rustc_parse::parser::Parser`.

Fix a typo

---

src/diagnostics.md

This is just a small clarification on the difference of a help vs note diagnostic, since I was a little uncertain and found a lot of inconsistency in the codebase.
See https://rust-lang.zulipchat.com/#narrow/stream/147480-t-compiler.2Fwg-diagnostics/topic/help.20or.20note/near/252087989 for more context.

Clarify difference of a help vs note diagnostic.

---

src/constants.md

blocked on https://github.com/rust-lang/rust/pull/87280
still not too happy with what I wrote here, pls review :heart:

`ty::Unevaluated`: dealing with unused substs

---

src/building/suggested.md
src/getting-started.md

Compare [this discussion on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Which.20rustfmt.20does.20x.2Epy.20fmt.20use.3F/near/253672905) ([archive](https://zulip-archive.rust-lang.org/stream/122651-general/topic/Which.20rustfmt.20does.20x.2Epy.20fmt.20use.3F.html#253672905)).

Suggests `--edition=2018` argument when using stage0/bin/rustfmt directly

---

src/building/suggested.md

I just noticed this inconsistent indentation after looking back at the result of #1207.

Make indentation consistent in example vscode config file

---

src/closure.md

Fix a typo on closure.md

---

src/backend/backend-agnostic.md
src/contributing.md
src/rustdoc-internals.md

Update some docs from 2021-10 date triage

---

src/diagnostics.md

As the title says, some minor adjustments. I've also updated the backtick example, as mdBook currently doesn't render them correctly. (It's expected that this originated from `mdbook-toc`, the related issue is: badboy/mdbook-toc#23)

Some minor adjustments to the diagnostic documentation

---

src/building/bootstrapping.md

Mainly revises the stages overview, using paragraphs instead of bullet points.

Edit bootstrapping chapter

---

src/contributing.md

Have found the branch consideration to be a crucial piece when dealing with subtrees and think it warrants being called out explicitly here as well. The Clippy docs are fantastic, so worth including a direct link as well

Make subtree docs an overview and add link to clippy docs for details

---

.github/workflows/date-check.yml
src/overview.md
src/rustdoc-internals.md
src/tests/intro.md

- Ensure date-check cron job is using latest stable Rust
- Update some date-check comments

Do some date triage for 2021-11

---

src/building/suggested.md

In the suggested workflows page there is an example settings.json file that many people use.  It uses a placeholder `TARGET_TRIPLE` in the file name, but many people, myself included on one occasion, forget to replace it or don't notice that it needs replacing.  This adds an emphasized note that should help remind people that replacing the triple is necessary.
Closes #1219

Add note to emphasize replacing TARGET_TRIPLE

---

src/building/bootstrapping.md

The italics added in #1239 broke the implicitly-resolved link.

Fix broken link in "Bootstrapping"

---

src/tests/running.md

I got the list of possible compare-modes from here: https://github.com/rust-lang/rust/blob/65b3c853178b04c5cbe41f26e6a1b1b90d7b8cc6/src/tools/compiletest/src/common.rs#L120
And I determined that compare-modes are separate to revisions from observing the behavior of tests like: https://github.com/rust-lang/rust/blob/56ebd57960efd1d96c142b456add67b5257c21fb/src/test/ui/regions/regions-outlives-projection-container-wc.rs

Fix compare-mode documentation

---

src/diagnostics/diagnostic-items.md

I found the previous link name has already changed, so I made it up-to-date.

Fix an invalid link on Diagnostic Items

---

src/SUMMARY.md
src/mir/drop-elaboration.md

I've focused on the "big picture" rather than trying to describe the existing pass from the bottom up. There are some subtleties (mostly around unwinding) that I don't fully understand. I did not implement the existing pass, so it's possible that I've missed something, but I think what I've described has been described correctly.
This (or something like it) was requested as part of the stabilization of rust-lang/rust#73255. I've included a section on the relationship between drop elaboration and const-checking which assumes that `#![feature(const_precise_live_drops)]` is merged.
cc @nikomatsakis @cramertj

Describe drop elaboration

---

examples/rustc-driver-example.rs
examples/rustc-driver-getting-diagnostics.rs
examples/rustc-driver-interacting-with-the-ast.rs

I used 1.58.0 nigthly to compile but compilation should be supported since 1.56.0 nightly

Update examples for latest compiler version

---

src/tests/adding.md

This adds some more documentation for compiletest headers.

Document more compiletest headers.

---

src/backend/libs-and-metadata.md
src/building/bootstrapping.md
src/constants.md

Separating from #1259 because I'm not 100% sure if `compute_hir_hash` is the right link.
cc @cjgillot could you review this?

Fix some more links

---

src/building/how-to-build-and-run.md
src/tests/running.md

I started rustc development by running tests without ever directly invoking the compiler.
Because of this the `Running tests manually` section didnt work for me and it wasnt clear what I had to do to fix it.
I added a link to the prereq section to avoid similar occurrences in the future.
I also added a note explaining how rebuilding rust will affect the toolchain added to rustup.

Improve 'Running tests manually' section

---

src/llvm-coverage-instrumentation.md

rust-lang/rust#91207 updates the coverage mapping format to Version 5 or
6, depending on the built-in version of LLVM (12 or 13, respectively).
This change updates the dev guide to match the recent changes.
(Note, this PR replaces #1235 with slightly more up-to-date description of the new behavior.)
r? @tmandry

Update LLVM coverage mapping format version supported by rustc

---

src/contributing.md
src/getting-started.md
src/walkthrough.md

* Whenever its mentioned that the bot randomly assigns someone I added that its based on the files you touch.
+ I think this is an important detail because otherwise, at least personally, I worry about trying to assign to an appropriate user but knowing that there is some intelligence behind the bots decision is reassuring.
* I added documentation for assigning to a group/team.
+ This is a useful feature but isnt documented anywhere.
+ I'm not sure which file describing `r?` I should put it in but contributing.md seemed like the one most suitable for  extensive documentation

Improve documentation on r?

---

src/hir.md
src/mir/optimizations.md
src/profiling.md

Fixes #1269.
- Fix some broken links
- Update HIR chapter to use `HirId` instead of `NodeId`

Fix some broken links

---

src/rustdoc.md

Use current paths when discussing source files.
Update cheat sheet section with download-rustc.
Add "use cases" section.

Update rustdoc internals

---

src/rustdoc-internals.md

The inline code wasn't being rendered correctly.

Move date-check comment to fix Markdown syntax

---

src/building/how-to-build-and-run.md
src/building/prerequisites.md
src/getting-started.md

The "Getting Started" chapter begins with:
> This documentation is not intended to be comprehensive; it is meant to be a quick guide for the most useful things.
But this isn't true! For a lot of things the "Getting Started" chapter has as much or more detail than subsequent chapters.
This PR streamlines some parts of "Getting Started", so it genuinely is just a brief guide. Extraneous details are removed or moved into the appropriate later chapter.

Streamline "Getting Started"

---

src/building/how-to-build-and-run.md
src/conventions.md
src/getting-started.md
src/rustdoc.md
src/tests/running.md

This is a follow-up to #1279.
The "Getting Started" chapter is, TBH, pretty bad when it comes to the
stuff about building and testing. It has far too much detail and lots of
repetition, which would be overwhelming to a newcomer.
This commit removes most of it, leaving behind just quick mentions of
the most common `x.py` commands: `check`, `build`, `test`, `fmt`, with
links to the appropriate chapters for details. There were a few
interesting details that weren't covered elsewhere, so I moved those
into other chapters.

Streamline "Getting Started" some more.

---

src/implementing_new_features.md

* I've never heard the term "pFCP" used before, so spell it out as
"proposed final comment period"
* Fix some unclear things (like implying that you need `r+` rights to
start an FCP)
* Improve the chapter's title, and make it consistent with its TOC entry
* Make some other assorted minor cleanups and improvements

Clean up section about FCPs

---

src/about-this-guide.md
src/backend/codegen.md
src/backend/monomorph.md
src/building/bootstrapping.md
src/building/compiler-documenting.md
src/building/how-to-build-and-run.md
src/building/suggested.md
src/compiler-src.md
src/compiletest.md
src/contributing.md
src/crates-io.md
src/diagnostics/diagnostic-items.md
src/macro-expansion.md
src/overview.md
src/test-implementation.md
src/tests/intro.md
src/tests/running.md
src/ty.md
src/walkthrough.md

This will make the documents more consistent, because in the most cases the `Rust` name is used. I think this also makes sense, because the name of the language should be capitalized.

Spelling: Rename `rust` to `Rust`

---

src/SUMMARY.md
src/asm.md

This PR adds information about the internals of inline assembly in the compiler, including instructions to follow when adding `asm!` support for a new architecture.
Fixes #686

Add inline assembly internals

---

src/contributing.md

Reading the docs [here](https://rustc-dev-guide.rust-lang.org/contributing.html#r) I thought `r?` only applied to the original PR description. @nagisa  [pointed out](https://github.com/rust-lang/rust/pull/92835#issuecomment-1018006922) out that it should work in comments, so adding that information to the guide seems relevant as it currently only talks about the initial description.

Clarify that r? works in comments.

---

src/git.md

Expanded a note to try to stress what you need to do if you're playing games with submodules.
(I overlooked this when cherry-picking an LLVM commit today, and wasted some time wondering why I wasn't seeing any effect in my resulting `rustc` build...)

git.md: more notes on x.py and git submodules

---

src/stabilization_guide.md

@cchiw stumbled across this in their PR, turns out we do build integration tests for stdlib/rustc crates on stage0.

mention test folders for cfg(bootstrap)

---

src/crates-io.md
src/diagnostics/diagnostic-items.md
src/diagnostics/lintstore.md
src/git.md
src/tests/compiletest.md

Triage some date references

---

src/building/how-to-build-and-run.md

The [bootstrapping chapter](https://github.com/rust-lang/rustc-dev-guide/blame/master/src/building/bootstrapping.md#L185) states:
> `build --stage N compiler/rustc` **does not** build the stage N compiler:
> instead it builds the stage N+1 compiler _using_ the stage N compiler.
That is in conflict with the "How to build and run" chapter that states:
> `./x.py build --stage 2` – builds the stage2 compiler
I believe the former is correct.

Correction, building stage3 compiler

---

src/getting-started.md

Closes https://github.com/rust-lang/rustc-dev-guide/issues/1254.

Link to The Rust Performance Book

---

src/appendix/glossary.md

Adds back-ticks to a few terms that appear in code.
Clarify that `tcx` is a convention.

Edit glossary

---

src/llvm-coverage-instrumentation.md
src/profile-guided-optimization.md

* `-C symbol-mangling-version=v0` has been stabilized in https://github.com/rust-lang/rust/pull/90128
* `-Z instrument-coverage` has been stabilized in https://github.com/rust-lang/rust/pull/90132

Update for recent stabilizations

---

src/tests/headers.md
src/tests/ui.md

The `known-bug` header was added in https://github.com/rust-lang/rust/pull/93953.

Add known-bug header.

---

src/profiling.md

`--timings` was stabilized in 1.60 via https://github.com/rust-lang/cargo/pull/10245

cargo timings has been stabilized

---

src/building/prerequisites.md

update winget install instructions to ensure proper packages are installed (-e for --exact, and full package names to ensure arbitrary packages from the msstore source aren't installed)
fixes #1324

fix winget install instructions installing wrong packages

---

src/constants.md

after reverting a part of https://github.com/rust-lang/rust/pull/87280 in https://github.com/rust-lang/rust/pull/92805 this was out of date.
Also generally extended that section to be a bit more helpful hopefully.

update section for type system constants

---

src/miri.md

Update miri.md: correct a minor typo

---

src/building/suggested.md

This circumvents an issue on newer OSes (including now macOS Monterery):
rust-lang/rust#71818
Thanks to jyn514 for suggesting this fix.

r-a: Use `python3 x.py` instead of `./x.py`

---

examples/rustc-driver-example.rs
examples/rustc-driver-getting-diagnostics.rs
examples/rustc-driver-interacting-with-the-ast.rs

Specifically this handles 2 changes in upstream : 
1. Remove Config::stderr - https://github.com/rust-lang/rust/commit/5eeff3f0733c83be9e0406874e92adf24a5cf2b6
2. Add Config::crate_check_cfg  - https://github.com/rust-lang/rust/commit/3a73ca587bb8a8fb52d6045fbe31d50d5a56ff19

Update examples with 1.61.0-nightly (latest version)

---

src/conventions.md
src/crates-io.md

Today I was deciding between tinyvec and smallvec for a hobby project, I remembered seeing one of them in the compiler's allowed crate list a while back. This list is a very useful resource (even outside of rustc) as it indicates a certain level of quality and maintenance.
I couldn't really find the link to the list easily this time, because I found the [paragraph in the coding conventions page](https://rustc-dev-guide.rust-lang.org/conventions.html#using-crates-from-cratesio) instead of the [page on crates.io dependencies](https://rustc-dev-guide.rust-lang.org/crates-io.html) with the actual link.
This PR replaces the paragraph in the conventions with a link to the page detailing the dependencies. The second commit changes the commit hash to the link from a commit on [2 August …

Consolidate crates.io convention section

---

src/diagnostics/sessiondiagnostic.md

Updates documentation on `#[derive(SessionDiagnostic)]` now that it can be used for translatable diagnostics.
~~Waiting on rust-lang/rust#95512 to be merged and for me to add links to the source after it has.~~

sessiondiagnostic: translation

---

src/borrow_check/region_inference/placeholders_and_universes.md

The `'b` in `let y` was an unbound region. Presumably this was meant to be `'c`.

Minor type fix

---

src/stabilization_guide.md

Because sending people doing library stabilization to `feature_gate.rs` will just result in confusion.

Send people doing *library* stabilizations over to the std-dev-guide

---

src/backend/debugging.md

As a drive-by, I fixed some out of date stuff (e.g. point to the relatively new LLVM github repo to which they've migrated their issues).
But my main focus was on capturing things I learned  or relearned over the past month or so.

Extend debugging llvm section

---

src/overview.md

Re-writes this section in cohesive paragraphs and sections.
For reviewers: I know the diff is massive, but I promise this is faithful to what was there before. 😇

Edit "What the compiler does to your code"

---

src/constants.md

Should probably go more in-depth here, but that isn't something I have the time for rn :sweat_smile: this should probably be merged with the explanation in https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.WithOptConstParam.html

mention `WithOptConstParam`

---

src/stability.md

This should be merged along with rust-lang/rust#95960.

Update docs for deprecated attribute

---

src/building/suggested.md

See https://github.com/rust-lang/rust-analyzer/pull/12010 and https://github.com/rust-lang/rust-analyzer/pull/12213
r-a should automatically patch the old configuration, but we might just as well suggest the new one :)

Fix configuration names for vscode/r-a

---

src/tracing.md

Support for automatic logging of all queries was recently added in https://github.com/rust-lang/rust/pull/96697.
Perhaps @oli-obk could review?

Add docs for logging of queries.

---

src/compiler-src.md

Makes various edits for clarity, style, readability, and formatting.

Edit the "Compiler Source Code" chapter

---

src/building/new-target.md

I have occasionally seen people get tripped up by the issue where if you use `patch` to a local path dependency, the build starts failing due to `deny-warnings`. This adds a note about this possible issue.

Add note about patching dependencies and warnings.

---

book.toml

https://tomlee.co/2014/04/a-more-detailed-tour-of-the-rust-compiler/ returns 404 on CI even though it's not actually 404.
So, that doesn't return any useful result, let's ignore it.
Also, formatted the exclude list for readability.

Exclude `tomlee.co` from link-checking

---

src/rustdoc-internals.md

- fixed one broken link
- updated date reference
- removed the mentions to `unindent-comments` pass as per https://github.com/rust-lang/rust/commit/7803a411517f0f1e64d8f37ce377c684d1f2d1fd
cc #1344

Cleanup rustdoc-internals

---

src/traits/chalk.md
src/traits/resolution.md

Address renaming of the types team, previously wg-traits.
r? @rust-lang/types 
cc #1344

Triage some date references related to traits

---

examples/rustc-driver-example.rs
examples/rustc-driver-getting-diagnostics.rs
examples/rustc-driver-interacting-with-the-ast.rs
src/rustc-driver-getting-diagnostics.md
src/rustc-driver-interacting-with-the-ast.md
src/rustc-driver.md

Updates rustc-driver related examples to the latest nightly (I forgot to update the references on #1330 :P).
cc #1344

Update rustc-driver related examples

---

src/building/how-to-build-and-run.md

When building and testing on a new system (without an installed `nightly` toolchain), the default behavior of `rustup link` can seem a bit surprising, namely that it uses **stable** `cargo`. This change adds a note to the section on `rustup link` to help clarify what's happening and how to fix it.
I think it would also make sense to include a note about how to get `rustup link` to use a cargo compiled with `./x.py build cargo`, but I haven't yet figured out how to do that.

Clarify cargo fallback behavior for rustup link

---

src/building/suggested.md

For some reason, using `procMacro.ignored` does not seem to work (many functions were missing from analysis because `#[tracing::instrument]` apparently expanded to nothing), so this config makes them work properly instead.

Make build scripts and proc macros work with the suggested rust-analyzer config

---

src/borrow_check/type_check.md

cc https://github.com/rust-lang/rust/pull/96515#pullrequestreview-978632387 @nikomatsakis 
Should maybe talk a bit more about how the user type gets computed when lowering patterns, but for that I would want to take more time to look at that code first :sweat_smile:

add section on user types

---

src/tests/compiletest.md
src/tests/headers.md
src/tests/running.md
src/tests/ui.md

NLL compare mode was removed in https://github.com/rust-lang/rust/pull/95565.

Remove nll compare mode.

---

src/tests/compiletest.md

This option was also removed, see https://github.com/rust-lang/rustc-dev-guide/pull/1366#discussion_r892701796.

Remove mention of -Zborrowck=mir with Polonius.

---

src/tests/docker.md

Found what I believe to be a tiny spelling mistake when reading the guide.

Replace the word "later" with "latter" to refer to the latter OS in a sequence

---

src/diagnostics.md

Also, RUST_BACKTRACE=full is now default

small improves

---

src/appendix/humorust.md

The PR wasn't merged, but neither was the rustc-ty punfest, so I think it belongs here.

humorust: Forbid pineapple on pizza

---

src/diagnostics/diagnostic-structs.md

Update the documentation for diagnostic structs to use the new typed identifier syntax for referring to slugs (after rust-lang/rust#98428).

diagnostics: structs with new slug syntax

---

src/building/suggested.md

`editor.formatOnSave` is not rust-lang/rust specific, so I think we should leave that decision to the user. Also many test files in the rustc repo are not formatted so this will make diffs unnecessarily big.
I also grouped the enabling of proc macros and build scripts together since it kind of feels like a related thing. ;)

leave formatOnSave to the user

---

src/lowering.md

It doesn't look like the old path ever existed.

Fix path to hir_id_validator.rs

---

src/building/suggested.md

Bootstrap is no longer in the workspace since #97513.
See https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/.E2.9C.94.20ra.20stopped.20working.20in.20rust-lang.2Frust.3F.

Add the config needed to get rust-analyzer working on src/bootstrap

---

src/building/suggested.md

This shouldn't be merged until after https://github.com/rust-lang/rust/pull/98745.
I kind of want to add --build-dir to the suggested command directly, since I doubt people are reading the rest of the docs, but I worry that will cause unnecessary slowness for people with few cores ... not sure the right approach.
cc @thomcc

Suggest a separate build directory for rust-analyzer

---

src/building/suggested.md

Cargo check isn't supported and gives an error that CFG_CHANNEL is missing.
It also generates a new target dir and recompiles dependencies.
Use x.py instead, which avoids both issues.
cc @jonas-schievink

Use `x.py check` instead of `cargo check` for build scripts

---

src/building/suggested.md

This reverts commit d955bab63c229c3160e3023f44496ad93a81f3ab.
cc @jyn514 @RalfJung 
As @RalfJung [noted here](https://github.com/rust-lang/rustc-dev-guide/pull/1381#issuecomment-1174007794=) this doesn't work.

Revert "Add the config needed to get rust-analyzer working on src/bootstrap (#1381)"

---

src/building/bootstrapping.md
src/building/compiler-documenting.md
src/building/how-to-build-and-run.md
src/building/suggested.md
src/contributing.md
src/profiling/wpa_profiling.md
src/rustdoc-internals.md
src/rustdoc.md
src/tests/intro.md
src/tests/running.md

Since https://github.com/rust-lang/rust/pull/95503, `library/std` means
"build just std and its dependencies"; to get the old behavior that built
`proc_macro` and `test`, you need `x build library`.
- Update `library/std` to `library`
- Remove the `-i` suggestions; `incremental = true` is already the default for most profiles, in
which case `-i` does nothing. If you don't have incremental enabled, I still think suggesting `-i`
is bad idea, because it's easy to forget once, at which point you'll end up rebuilding the whole
compiler / standard library.
- Remove a few repetitive sections and don't discuss incremental in such detail
Incremental works well enough that it should "just work" for most people;
I don't think it needs multiple paragraphs of explanation so early in the guide.
- …

Update the build instructions for the standard library

---

src/asm.md
src/backend/monomorph.md
src/building/bootstrapping.md
src/lang-items.md
src/salsa.md

This was with help of typos-cli crate

fix some typos

---

src/building/how-to-build-and-run.md
src/contributing.md
src/implementing_new_features.md
src/macro-expansion.md
src/mir/optimizations.md
src/overview.md
src/parallel-rustc.md

Used the following command (in fish), followed by some manual tweaking:
sd 'https://rustc-dev-guide.rust-lang.org/(.+).html' '$1.md' (fd)

use relative links

---

src/contributing.md

The docs changes are now reviewed by a specific team (e.g. t-libs, t-compiler) or the [docs group](https://github.com/rust-lang/highfive/blob/da54dc554f153481656f2cbbbf6591ca3cf226a1/highfive/configs/rust-lang/rust.json#L46-L50) and suggesting `r? @steveklabnik` is inaccurate (actually this is referenced by a contributor, e.g. https://togithub.com/rust-lang/rust/pull/98651#issue-1288041815). Since mentioning a specific user often gets outdated. the example should only show how you specify a reviewer. This removes a mention of Steve and replaces them with `@awesome-reviewer`, a placeholder.

Remove a mention to Steve on r? example

---

src/SUMMARY.md
src/building/compiler-documenting.md

I thought this was about documenting things, not building documentation.
Also, it's more than just building compiler documentation.

replace misleading name

---

src/contributing.md

They moved to the clippy book!

Fix link to clippy sync docs

---

src/tests/compiletest.md

Updated compiletest in https://github.com/rust-lang/rust/pull/99488 to allow revisions for debuginfo tests.

Debuginfo tests now also support revisions.

---

src/contributing.md
src/git.md

It used to be a submodule.
cf. https://github.com/rust-lang/rust/pull/99603
Closes https://github.com/rust-lang/rustc-dev-guide/issues/1407

rust-analyzer is now a subtree

---

src/building/new-target.md

This PR add the instructions to fix the build errors that may happen after adding a new target to compiler and adding support in std.
cc @jyn514 @Mark-Simulacrum 
Fixes https://github.com/rust-lang/rust/issues/99901

Add instructions to fix build errors in std after adding a new target

---

src/building/compiler-documenting.md

it's a tiny chapter, so made it lightweight by doing bullet points instead of section headers

revamp doc-build chapter

---

ci/date-check/src/main.rs

It's not just non-digit, it's alphabetic

date-check: be more strict

---

src/building/bootstrapping.md

Closes #1419.
This diagram is based on the diagram in Joshua Nelson's talk on
bootstrapping at RustConf 2022 [1]. I converted it to Mermaid and made
some tweaks to simplify it and bring it closer to bootstrap's
terminology, and then Ralf Jung added nodes for copying artifacts.
[1]: https://rustconf.com/schedule#bootstrapping-the-once-and-future-compiler
Co-authored-by: Joshua Nelson <github@jyn.dev>
Co-authored-by: Ralf Jung <post@ralfj.de>
r? @jyn514

Add bootstrapping diagram

---

src/building/bootstrapping.md

Your comment at https://github.com/rust-lang/rustc-dev-guide/pull/1421#issuecomment-1209923775 made me realize this needed to be fixed :)
r? @jyn514

Fix legend colors in dark mode

---

src/backend/updating-llvm.md

Also, make link to upstream llvm repo clickable

move references down to avoid clutter

---

src/compiler-debugging.md

From https://github.com/rust-lang/rustc-dev-guide/issues/1409#issuecomment-1207225605

Add gdb tips for symbol-mangling-version

---

src/crates-io.md

date-check: crates-io

---

src/diagnostics/diagnostic-items.md

Improve the "Diagnostic items" chapter
